opensearch-project/ml-commons

.github/workflows/CI-workflow.yml
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
common/src/main/java/org/opensearch/ml/common/parameter/MLInput.java
common/src/test/java/org/opensearch/ml/common/transport/prediction/MLPredictionTaskRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/training/MLTrainingTaskRequestTest.java
docs/how-to-add-new-function.md
gradle.properties
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngineClassLoader.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/sample/LocalSampleCalculator.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineClassLoaderTests.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/task/MLExecuteTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java

support registering ML objects; refactor ML engine interface

support registering ML objects; refactor ML engine interface

---

.github/workflows/CI-workflow.yml
gradle.properties

bump to 1.2.3

---

.github/workflows/CI-workflow.yml
gradle.properties

bump to 1.3.0

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/training/MLTrainingTaskExecutionTransportAction.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
plugin/src/main/java/org/opensearch/ml/model/MLTask.java
plugin/src/main/java/org/opensearch/ml/model/MLTaskState.java
plugin/src/main/java/org/opensearch/ml/model/MLTaskType.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/indices/MLIndicesHandlerTests.java
plugin/src/test/java/org/opensearch/ml/model/MLTaskTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java

1. Refactor ML task data model
2. Add create ML task index method

refactor ML task data model; add create ML task index method

---

client/build.gradle
client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
common/src/main/java/org/opensearch/ml/common/transport/execute/MLExecuteTaskRequest.java
common/src/main/java/org/opensearch/ml/common/transport/execute/MLExecuteTaskResponse.java
common/src/main/java/org/opensearch/ml/common/transport/prediction/MLPredictionTaskResponse.java
common/src/main/java/org/opensearch/ml/common/transport/trainpredict/MLTrainAndPredictionTaskAction.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/TrainAndPredictable.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/clustering/KMeans.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/trainpredict/MLTrainAndPredictionTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLTaskType.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLTrainAndPredictAction.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java

Add train and predict API.
#111 

add train and predict API

---

common/src/main/java/org/opensearch/ml/common/exception/MLException.java
common/src/main/java/org/opensearch/ml/common/exception/MLLimitExceededException.java
common/src/main/java/org/opensearch/ml/common/exception/MLResourceNotFoundException.java
common/src/main/java/org/opensearch/ml/common/exception/MLValidationException.java
common/src/test/java/org/opensearch/ml/common/exception/MLExceptionTest.java
common/src/test/java/org/opensearch/ml/common/exception/MLLimitExceededExceptionTest.java
common/src/test/java/org/opensearch/ml/common/exception/MLResourceNotFoundExceptionTest.java
common/src/test/java/org/opensearch/ml/common/exception/MLValidationExceptionTest.java

add ML custom exceptions

---

common/build.gradle
common/src/main/java/org/opensearch/ml/common/transport/model/MLModelDeleteAction.java
common/src/main/java/org/opensearch/ml/common/transport/model/MLModelDeleteRequest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteModelAction.java

This PR added ML delete model API. 

add ML Delete model API

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
common/build.gradle
common/src/main/java/org/opensearch/ml/common/transport/model/MLModelGetResponse.java
common/src/main/java/org/opensearch/ml/common/transport/model/MLModelSearchAction.java
common/src/test/java/org/opensearch/ml/common/transport/model/MLModelDeleteRequestTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/models/SearchModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLSearchModelAction.java

Add the search model API for ml-common.

Add ML Model Search API

---

common/build.gradle
common/src/main/java/org/opensearch/ml/common/breaker/BreakerName.java
common/src/main/java/org/opensearch/ml/common/breaker/CircuitBreaker.java
common/src/main/java/org/opensearch/ml/common/breaker/MLCircuitBreakerService.java
common/src/main/java/org/opensearch/ml/common/breaker/MemoryCircuitBreaker.java
common/src/main/java/org/opensearch/ml/common/breaker/ThresholdCircuitBreaker.java
common/src/test/java/org/opensearch/ml/common/breaker/MLCircuitBreakerServiceTests.java
common/src/test/java/org/opensearch/ml/common/breaker/MemoryCircuitBreakerTests.java
plugin/src/main/java/org/opensearch/ml/action/trainpredict/TransportTrainAndPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/task/MLExecuteTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java

Add circuit breaker to protect cluster not overloaded by ML tasks.
#141

add circuit breaker

---

common/src/main/java/org/opensearch/ml/common/parameter/BatchRCFParams.java
common/src/main/java/org/opensearch/ml/common/parameter/FitRCFParams.java
common/src/main/java/org/opensearch/ml/common/parameter/FunctionName.java
common/src/test/java/org/opensearch/ml/common/parameter/BatchRCFParamsTest.java
common/src/test/java/org/opensearch/ml/common/parameter/FitRCFParamsTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/BatchRandomCutForest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ModelSerDeSer.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForestTest.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Add batch RCF to detect non-time-series data.

add batch RCF for non-time-series data

---

common/src/main/java/org/opensearch/ml/common/transport/training/MLTrainingTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java

fix system index permission issue in train/predict runner

fix system index permission issue in train/predict runner

---

plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java

cleanup task cache once task done

cleanup task cache once task done

---

plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java

Restore thread context after accessing system index to check user permission on non-system index.
If we don't do this, user can read data from all non-system index if they train model with index data.

restore context after accessing system index to check user permission on non-system index

---

plugin/src/main/java/org/opensearch/ml/action/stats/MLStatsNodesRequest.java
plugin/src/main/java/org/opensearch/ml/action/stats/MLStatsNodesTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestStatsMLAction.java
plugin/src/main/java/org/opensearch/ml/stats/ActionName.java
plugin/src/main/java/org/opensearch/ml/stats/MLStats.java
plugin/src/main/java/org/opensearch/ml/stats/StatNames.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/stats/MLStatsNodeITTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLTrainAndPredictIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestStatsMLActionTests.java
plugin/src/test/java/org/opensearch/ml/stats/MLStatsTests.java
plugin/src/test/java/org/opensearch/ml/stats/StatNamesTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestData.java

add more stats: request/failure/model count on algo/action level
#102

add more stats: request/failure/model count on algo/action level

---

build.gradle
scripts/build.sh

fix maven group

---

ml-algorithms/build.gradle

lower coverage in 1.3 as it excludes anomaly localization

[Backport to 1.3] lower coverage in 1.3 as it excludes anomaly localization

---

ml-algorithms/build.gradle

lower coverage in 1.3 as it excludes anomaly localization

[Backport to 1.x] lower coverage in 1.3 as it excludes anomaly localization

---

.github/workflows/CI-workflow.yml
common/src/test/java/org/opensearch/ml/common/dataframe/DefaultDataFrameTest.java

add java 8 to CI workflow

---

client/build.gradle
client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
common/src/main/java/org/opensearch/ml/common/transport/task/MLTaskGetResponse.java

Add Task related APIs in Client.

add tasks API in Client

---

client/build.gradle
client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java

add more UT to client module

---

common/src/main/java/org/opensearch/ml/common/parameter/MLTask.java
plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Add more UT for task manager/runner

add more UT for task manager/runner

---

common/src/main/java/org/opensearch/ml/common/parameter/MLTask.java
plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Backport to 1.x: add more UT for task manager/runner (#206)

[Backport to 1.x] add more UT for task manager/runner (#206)

---

common/src/main/java/org/opensearch/ml/common/parameter/MLTask.java
plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Backport to 1.3: add more UT for task manager/runner

[Backport to 1.3] add more UT for task manager/runner (#206)

---

.github/draft-release-notes-config.yml
.github/workflows/draft-release-notes-workflow.yml

Add config file and workflow file for release notes. 

create config and workflow files for release note

---

release-notes/opensearch-opensearch-ml.release-notes-1.3.0.0.md

Add ml-common release notes for 1.3.0.0.

Add ml-common release notes for 1.3.0.0

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/utils/MLNodeUtilsTests.java
plugin/src/test/java/org/opensearch/ml/utils/RestActionUtilsTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestData.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

add more UT for plugin util class

add more UT for plugin util class

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/RestMLTrainingActionTests.java

Add sample unit test for RestMLTrainingAction
@Zhangxunmt you can use similar way to add unit test for other rest actions

add sample unit test for RestMLTrainingAction

---

.github/workflows/CI-workflow.yml
plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java

This is a back port to 1.x from main branch.

add more UT for model/task rest actions, remove support for JDK8 (#230)

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/indices/MLInputDatasetHandlerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLTrainAndPredictActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLTrainingActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Improves the tests coverage and remove qualified classes from exclusion list.

improve tests coverage for dataset handler and rest actions

---

.github/workflows/CI-workflow.yml
build.gradle
client/build.gradle
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
common/build.gradle
common/src/main/java/org/opensearch/ml/common/dataset/SearchQueryInputDataset.java
common/src/test/java/org/opensearch/ml/common/parameter/AnomalyLocalizationInputTests.java
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
ml-algorithms/build.gradle
plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/action/stats/MLStatsNodeITTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Updates job scheduler to use OS 2.0, Gradle 7.3, and fix dependency update errors.

update ml-common to use OS 2.0 and gradle 7.3

---

build.gradle

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
More changes to bring ml-commons logic same as other repos
#258

More changes to bring ml-commons logic same as other repos

---

build.gradle

Signed-off-by: Sayali Rohidas Gaikawad <gaiksaya@amazon.com>
Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity.

Incremented version to 1.3.2.

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/GetModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/DeleteTaskTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/GetTaskTransportActionTests.java

Add UT for Search transport action.

add more UT for search transport handler

---

.github/workflows/CI-workflow.yml
README.md

add coverage badges

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImplTests.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Signed-off-by: jackiehanyang <jkhanjob@gmail.com>
https://github.com/opensearch-project/ml-commons/issues/234

Fix NPE in anomaly localization

---

release-notes/opensearch-ml-common.release-notes-2.0.0.0-rc1.md

add 2.0-rc1 release notes

---

build.gradle

Incremented version to 1.3.2

---

release-notes/opensearch-ml-common.release-notes-1.3.2.0.md

Signed-off-by: jackiehanyang <jkhanjob@gmail.com>
Release notes for version 1.3.2

Release notes for version 1.3.2

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/stats/StatNames.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

add circuit breaker trigger count stat

[Backport to 1.3] add circuit breaker trigger count stat (#274)

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/stats/StatNames.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

add circuit breaker trigger count stat

[Backport to 1.x] add circuit breaker trigger count stat (#274)

---

release-notes/opensearch-ml-common.release-notes-2.0.0.0.md

2.0 GA release notes

---

.github/workflows/CI-workflow.yml
build.gradle

Signed-off-by: pgodithi <pgodithi@amazon.com>
https://github.com/opensearch-project/opensearch-build/issues/2101
N/A

Version Increment to 1.3.3 OpenSearch release

---

release-notes/opensearch-ml-common.release-notes-1.3.3.0.md

Add release notes for 1.3.3 version. 

Release notes for version 1.3.3

---

build.gradle
common/src/main/java/org/opensearch/ml/common/FunctionName.java
common/src/main/java/org/opensearch/ml/common/input/execute/bertqa/BertQAInput.java
common/src/main/java/org/opensearch/ml/common/input/execute/od/ObjectDetectionInput.java
common/src/main/java/org/opensearch/ml/common/input/execute/resnet18/Resnet18Input.java
common/src/main/java/org/opensearch/ml/common/output/execute/bertqa/BertQAOutput.java
common/src/main/java/org/opensearch/ml/common/output/execute/od/ObjectDetectionOutput.java
common/src/main/java/org/opensearch/ml/common/output/execute/resnet18/Resnet18Output.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/bertqa/BertQA.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/bertqa/BertTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/od/ObjectDetection.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/resnet18/Resnet18.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/plugin-metadata/plugin-security.policy

Add some test models.
UT/IT will be added later.

add test models

---

release-notes/opensearch-ml-common.release-notes-2.1.0.0.md

Signed-off-by: Jackie Han <jkhanjob@gmail.com>

add 2.1 release notes

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/clustering/KMeans.java

Signed-off-by: Dhrubo Saha <dhrubo@amazon.com>

remove comment which is not applicable now

---

build.gradle

Signed-off-by: Jing Zhang <jngz@amazon.com>
Bump to opensearch 2.2

bump to 2.2

---

release-notes/opensearch-ml-common.release-notes-2.2.0.0.md

ml-common 2.2 release notes.
https://github.com/opensearch-project/ml-commons/issues/374

2.2 release notes

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java

Algorithm docs link added to client interface java doc

Algorithm links added to javadoc

---

build.gradle

bump to version 3.0

---

.github/workflows/CI-workflow.yml
build.gradle

Incremented version to 1.3.5.
Part of: https://github.com/opensearch-project/opensearch-build/issues/2348

[Release 1.3.5] Version increment 

---

build-tools/repositories.gradle

upgrade to lucene snapshot

---

release-notes/opensearch-ml-common.release-notes-2.3.0.0.md

add ml-commons release notes for 2.3

---

README.md

fix readme: remove experimental words

---

README.md
build-tools/repositories.gradle
build.gradle
plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileAction.java
plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileNodeRequest.java
plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileNodeResponse.java
plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileRequest.java
plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileResponse.java
plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/profile/MLProfileInput.java
plugin/src/main/java/org/opensearch/ml/rest/AbstractMLSearchAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLProfileAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLStatsAction.java
plugin/src/main/java/org/opensearch/ml/stats/MLStatsInput.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/utils/MLNodeUtils.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileNodeRequestTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileNodeResponseTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileRequestTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileResponseTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/profile/MLProfileInputTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLProfileActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLStatsActionTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/utils/RestActionUtilsTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java
release-notes/opensearch-ml-common.release-notes-2.3.0.0.md

Backport changes to custom_model branch

Backport changes to custom_model branch

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/model/MLModelConfig.java
common/src/main/java/org/opensearch/ml/common/model/MLModelFormat.java
common/src/main/java/org/opensearch/ml/common/model/MLModelState.java
common/src/main/java/org/opensearch/ml/common/model/MLModelTaskType.java
common/src/main/java/org/opensearch/ml/common/model/TextEmbeddingModelConfig.java
common/src/test/java/org/opensearch/ml/common/MLModelTests.java
common/src/test/java/org/opensearch/ml/common/model/MLModelFormatTests.java
common/src/test/java/org/opensearch/ml/common/model/MLModelStateTests.java
common/src/test/java/org/opensearch/ml/common/model/MLModelTaskTypeTests.java
common/src/test/java/org/opensearch/ml/common/model/TextEmbeddingModelConfigTests.java

Tune ML model to support custom model.

tune ML model to support custom model

---

release-notes/opensearch-ml-common.release-notes-1.3.6.0.md

Add ml-common release notes for 1.3.6.

add release notes for 1.3.6

---

common/src/main/java/org/opensearch/ml/common/transport/model/MLModelGetRequest.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetModelAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelActionTests.java

Do not show model_content by default in model Get API. 
For example: 
GET .../modes/mode_id
{
"name" : "KMEANS",
"algorithm" : "KMEANS",
"version" : 1,
}
GET .../modes/mode_id?return_content=true
{
"name" : "KMEANS",
"algorithm" : "KMEANS",
"version" : 1,
"model_content" : "rO0ABXNyAChvcmcudHJpYnVvLmNsdXN0ZXJpbmcua21lYW5zLktNZWFuc01vZGVsAAAAAAAAAAECAAJbAA9jZW50cm9pZFZlY3RvcnN0ACFbTG9y...
}
POST /_plugins/_ml/models/_search
{
"query": {
"match_all": {}
},
"_source": {"include": [ "model_content" ]},
"size":  20
}
Response: 
{
"took" : 5,
"timed_out" : false,
"_shards" : {
"total" : 1,
"successful" : 1,
"skipped" : 0,
"failed" : 0
},
"hits" : {
"total" : {
"value" : 11,
"relation" : "eq"
},
"max_score" : 1.0,
"hits" : [
{
"_index" : …

do not return model content by default

---

common/src/main/java/org/opensearch/ml/common/transport/model/MLModelGetRequest.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileRequest.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetModelAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelActionTests.java

backport changes to custom model branch

Backport change to custom model branch

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/MLTask.java
common/src/main/java/org/opensearch/ml/common/MLTaskState.java
common/src/main/java/org/opensearch/ml/common/MLTaskType.java
common/src/main/java/org/opensearch/ml/common/dataset/MLInputDataType.java
common/src/main/java/org/opensearch/ml/common/dataset/TextDocsInputDataSet.java
common/src/main/java/org/opensearch/ml/common/exception/MLException.java
common/src/main/java/org/opensearch/ml/common/input/MLInput.java
common/src/main/java/org/opensearch/ml/common/model/MLModelState.java
common/src/main/java/org/opensearch/ml/common/output/MLOutputType.java
common/src/main/java/org/opensearch/ml/common/output/model/MLResultDataType.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelResultFilter.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensor.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensorOutput.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensors.java
common/src/test/java/org/opensearch/ml/common/exception/MLExceptionTest.java
common/src/test/java/org/opensearch/ml/common/input/MLInputTest.java
common/src/test/java/org/opensearch/ml/common/model/MLModelStateTests.java
common/src/test/java/org/opensearch/ml/common/output/model/ModelResultFilterTest.java
common/src/test/java/org/opensearch/ml/common/output/model/ModelTensorOutputTest.java

add input/output for custom model

add input/output for custom model

---

client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java

always dispatch task to ML node

always dispatch task to ML node

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
plugin/src/main/java/org/opensearch/ml/action/trained_model/unload/TransportUnloadModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

change unload model status to unloaded

change unload model status to unloaded

---

common/src/main/java/org/opensearch/ml/common/breaker/BreakerName.java
common/src/main/java/org/opensearch/ml/common/breaker/DiskCircuitBreaker.java
common/src/main/java/org/opensearch/ml/common/breaker/MLCircuitBreakerService.java
plugin/src/main/java/org/opensearch/ml/action/trained_model/upload/MLModelUploader.java
plugin/src/main/java/org/opensearch/ml/action/trained_model/upload/TransportUploadModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/plugin-metadata/plugin-security.policy

Add a new disk breaker and permissions to check disk shortage before uploading, loading, and running a model.

add disk circuit braker

---

plugin/build.gradle

Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
add groupId to pluginzip publication
https://github.com/opensearch-project/ml-commons/issues/412

add groupId to pluginzip publication

---

ml-algorithms/build.gradle
plugin/build.gradle

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
Backport of https://github.com/opensearch-project/ml-commons/pull/487 to `2.x`
Closes https://github.com/opensearch-project/ml-commons/issues/485

[Backport] [2.x] Address CVE-2022-42889 by updating commons-text (#487)

---

common/src/main/java/org/opensearch/ml/common/transport/load/LoadModelResponse.java
common/src/main/java/org/opensearch/ml/common/transport/upload/MLUploadInput.java
common/src/main/java/org/opensearch/ml/common/transport/upload/UploadModelResponse.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/clustering/KMeans.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/FileUtils.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/cluster/MLCommonsClusterManagerEventListener.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/profile/MLModelProfile.java
plugin/src/main/java/org/opensearch/ml/profile/MLPredictRequestStats.java
plugin/src/main/java/org/opensearch/ml/task/MLExecuteTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskCache.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

refactor model cache and thread pool

refactor model cache and thread pool

---

plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelActionTests.java

Signed-off-by: Zan Niu <zaniu@amazon.com>

Add UT for TransportLoadModelAction

---

common/src/main/java/org/opensearch/ml/common/breaker/BreakerName.java
common/src/main/java/org/opensearch/ml/common/breaker/DiskCircuitBreaker.java
common/src/main/java/org/opensearch/ml/common/breaker/MLCircuitBreakerService.java
common/src/test/java/org/opensearch/ml/common/breaker/MLCircuitBreakerServiceTests.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/plugin-metadata/plugin-security.policy
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java

This is a backport of disk circuit breakers and message format change in the earlier PR.

add disk circuit breaker, update deleteModel message format

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java

Add 4GB limit for custom model size. 
Remove redundant access control in taskRunner.

add custom model size limit

---

common/src/main/java/org/opensearch/ml/common/breaker/CircuitBreaker.java
common/src/main/java/org/opensearch/ml/common/breaker/DiskCircuitBreaker.java
common/src/main/java/org/opensearch/ml/common/breaker/MLCircuitBreakerService.java
common/src/main/java/org/opensearch/ml/common/breaker/MemoryCircuitBreaker.java
common/src/test/java/org/opensearch/ml/common/breaker/MLCircuitBreakerServiceTests.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/utils/MLNodeUtils.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

Include the circuit breaker name in the returned exception messages.

return circuit breaker name in error messages

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java

update new small torchscript model

update new small torchscript model for integ test

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModel.java
plugin/src/main/java/org/opensearch/ml/cluster/MLCommonsClusterEventListener.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

support multi-gpu; fix inference duration queue bug

support multi-gpu; fix inference duration queue bug

---

common/src/main/java/org/opensearch/ml/common/transport/forward/MLForwardResponse.java
common/src/main/java/org/opensearch/ml/common/transport/sync/MLSyncUpResponse.java
common/src/test/java/org/opensearch/ml/common/transport/forward/MLForwardInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/forward/MLForwardRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/forward/MLForwardResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelNodeResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelNodesRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelNodesResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/MLLoadModelRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpNodeRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpNodeResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpNodesResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/training/MLTrainingTaskRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelNodeResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelNodesRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelNodesResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadModelRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload/UploadModelResponseTest.java

Add some unit test test coverage to common package
Previously test coverage for common package in our ml-commons app is low

Add test coverage to common package

---

common/src/main/java/org/opensearch/ml/common/transport/upload/MLUploadInput.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelMetaCreate.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLStatsActionTests.java

add description field when upload model; tune log level

add description field when upload model; tune log level

---

plugin/build.gradle

test coverage ratio changes for build.gradlew in plugin package

test coverage ratio changes for build.gradlew in plugin package

---

release-notes/opensearch-ml-common.release-notes-2.4.0.0.md

move custom model related PRs to experimental features

move custom model related PRs to experimental features

---

plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java

When upgrade from older version, will check if need to upgrade model/task index mapping. As model/task index is system index, so we need to stash thread context first, otherwise it throws no permission exception.
Error log
```
OpenSearchSecurityException[no permissions for [] and User [name=admin123, backend_roles=[], requestedTenant=]]
at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:363)
at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:149)
at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:217)
at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:78)
at …
```

[Backport to 2.3] fix no permission bug when update index mapping

---

plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java

[Backport to 2.2] fix no permission bug when update index mapping

---

release-notes/opensearch-ml-common.release-notes-2.4.0.0.md

add bug fix changes to release notes

add bug fix changes to release notes

---

plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelActionTests.java

Signed-off-by: Zan Niu <zaniu@amazon.com>
Signed-off-by: Zan Niu <zaniu@amazon.com>
Co-authored-by: Yaliang Wu <ylwu@amazon.com>
This PR is a partial forwarding of port changes in branch 2.x ([commit #490](https://github.com/opensearch-project/ml-commons/commit/e6a426631a93777553b25664bad0968e68201b6b)) to main branch. …

Forwarding port changes in 2.4 to main branch (Add UT for TransportLoadModelAction)

---

common/src/main/java/org/opensearch/ml/common/breaker/BreakerName.java
common/src/main/java/org/opensearch/ml/common/breaker/DiskCircuitBreaker.java
common/src/main/java/org/opensearch/ml/common/breaker/MLCircuitBreakerService.java
common/src/test/java/org/opensearch/ml/common/breaker/MLCircuitBreakerServiceTests.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/plugin-metadata/plugin-security.policy
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java

* add disk circuit breaker, update deleteModel message format
This PR is a partial forwarding of port changes in branch 2.x ([commit #498](https://github.com/opensearch-project/ml-commons/commit/ca97f26efd2e01ef099cd9e8f90dc398c7b4e069)) to main branch. …

Forwarding port changes in 2.4 to main branch (add disk circuit breaker, update deleteModel message format)

---

common/src/main/java/org/opensearch/ml/common/breaker/CircuitBreaker.java
common/src/main/java/org/opensearch/ml/common/breaker/DiskCircuitBreaker.java
common/src/main/java/org/opensearch/ml/common/breaker/MLCircuitBreakerService.java
common/src/main/java/org/opensearch/ml/common/breaker/MemoryCircuitBreaker.java
common/src/test/java/org/opensearch/ml/common/breaker/MLCircuitBreakerServiceTests.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/utils/MLNodeUtils.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

* return circuit breaker name in error messages
This PR is a partial forwarding of port changes in branch 2.x ([commit #507](https://github.com/opensearch-project/ml-commons/commit/1464a5644a467840d7cb855d1884daa064c808e1)) to main branch. …

Forwarding port changes in 2.4 to main branch (return circuit breaker name in error message)

---

plugin/src/main/java/org/opensearch/ml/action/unload/TransportUnloadModelAction.java

set model state as unloaded when call unload model API

set model state as unloaded when call unload model API

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #508](https://github.com/opensearch-project/ml-commons/commit/b57eb32e774a32bc1d002f144d48b271cbfae58e)) to main branch.

Forwarding port changes in 2.4 to main branch (update small torchscript model for integ test)

---

ml-algorithms/build.gradle
plugin/build.gradle

force protobuf-java version as 3.21.9

---

.github/workflows/CI-workflow.yml

Signed-off-by: Jing Zhang <jngz@amazon.com>
backport windows ci build.
https://github.com/opensearch-project/ml-commons/issues/579

windows ci build

---

build.gradle
plugin/build.gradle

fix junit version

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModel.java
plugin/src/main/java/org/opensearch/ml/cluster/MLCommonsClusterEventListener.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

* support multi-gpu; fix inference duration queue bug
* address comments from Frank
* rename variable
This PR is a partial forwarding of port changes in branch 2.x ([commit #515](https://github.com/opensearch-project/ml-commons/commit/b113885bb92c9195e8a29b184188f0448d583797)) to main branch.
By submitting this pull request, I confirm that my contribution is made under the terms of the …

Forwarding port changes in 2.4 to main branch (support multi-gpu; fix inference duration queue bug)

---

common/src/main/java/org/opensearch/ml/common/transport/forward/MLForwardAction.java
common/src/main/java/org/opensearch/ml/common/transport/sync/MLSyncUpAction.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/FileUtils.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/unload/TransportUnloadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/upload/TransportUploadModelAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #518](https://github.com/opensearch-project/ml-commons/commit/ed94afd31ffdcc3256100bd5adfb68f1cd56f57e)) to main branch.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/mai …

Forwarding port changes in 2.4 to main branch (add trusted URL regex)

---

common/src/main/java/org/opensearch/ml/common/transport/upload/MLUploadInput.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelMetaCreate.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCustomModelChunkActionIT.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #531](https://github.com/opensearch-project/ml-commons/commit/45f40adecfe85c57ac31462104d345dd9033fba9)) to main branch.

Forwarding port changes in 2.4 to main branch (add description field when upload model; tune log level)

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

* fix running tasks when circuit breaker is open
* fix log error message
This PR is a partial forwarding of port changes in branch 2.x ([commit #542](https://github.com/opensearch-project/ml-commons/commit/34bb2abe12e9af9bbfc66f392b457d8b9732df60)) to main branch.
For more information on following Developer Certificate …

Forwarding port changes in 2.4 to main branch (fix running tasks when circuit breaker is open)

---

plugin/src/main/java/org/opensearch/ml/action/unload/TransportUnloadModelAction.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #580](https://github.com/opensearch-project/ml-commons/commit/32f0e6b884ed8cc38f93f3bdaa2867dc50c71b93)) to main branch.

Forwarding port changes in 2.4 to main branch (set model state as unloaded when call unload model API)

---

ml-algorithms/build.gradle
plugin/build.gradle

This PR is a partial forwarding of port changes in branch 2.x ([commit #588](https://github.com/opensearch-project/ml-commons/commit/52cc55f61148f4ddff65a5b9250c3e0059a69106)) to main branch.

Forwarding port changes in 2.4 to main branch (force protobuf-java version as 3.21.9)

---

.whitesource

Welcome to [Mend for GitHub.com](https://github.com/apps/mend-for-github-com) (formerly WhiteSource). This is an onboarding PR to help you understand and configure settings before Mend starts scanning your repository for security vulnerabilities.
:vertical_traffic_light: Mend for GitHub.com will start scanning your repository only once you merge this Pull Request. To disable Mend for GitHub.com, simply close this Pull Request. 
---
This PR contains a '.whitesource' configuration file which can be customized to your needs. If no changes were applied to this file, Mend for GitHub.com will use the default configuration.
Before merging this PR, Make sure the [Issues tab is enabled](https://docs.mend.io/bundle/community_tools/page/enabling_ …

Add .whitesource configuration file

---

release-notes/opensearch-ml-common.release-notes-2.4.1.0.md

add release notes for 2.4.1

---

release-notes/opensearch-ml-common.release-notes-1.3.7.0.md

add release notes for 1.3.7

---

release-notes/opensearch-ml-common.release-notes-2.4.1.0.md

release notes 2.4.1 changes

---

client/build.gradle
common/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle

Update dependency junit:junit to v4.13.1

backport:Update dependency junit:junit to v4.13.1

---

plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java

When add or remove task from cache, we should make sure the running task count increment/decrement correctly.

fix running task count bug

---

ml-algorithms/build.gradle
plugin/build.gradle

bump djl to 0.20 and add onnxruntime-gpu dependency

bump djl to 0.20 and add onnxruntime-gpu dependency

---

common/src/main/java/org/opensearch/ml/common/model/MLModelState.java
common/src/main/java/org/opensearch/ml/common/transport/upload/MLUploadInput.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadInputTest.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/action/upload/TransportUploadModelAction.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/utils/MLExceptionUtilsTests.java

We will build some model and publish to our model repo. Will provide model list to user. User can upload model easily with just model name and version, for example
```
POST /_plugins/_ml/models/_upload
{
"name": "huggingface/sentence-transformers/msmarco-distilbert-base-tas-b",
"version": "1.0.0"
}
```

support uploading prebuilt model

---

MAINTAINERS.md

Updating maintainers list

---

MAINTAINERS.md

(cherry picked from commit ed94380c6c2238d425a1be2afbbde8b88b1dcca4)
Updated MAINTAINERS.md format

Updated MAINTAINERS.md format (#668)

---

MAINTAINERS.md

(cherry picked from commit a08e4825db916c7138a28f3dd259732d6ba8decd)
Updating maintainers list

Updating maintainers list (#663)

---

docs/model_serving_framework/GPU_support.md

add doc about how to setup GPU ML node

add doc about how to setup GPU ML node

---

release-notes/opensearch-ml-common.release-notes-2.5.0.0.md

Adding ml-commons plugin v2.5.0 release note.

Adding ml-commons plugin v2.5.0 release note

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/bwc/MLCommonsBackwardsCompatibilityIT.java

This is a manually backport for PR #705 

[Backport 2.5] fix bwc bug when incrementing to OS 2.6.0 (#705)

---

docs/model_serving_framework/text_embedding_model_examples.md

change model url to public repo in text embedding model example doc

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
docs/model_serving_framework/text_embedding_model_examples.md
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Refactor code to make it more extensible.

refactor: add DL model class

---

ml-algorithms/src/test/resources/org/opensearch/ml/engine/algorithms/text_embedding/pre_trained_models_list.json

[json listing of all the pretrianed models]

json listing of all the pretrianed models

---

release-notes/opensearch-ml-common.release-notes-2.6.0.0.md

Release note for ml-common 2.6.
[[List any issues this PR will resolve](https://github.com/opensearch-project/ml-commons/issues/733)]

add release note for 2.6

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java

code fix for delete model API 

fix delete model API

---

release-notes/opensearch-ml-common.release-notes-2.6.0.0.md

Update the 2.6 release notes to reflect experimental features and latest bug fixes.

update 2.6 release note

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/FileUtils.java

[Backport to 2.x] change to old method to fix missing method createParentDirectories

---

plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java

Backport PR #641  to main branch

[Backport to main] fix running task count bug (#641)

---

ml-algorithms/build.gradle
plugin/build.gradle

Backport PR #644 #652  to main branch

[Backport to main] bump djl to 0.20 and add onnxruntime-gpu dependency & Remove jackson-databind

---

common/src/main/java/org/opensearch/ml/common/model/MLModelState.java
common/src/main/java/org/opensearch/ml/common/transport/upload/MLUploadInput.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadInputTest.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/action/upload/TransportUploadModelAction.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/utils/MLExceptionUtilsTests.java

[Backport to main] support uploading prebuilt model (#655)

---

common/src/main/java/org/opensearch/ml/common/MLTask.java
common/src/test/java/org/opensearch/ml/common/MLTaskTests.java
common/src/test/java/org/opensearch/ml/common/transport/forward/MLForwardInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/forward/MLForwardRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelNodesRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/task/MLTaskGetResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/upload/TransportUploadModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/profile/MLModelProfile.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileNodeResponseTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileResponseTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLProfileActionTests.java

Backport PR #656 to main branch

[Backport to main] change task worker node to list; add target worker node to cache (#656)

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/model/TextEmbeddingModelConfig.java
common/src/test/java/org/opensearch/ml/common/model/TextEmbeddingModelConfigTests.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaRequestTest.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/HuggingfaceTextEmbeddingTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/HuggingfaceTextEmbeddingTranslatorFactory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/ONNXSentenceTransformerTextEmbeddingTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelMetaCreateTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportCreateModelMetaActionTests.java

Backport PR #672 to main branch

[Backport to main] add more pooling method and refactor (#672)

---

docs/model_serving_framework/GPU_support.md

Backport PR #677 to main branch

[Backport to main] add doc about how to setup GPU ML node (#677)

---

common/src/main/java/org/opensearch/ml/common/transport/upload/MLUploadInput.java
ml-algorithms/build.gradle
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/main/java/org/opensearch/ml/action/upload/TransportUploadModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Backport PR #682 to main branch

[Backport to main] disable prebuilt model (#682)

---

plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java

Backport PR #686 to main branch

[Backport to main]change only run on ml node setting default value to true (#686)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ModelSerDeSer.java

fix class not found exception when deserialize model

fix class not found exception when deserialize model

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/FileUtils.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
release-notes/opensearch-ml-common.release-notes-2.6.0.0.md

Backport multiple changes to main branch
#739 
#748 
#750 
#759 

[Backport to main] backport multiple changes to main branch

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionActionTests.java

Backport PR #790 to main branch

[Backport to main] change exception type; get function name from cache (#790)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

User may put wrong model file in model zip.
This PR checks if there is any wrong model file in model zip. For example, user input "ONNX" model format, but the model zip contains ".pt" file. Then we will throw exception and mark the upload file task as failed.

check model format when upload model

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

[Backport to main] check model format when upload model (#795)

---

common/build.gradle

Backport PR #796 to main branch

[Backport to main] exclude commons-io and reflections class from ml-commons client jar (#796)

---

docs/docker/docker-compose.yml

[Backport to 2.x] add docker-compose file for starting cluster with dedicated ML node (#799)

---

common/src/main/java/org/opensearch/ml/common/transport/unload/UnloadModelNodeResponse.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelNodeResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelNodesResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/unload/TransportUnloadModelAction.java
plugin/src/test/java/org/opensearch/ml/action/unload/TransportUnloadModelActionTests.java

[Backport main]set model state as partially loaded if unload model from partial nodes (#806)

---

plugin/src/main/java/org/opensearch/ml/action/unload/TransportUnloadModelAction.java
plugin/src/main/java/org/opensearch/ml/cluster/DiscoveryNodeHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/test/java/org/opensearch/ml/cluster/DiscoveryNodeHelperTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLTrainAndPredictIT.java

Backport PR #813 to main branch

[Backport to main] add exclude nodes setting (#813)

---

common/src/main/java/org/opensearch/ml/common/MLCommonsClassLoader.java
common/src/main/java/org/opensearch/ml/common/annotation/MLInput.java
common/src/main/java/org/opensearch/ml/common/input/MLInput.java
common/src/main/java/org/opensearch/ml/common/input/nlp/TextDocsMLInput.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelResultFilter.java
common/src/test/java/org/opensearch/ml/common/MLCommonsClassLoaderTests.java
common/src/test/java/org/opensearch/ml/common/input/nlp/TextDocsMLInputTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModel.java

Backport PR #830 to main branch

[Backport to main]add text docs ML input (#830)

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLExecuteTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/models/GetModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/task/MLExecuteTaskRunnerTests.java

[change the settings name and fixed a bug in delete model]

change the settings name and fixed a bug in delete model

---

release-notes/opensearch-ml-common.release-notes-2.7.0.0.md

release note for 2.7.0

---

plugin/src/main/java/org/opensearch/ml/profile/MLModelProfile.java

change mem_size_estimation to memory_size_estimation

change mem_size_estimation to memory_size_estimation

---

MAINTAINERS.md

The link to @zane-neo is borked, missing a `)`.
Best viewed as https://github.com/opensearch-project/ml-commons/pull/890/files?w=1.

Fix: MAINTAINERS.md format.

---

.github/workflows/CI-workflow.yml
build.gradle

Increment version to 1.3.10-SNAPSHOT

Increment version to 1.3.10-SNAPSHOT

---

common/src/main/java/org/opensearch/ml/common/transport/undeploy/MLUndeployModelsAction.java
common/src/main/java/org/opensearch/ml/common/transport/undeploy/MLUndeployModelsResponse.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java

fix undeploy model API

---

plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java

Fix some bugs for model access control

---

common/src/main/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupInput.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploader.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploaderTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaActionTests.java

add access control to register version via local file and minor fixes

add access control to register version via local file and minor fixes

---

common/src/main/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupInput.java

Change model_access_control to optional when register model

---

common/src/main/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupResponse.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/model_group/SearchModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/SearchModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java
plugin/src/test/java/org/opensearch/ml/action/model_group/RegisterModelGroupITTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/SearchModelGroupITTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/UpdateModelGroupITTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelITTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java

Add ITs and UTs and refactor model group search code and fixed minor bugs

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelation.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelationTest.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploader.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

fix metric correlation

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ModelSerDeSer.java

This is a bp for PR https://github.com/opensearch-project/ml-commons/pull/781

[Backport 2.x] fix class not found exception when deserialize model

---

plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java
plugin/src/test/java/org/opensearch/ml/action/model_group/SearchModelGroupITTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelITTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java

Fix model search IT bugs

---

common/src/main/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupResponse.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLUpdateModelGroupRequest.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLUpdateModelGroupResponse.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLModelGroupDeleteRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLUpdateModelGroupInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLUpdateModelGroupRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLUpdateModelGroupResponseTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/SearchModelGroupTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/GetModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploaderTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaActionTests.java
plugin/src/test/java/org/opensearch/ml/helper/ModelAccessControlHelperTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelGroupActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRegisterModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUndeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateModelGroupActionTests.java

Unit tests for model access control new classes

Unit tests for model access control new classes

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLModelGroup.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCustomModelActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

Add Search Model Group Rest Action unit tests and minor fixes

Add Search Model Group Rest Action unit tests and minor fixes

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

Fix model group index not existing model version query issue and SecureMLRestIT failure ITs

---

common/src/main/java/org/opensearch/ml/common/MLModelGroup.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelActionTests.java

set default access_control_enabled setting to false

set default access_control_enabled setting to false

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

[Backport 2.8] Fix model group index not existing model version query issue and SecureMLRestIT failure ITs

---

common/src/main/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupInput.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLUpdateModelGroupInput.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

fix model access mode upper case bug

---

plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

enable model access control in secure reset IT

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/MLModelGroupRestIT.java

Add model group rest ITs

---

release-notes/opensearch-ml-common.release-notes-2.8.0.0.md

2.8 release notes

---

plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java

fix no permission to update model group index

---

plugin/src/test/java/org/opensearch/ml/rest/MLModelGroupRestIT.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

fix security IT failure caused by weak password

---

plugin/src/main/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploader.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaAction.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploaderTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLModelGroupRestIT.java

fix minor bugs and reformat error messsages

fix minor bugs and reformat error messsages

---

common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/connector/template/APISchema.java
common/src/main/java/org/opensearch/ml/common/connector/template/DetachedConnector.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorSearchAction.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ChatConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
plugin/src/main/java/org/opensearch/ml/action/remote/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Some refactor to connectors to support predict API.

refactor connectors to support predict API

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java

fix connector mapping issues temporary

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java

fix connector mapping typos

---

common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/template/DetachedConnector.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java

some enhancement to abstract connector and detached connector.

enhance abstract and detached connectors

---

common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/template/DetachedConnector.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java

fix parsing url endpoint

---

build.gradle

Increment version to 2.5.1-SNAPSHOT

Increment version to 2.5.1-SNAPSHOT

---

build.gradle

Increment version to 2.7.1-SNAPSHOT

Increment version to 2.7.1-SNAPSHOT

---

plugin/src/main/java/org/opensearch/ml/action/remote/TransportCreateConnectorAction.java
plugin/src/test/java/org/opensearch/ml/action/remote/TransportCreateConnectorActionTests.java

fix null value error for API schema

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
plugin/src/main/java/org/opensearch/ml/action/remote/TransportCreateConnectorAction.java

Move connector metadata to top level

move connector metadata to top level

---

common/src/main/java/org/opensearch/ml/common/connector/template/APISchema.java
common/src/main/java/org/opensearch/ml/common/connector/template/ConnectorTemplate.java
common/src/main/java/org/opensearch/ml/common/connector/template/DetachedConnector.java

fix the pre and post processing functions.

include pre and post processing functions in detached connectors

---

common/src/main/java/org/opensearch/ml/common/connector/template/DetachedConnector.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
plugin/src/main/java/org/opensearch/ml/action/remote/TransportCreateConnectorAction.java

Fix connector access control disabled creation issue

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
plugin/src/main/java/org/opensearch/ml/action/remote/TransportCreateConnectorAction.java
plugin/src/test/java/org/opensearch/ml/action/remote/TransportCreateConnectorActionTests.java

Fix invalid json admin create connector issues

---

ml-algorithms/build.gradle
plugin/build.gradle

This is a manual backport for #1005

Manual CVE backport

---

plugin/build.gradle

This PR should fix CVE mentioned in #1000 and #1002

Manual CVE fix

---

common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/connector/template/DetachedConnector.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java

Fix invalid json issue and remove all escapeJson invocation

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java

Fix invalid json issue with escapeJava approach

---

common/src/main/java/org/opensearch/ml/common/connector/template/DetachedConnector.java
plugin/src/main/java/org/opensearch/ml/breaker/MLCircuitBreakerService.java
plugin/src/main/java/org/opensearch/ml/breaker/MemoryCircuitBreaker.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java

disable native memory breaker and add settings for heap memory breaker

---

common/src/main/java/org/opensearch/ml/common/connector/template/Connector.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelResponse.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

Re-include model_id in the Model Register API.

include model id in the register model API response

---

release-notes/opensearch-ml-common.release-notes-1.3.11.0.md

Adding the release note for OS 1.3.11

Add release note for 1.3.11

---

common/build.gradle
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactory.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/action/remote/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/remote/TransportCreateConnectorActionTests.java

Fix appsec review issues and add torchscript runtime optimization

---

ml-algorithms/build.gradle
plugin/build.gradle

Change google guava version to 32.0.1-jre

---

plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java
plugin/src/test/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployerTests.java

Fix map incompatibility issue

---

plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Exclude remote model in checking the Max Model Limit per node.

do not count remote model in checking the max models per node

---

plugin/src/main/java/org/opensearch/ml/action/remote/GetConnectorTransportAction.java

Update the exception code to 400 for incorrect connector ID. 

return 400 code when connector id is incorrect in GetConnector API

---

build.gradle
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImplTests.java
plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployerTests.java
plugin/src/test/java/org/opensearch/ml/cluster/DiscoveryNodeHelperTests.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskDispatcherTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

rollback to opensearch 2.8 to unblock the latest code  deployment

---

plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java

Remove credential information in model search API

---

common/src/main/java/org/opensearch/ml/common/connector/template/DetachedConnector.java
plugin/src/main/java/org/opensearch/ml/action/remote/GetConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/remote/SearchConnectorTransportAction.java

Remove connector get or search credential information in result

---

plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java

Change connector access control default value to false

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/Encryptor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
plugin/src/main/java/org/opensearch/ml/action/remote/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/remote/TransportCreateConnectorActionTests.java

allow daynamically updating the encryption key. tests pass. 

refactor encryptImpl

---

plugin/src/main/java/org/opensearch/ml/action/remote/DeleteConnectorTransportAction.java

Fix the bug of "search action for .plugins-ml-model is not allowed for a non adminDN user" by adding the thread context.

add thread context in searching models for connectors

---

plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java

Change default sagemaker connector endpoint regex

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/test/java/org/opensearch/ml/common/connector/ConnectorActionTest.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactory.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactoryTests.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

remote inference: add connector executor

---

common/src/main/java/org/opensearch/ml/common/connector/AwsConnector.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/action/remote/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/remote/GetConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/remote/SearchConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/breaker/MemoryCircuitBreaker.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/remote/SearchConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/remote/TransportCreateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployerTests.java
plugin/src/test/java/org/opensearch/ml/cluster/DiscoveryNodeHelperTests.java
plugin/src/test/java/org/opensearch/ml/helper/ConnectorAccessControlHelperTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskDispatcherTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Add search connector uts

---

common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/AwsConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/connector/ConnectorProtocols.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/test/java/org/opensearch/ml/common/connector/AwsConnectorTest.java
common/src/test/java/org/opensearch/ml/common/connector/ConnectorActionTest.java
common/src/test/java/org/opensearch/ml/common/connector/ConnectorProtocolsTest.java
common/src/test/java/org/opensearch/ml/common/connector/ConnectorTest.java
common/src/test/java/org/opensearch/ml/common/connector/HttpConnectorTest.java
common/src/test/java/org/opensearch/ml/common/connector/MLPostProcessFunctionTest.java
common/src/test/java/org/opensearch/ml/common/connector/MLPreProcessFunctionTest.java
common/src/test/java/org/opensearch/ml/common/input/nlp/TextDocsMLInputTest.java
common/src/test/java/org/opensearch/ml/common/model/TextEmbeddingModelConfigTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java
plugin/src/test/java/org/opensearch/ml/action/model_group/SearchModelGroupITTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/UpdateModelGroupITTests.java

add unit test for connector class in commons

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteConnectorAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetConnectorAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLSearchConnectorAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/connector/GetConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Restful Actions for connectors and UT.

restful connector actions and UT

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/breaker/MLCircuitBreakerService.java
plugin/src/test/java/org/opensearch/ml/breaker/MLCircuitBreakerServiceTests.java

add the missing part in the circuit breaker service and remove it from jacoco list.

fix memory circuit breaker

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Increase sleep time on remote inference integration tests

---

plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLModelGroupRestIT.java

fix encoding US-ASCII error

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

fix remote inference it: update job interval

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Removes @Ignore from OpenAI tests

Reenable OpenAI Remote Inference Tests

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java

If user input unescaped string, remote inference will throw error. This PR enhance process input function to escape parameters if not valid json.
#1159

remote inference: escape parameter if not valid json

---

plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java

[Backport to 2.x] fix:admin with no backend role on AOS unable to create restricted model group (#1188)

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

* fixing metrics
* addressing comments
* addressing comments
* updating test
* added IllegalArgumentException in the if statement
* addressing comments
* fixing spotless
---------

[Backport to 2.x] fixing metrics (#1194)

---

plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/execute/TransportExecuteTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/action/training/TransportTrainingTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/trainpredict/TransportTrainAndPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelAction.java
plugin/src/main/java/org/opensearch/ml/cluster/DiscoveryNodeHelper.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/cluster/DiscoveryNodeHelperTests.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskDispatcherTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

* add eligible node role settings
* add more comment
---------

[Backport to 2.x] add eligible node role settings (#1197)

---

common/src/main/java/org/opensearch/ml/common/MLCommonsClassLoader.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
plugin/src/main/java/org/opensearch/ml/action/connector/GetConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCreateConnectorAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateConnectorActionTests.java

[Backport to 2.x] fixing some error message handeling

---

plugin/build.gradle

This is a backport PR for #1216

[Backport main] Bump checkstyle version for CVE fix 

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLExecuteTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/models/GetModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/task/MLExecuteTaskRunnerTests.java

Backport PR #861 to main branch.

[Backport to main] change the settings name and fixed a bug in delete model (#861)

---

release-notes/opensearch-ml-common.release-notes-2.7.0.0.md

Backport https://github.com/opensearch-project/ml-commons/pull/865 to main

[Backport to main]release note for 2.7.0 (#865)

---

plugin/src/main/java/org/opensearch/ml/profile/MLModelProfile.java

Backport https://github.com/opensearch-project/ml-commons/pull/868 to main

[Backport to main]Change mem_size_estimation to memory_size_estimation. (#868)

---

common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

Backport https://github.com/opensearch-project/ml-commons/pull/878 to main

[Backport to main]check hash value (#878)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java

Backport https://github.com/opensearch-project/ml-commons/pull/884 to main

[Backport to main]fix null hash value (#884)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

* add pre-trained model list
* address comments
---------
Backport https://github.com/opensearch-project/ml-commons/pull/883 to main

[Backport to main]add pre-trained model list (#883)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelation.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelationTest.java

* adding model content hash value
* addressed comment
---------
Backport https://github.com/opensearch-project/ml-commons/pull/885 to main

[Backport to main]adding model content hash value (#885)

---

client/build.gradle

Backport https://github.com/opensearch-project/ml-commons/pull/919 to main 

[Backport to main]fix publish shadow publication dependency issue (#919)

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

Backport https://github.com/opensearch-project/ml-commons/pull/933 to main

[Backport to main] Fix model group index not existing model version query issue and SecureMLRestIT failure ITs

---

common/src/main/java/org/opensearch/ml/common/MLModelGroup.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelActionTests.java

* set default access_control_enabled setting to false
Backport https://github.com/opensearch-project/ml-commons/pull/935 to main

[Backport to main]set default access_control_enabled setting to false (#935)

---

common/src/main/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupInput.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLUpdateModelGroupInput.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

* fix upper case bug
* create shared public model group in SecureMLRestIT
---------
Backport https://github.com/opensearch-project/ml-commons/pull/937 to main

[Backport to main]fix model access mode upper case bug (#937)

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/MLModelGroupRestIT.java

* Add model group rest ITs
* Fix failure ITs
* Fix failure ITs
* Fix failure ITs
---------
Backport https://github.com/opensearch-project/ml-commons/pull/942 to main

[Backport to main]Add model group rest ITs (#942)

---

release-notes/opensearch-ml-common.release-notes-2.8.0.0.md

Backport https://github.com/opensearch-project/ml-commons/pull/946 to main

[Backport to main]2.8 release notes (#946)

---

plugin/build.gradle

This is a backport PR for #1216 

[Backport 1.3] Bump checkstyle version for CVE fix

---

plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java

Backport https://github.com/opensearch-project/ml-commons/pull/948  to main

[Backport to main]fix no permission to update model group index (#948)

---

plugin/src/main/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploader.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaAction.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploaderTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLModelGroupRestIT.java

* fix minor bugs and reformat error messsages
Backport https://github.com/opensearch-project/ml-commons/pull/953 to main

[Backport to main]fix minor bugs and reformat error messsages (#953)

---

docs/model_access_control.md

* model access control documentation
Backport https://github.com/opensearch-project/ml-commons/pull/966 to main

[Backport to main]model access control documentation (#966)

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImplTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/cluster/DiscoveryNodeHelperTests.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskDispatcherTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

* Fix build.
* Remove unused import.
---------
Backport https://github.com/opensearch-project/ml-commons/pull/1018 to main

[Backport to main]Fix build. (#1018)

---

TRIAGING.md

add triaging doc

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/plugin/MachineLearningPluginTests.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAProcessorConstants.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQARequestProcessor.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAResponseProcessor.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQARequestProcessorTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAResponseProcessorTests.java

Allow RAG pipeline feature flag to be enabled and disabled dynamically.
#1150 
- [ x] New functionality includes testing.
- [ x] All tests pass
- [ x] Commits are signed per the DCO using --signoff 

Allow RAG pipeline feature flag to be enabled and disabled dynamically

---

release-notes/opensearch-ml-common.release-notes-2.10.0.0.md

This PR adds release note for 2.10.0 release

Add release note for 2.10.0 release

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java

* Fix unassigned ml system shard replicas
* Adjust auto replica settings to keep it consistent with AOS default setting
* Update plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
* Modify exception handling
* Modify exception messages
* Add response check
* Add response check and exception handling
* Keep error message consistent
* Keep error message consistent
* Keep error message consistent
---------
This is a backport PR for #1315 

[Backport main] Fix unassigned ml system shard replicas (#1315)

---

plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java

This is a patch commit for PR #1315 

Adjust index replicas settings to keep consistent with AOS 2.9

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/SentenceTransformerTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/TextEmbeddingModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/SentenceTransformerTextEmbeddingTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingDenseModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/sparse_encoding/TextEmbeddingSparseEncodingModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/tokenize/SparseTokenizerModelTest.java

fix license problem

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelation.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/SearchModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

[Backport to 2.x] restore thread context before running action listener (#1418)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java

The fix in last PR https://github.com/opensearch-project/ml-commons/pull/1407 will break BWC. This PR fixed that break.

support bwc for process function

---

DEVELOPER_GUIDE.md

Updated developer guide to include useful links for getting started with git
Resolves #1400

Updated developer guide to include links for getting started with git

---

plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupActionTests.java

throw exception when model group not found during update request

throw exception when model group not found during update request

---

common/src/main/java/org/opensearch/ml/common/output/model/ModelTensors.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java

* add status code to model tensor
* fix ut
---------

[Backport to 2.11] add status code to model tensor (#1443)

---

common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/model/MetricsCorrelationModelConfig.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/test/java/org/opensearch/ml/common/model/MetricsCorrelationModelConfigTests.java
common/src/test/java/org/opensearch/ml/common/transport/register/MLRegisterModelInputTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModelExecute.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelation.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelationTest.java

[fixing metrics correlation algorithm]

fixing metrics correlation algorithm

---

plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java

add bedrockURL to trusted connector regex list

add bedrockURL to trusted connector regex list

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java

fix failed ut from PR 1472

---

plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java

fix no worker node error on multi-node cluster

---

release-notes/opensearch-ml-common.release-notes-2.11.0.0.md

adding another fix issue to the release note

---

.gitignore
docs/remote_inference_blueprints/cohere_connector_embedding_blueprint.md

1. Fixes Cohere prompt template from $parameters.texts to $parameters.prompt
2. Adds in the pre/post steps needed for Cohere pipeline. 
Resolves #1344
- [N/A] New functionality includes testing.
- [N/A] All tests pass
- [N/A] New functionality has been documented.
- [N/A] New functionality has javadoc added

Fixes bugs in the Cohere Blueprint

---

common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/tools/GetToolTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tools/ListToolsTransportAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLListToolsAction.java
search-processors/build.gradle

1. remove hardcode version in dependencies
2. add missing license header

Remove hardcode version

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/AgentTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/CatIndexTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MLModelTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MathTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/PainlessScriptTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/VectorDBTool.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetToolAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLListToolsAction.java
spi/src/main/java/org/opensearch/ml/common/spi/tools/Tool.java

fix list/get tool api

---

release-notes/opensearch-ml-common.release-notes-2.11.1.0.md

updating release note

---

docs/remote_inference_blueprints/bedrock_connector_anthropic_claude_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_titan_embedding_blueprint.md
docs/remote_inference_blueprints/openai_connector_embedding_blueprint.md

add openai embedding model blueprint
fine tune doc format

add openai embedding model blueprint

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/MLMemoryManager.java

add the function to update interaction based on interaction id, inside the memory manager class. 

add update Interaction in the memory manager

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLRegisterModelMetaInput.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLRegisterModelMetaInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLRegisterModelMetaRequestTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/GetModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/UpdateModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRegisterModelActionTests.java

[Creating hidden model functionalities
Tested all the functionalities. 
Test is not covered yet. Will address test after unblocking others.
]

hidden_model

---

client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java

Manual backport of https://github.com/opensearch-project/ml-commons/pull/1616

[Backport feature/agent_framework_dev] Fixing class casting exception for MachineLearningNodeClient GetMLTask API

---

common/src/main/java/org/opensearch/ml/common/agent/MLAgent.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/ConversationIndexMemory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/ConversationIndexMessage.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/AgentTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/CatIndexTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MLModelTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MathTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/PainlessScriptTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/VectorDBTool.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
spi/src/main/java/org/opensearch/ml/common/spi/tools/Tool.java

chat agent execution

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java

bug fixes - conversational agent execution

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Changed rate limiter token capacity setting to make it more flexible.

Change rate limiter token capacity setting

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/MLMemoryManager.java

check the additional info and make sure it's not null to be ingested in OS for a flat object. remove the wrong access check for interaction access using meta index check.

additional info cannot be null and update getTraces

---

common/build.gradle
plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/action/models/UpdateModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryCreateInteractionActionTests.java

This PR should unblock the build pipeline

Ignore some failed tests to unblock build pipeline

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/ConversationIndexMemory.java

fix additional info issue when creating conversation

---

plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java

Fix the update model api issue due to restoring context too early.

Fix only superadmin can use update model api bug

---

common/src/main/java/org/opensearch/ml/common/transport/model/MLModelGetRequest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelation.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetModelAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/action/models/GetModelTransportActionTests.java

fixing predict request block during transport communication

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/VisualizationsTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/VisualizationToolTests.java
ml-algorithms/src/test/resources/org/opensearch/ml/engine/tools/visualization.json
ml-algorithms/src/test/resources/org/opensearch/ml/engine/tools/visualization_not_found.json
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Add Visualization tool to support find visualizations by its title, and return first 3 result.

Add Visualization tool

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java

fix null user in conversation

---

build.gradle

rollback to 2.11.0

---

client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java

Fixed ActionListener for Register Agent

Fixed ActionListener for Register Agent

---

release-notes/opensearch-ml-common.release-notes-2.11.1.0.md

release notes for 2.11

---

common/src/main/java/org/opensearch/ml/common/output/model/ModelTensors.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunner.java

Add support to parse Agent tool output in Flow agent

Add support to parse Agent tool output in Flow agent

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/IndexMappingTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/IndexMappingToolTests.java

Add final trace interaction with the final answer, and some spotless changes.

add final trace with final answer

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/IndexMappingTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/IndexMappingToolTests.java

fix checkstyle of index mapping tool

fix checkstyle of index mapping tool

---

common/src/main/java/org/opensearch/ml/common/conversation/ConversationalIndexConstants.java

[1693](https://github.com/opensearch-project/ml-commons/pull/1678)

rename the conversation and interaction indices to memory meta

---

memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/MLMemoryManager.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryGetInteractionsActionIT.java

Update the default sort from DESC to ASC in listing interactions and traces, based on the requests from FE.

update sorting from desc to asc for list interactions and traces

---

common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentDeleteAction.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentDeleteRequest.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentGetAction.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentGetRequest.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentGetResponse.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/agents/DeleteAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/GetAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteAgentAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetAgentAction.java

Get and Delete Agent APIs

---

docs/remote_inference_blueprints/cohere_v2_connector_embedding_blueprint.md
docs/remote_inference_blueprints/cohere_v3_connector_embedding_blueprint.md

Per request from Cohere, add the cohere v3.0 embedding model blueprint. The previous blueprint is renamed to v2.0. 

Add cohere version 3 embedding model

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Read more details https://github.com/opensearch-project/ml-commons/issues/1666
Resolve https://github.com/opensearch-project/ml-commons/issues/1666

support charset input params and change default charset as utf8

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunner.java

ModelTensorOutput from a tool in flow agent results in following exception
```
com.google.gson.JsonIOException: Failed making field 'java.nio.ByteBuffer#hb' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
```
Added custom parsing logic to support ModelTensorOutput. Changes were tested locally on OpenSearch instance.
Sample ModelTensorOutput stored in memory
```
{
"interactions": [
{
"conversation_id": "zzLhWowBClkb1IYEPGvG",
"interaction_id": "0DLhWowBClkb1IYEPGvc",
"create_time": "2023-12-11T21:55:59.824689655Z",
"input": "What are the id's of visualizations with title 'test'",
"prompt_template": null,
"response": "Based on the information you previously requested, the IDs of the visualizations titled 'test' are …
```

Handle ModelTensorOutput type while parsing response

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MLModelTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/MLModelToolTests.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java

adding unit tests

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/agent/LLMSpec.java
common/src/main/java/org/opensearch/ml/common/agent/MLAgent.java
common/src/main/java/org/opensearch/ml/common/agent/MLMemorySpec.java
common/src/main/java/org/opensearch/ml/common/agent/MLToolSpec.java
common/src/test/java/org/opensearch/ml/common/agent/LLMSpecTest.java
common/src/test/java/org/opensearch/ml/common/agent/MLAgentTest.java
common/src/test/java/org/opensearch/ml/common/agent/MLMemorySpecTest.java
common/src/test/java/org/opensearch/ml/common/agent/MLToolSpecTest.java

agent meta classes in common

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/AgentTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/AgentToolTests.java

adding tests for agentTool

---

common/src/main/java/org/opensearch/ml/common/conversation/ActionConstants.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetTracesAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetTracesRequest.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetTracesResponse.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetTracesTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateConversationAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateConversationRequest.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionRequest.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionTransportAction.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetTracesRequestTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetTracesResponseTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetTracesTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/UpdateConversationRequestTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/UpdateConversationTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionRequestTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionTransportActionTests.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/MLMemoryManager.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/memory/MLMemoryManagerTests.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMemoryGetTracesAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMemoryUpdateConversationAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMemoryUpdateInteractionAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryGetTracesActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryUpdateConversationTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryUpdateInteractionActionTests.java

Add more actions in the memory layer for update Memories with 100% coverage. Memory Manager for Agents is also included. 

Memory Manager and Update Memory Actions/APIs

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
common/src/main/java/org/opensearch/ml/common/input/execute/agent/AgentMLInput.java
common/src/main/java/org/opensearch/ml/common/transport/prediction/MLPredictionTaskRequest.java
common/src/test/java/org/opensearch/ml/common/input/execute/agent/AgentMLInputTests.java
common/src/test/java/org/opensearch/ml/common/transport/prediction/MLPredictionTaskRequestTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/AgentTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MLModelTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/AgentToolTests.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/MLModelToolTests.java

adding mlmodeltool and agent tool with tests

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java

Add more methods to ML client
1. undeploy model
2. delete connector
3. register agent
4. delete agent

add more methods to client

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/RAGTool.java

Change RAG tool description to **Use this tool to retrieve helpful information to answer question.**
Correct RAG tool description.

fix: correct rag tool description

---

plugin/src/main/java/org/opensearch/ml/action/agents/TransportRegisterAgentAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterAgentAction.java
plugin/src/test/java/org/opensearch/ml/action/agents/RegisterAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RegisterAgentTransportActionTests.java

Register Agent rest action and transport action.
Test in local cluster:
```
POST /_plugins/_ml/agents/_register
{
"name": "Test_Agent_For_RAG",
"type": "flow",
"description": "this is a test agent",
"tools": [
{
"type": "VectorDBTool",
"model_id": "zBRyYIsBls05QaITo5ex",
"index": "my_test_data",
"embedding_field": "embedding",
"source_field": [
"text"
],
"input": "${parameters.question}"
}
},
{
"type": "MLModelTool",
"description": "A general tool to answer any question",
"model_id": "NWR9YIsBUysqmzBdifVJ",
"prompt": "\n\nHuman:You are a professional data analysist. You will always answer question based on the given context first. If the answer is not directly shown in the context, you will analyze the data and find the answer. If you don't know the answer, …
```

register agent rest and transport actions

---

common/src/main/java/org/opensearch/ml/common/transport/agent/MLSearchAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/TransportSearchAgentAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLSearchAgentAction.java
plugin/src/test/java/org/opensearch/ml/action/agents/TransportSearchAgentActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchAgentActionTests.java

Implements an API to search agent: `/_plugins/_ml/agents/_search`
Implements an API to search agent: `/_plugins/_ml/agents/_search`

feat: search agent API

---

plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java

Fine tune log message based on error type
NA

Fine tune log message based on error type

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutorTest.java

fix bug - not found agent index

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

The agent catches all errors or exceptions from tools and sends the error messages to the LLM.

handling tool errors

---

docs/remote_inference_blueprints/cohere_v2_connector_embedding_blueprint.md
docs/remote_inference_blueprints/cohere_v3_connector_embedding_blueprint.md

This header allows us to keep track of what project requests are coming from.

Add Request-Source header

---

plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelOnNodeAction.java

Backport a14521dd97397c2ec9f6899e5d7d2f450986a5f9 from #1904

[Backport 2.9] stash thread context before running forward action (#1904)

---

build.gradle

downgrade 2.x branch to 2.11 version for testing purpose

downgrade to 2.11 version for testing purpose

---

plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java

Refine the error message on cluster status not ready scenario
NA

Refine the error message on cluster status not ready scenario

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLMemoryCircuitBreakerIT.java

Update http package import for 2.x as it use httpclient 4.x
fix for this backport PR https://github.com/opensearch-project/ml-commons/pull/1946

Update http package import for 2.x

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java

Fix the issue about duplicated last trace interaction in the memory.
Tested on my local cluster.
https://github.com/opensearch-project/ml-commons/issues/1972

fix dup last trace

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java

If no parameters in tool spec, the agent will throw nullpointexception.

fix empty tool parameter issue

---

common/src/main/java/org/opensearch/ml/common/transport/model/MLUpdateModelInput.java
common/src/test/java/org/opensearch/ml/common/transport/model/MLUpdateModelInputTest.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/models/UpdateModelTransportActionTests.java

This PR should fix the internal connector cannot update bug.

Fix internal connector

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/Configuration.java
common/src/main/java/org/opensearch/ml/common/MLConfig.java
common/src/main/java/org/opensearch/ml/common/transport/config/MLConfigGetAction.java
common/src/main/java/org/opensearch/ml/common/transport/config/MLConfigGetRequest.java
common/src/main/java/org/opensearch/ml/common/transport/config/MLConfigGetResponse.java
common/src/test/java/org/opensearch/ml/common/transport/config/MLConfigGetActionTest.java
common/src/test/java/org/opensearch/ml/common/transport/config/MLConfigGetRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/config/MLConfigGetResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/config/GetConfigTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetConfigAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/config/GetConfigTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetConfigActionTests.java

add get config api to retrieve root agent id

add get config api to retrieve root agent id

---

common/src/main/java/org/opensearch/ml/common/dataset/TextDocsInputDataSet.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLRegisterModelMetaInput.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

[Backport main] Add a version filter to enable bwc in 2.12 (#1944)

---

build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle

This is coming from the PR in main for the CVE issue. https://github.com/opensearch-project/ml-commons/pull/2009

[Backport from Main] fix CVE-2023-2976  and upgrade guava to be consistent (#2009)

---

common/src/main/java/org/opensearch/ml/common/conversation/ActionConstants.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationsResponseTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetInteractionsResponseTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryGetConversationsActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryGetInteractionsActionIT.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/ext/GenerativeQAParameters.java

Some field names should be updated in the memories based on feedbacks from the Tech doc writer.

rename memory field names in responses

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/CatIndexTool.java

Update description for CatIndexTool, to include parameter and output results.
Update description for CatIndexTool, to include parameter and output results.

feat: update description for CatIndexTool

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java

Backport https://github.com/opensearch-project/ml-commons/pull/1980 from main to 2.x.

fix empty tool parameter issue (#1980)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

Backport https://github.com/opensearch-project/ml-commons/pull/2022 from main to 2.x.

tool uses original input (#2022)

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

Backport https://github.com/opensearch-project/ml-commons/pull/1911 from main to 2.x.

bug fix - tool parameters missing (#1911)

---

ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLConversationalFlowAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/ConversationIndexMemory.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

add conversational flow agent

---

release-notes/opensearch-ml-common.release-notes-2.12.0.0.md

updating release note for 2.12

---

build-tools/repositories.gradle
build.gradle

Update the lucene snapshot url per https://github.com/opensearch-project/opensearch-build/issues/3874#issuecomment-1836600851.

Update the lucene snapshot url

---

plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/test/java/org/opensearch/ml/action/prediction/TransportPredictionTaskActionTests.java

[changing error message and error code. Currently error message is default to the 500 error which is not ideal. So we need to set the correct error which we are receiving from the downstream. ]

changing error message and error code

---

release-notes/opensearch-ml-common.release-notes-2.12.0.0.md

Include the latest commits in the release notes.

update release notes 2.12

---

release-notes/opensearch-ml-common.release-notes-2.12.0.0.md

[updating release note for 2.12.0]

updating release note for 2.12.0

---

memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateInteractionTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/DeleteConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetConversationsTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetInteractionTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetInteractionsTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetTracesTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/SearchConversationsTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/SearchInteractionsTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandler.java
memory/src/test/java/org/opensearch/ml/memory/ConversationalMemoryHandlerITTests.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexITTests.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexTests.java
memory/src/test/java/org/opensearch/ml/memory/index/InteractionsIndexTests.java

Refactor memory logs to 1) add more logs info from pen testers' suggestion and 2) replace conversation/interaction with memory/message in the logs based on suggestion from Tec doc writer. 

refactor memory logs

---

common/src/main/java/org/opensearch/ml/common/output/model/ModelTensors.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java

Backport missing PR (#1443) to fix bwc issue
This will partly resolved #1838

Backport missing PR(#1443) to enable bwc in 2.10

---

common/src/main/java/org/opensearch/ml/common/controller/MLRateLimiter.java
common/src/test/java/org/opensearch/ml/common/controller/MLRateLimiterTest.java

This PR will add verification to rate limiter number field to avoid illegal input

Add verification to rate limiter number field

---

docs/tutorials/rerank/rerank_pipeline_with_Cohere_Rerank_model.md

Add tutorial for rerank pipeline with Cohere rerank model

add tutorial for rerank pipeline with Cohere rerank model

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java

[adding BWC for connector config field]

adding BWC for connector config field

---

ml-algorithms/build.gradle

See #2193 
Weird branch reasons -> now I have another PR

Fix onnx dep

---

client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLAgentType.java
common/src/main/java/org/opensearch/ml/common/agent/MLAgent.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentGetRequest.java
common/src/test/java/org/opensearch/ml/common/MLAgentTypeTests.java
common/src/test/java/org/opensearch/ml/common/agent/MLAgentTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetResponseTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunnerTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/indices/MLIndicesHandlerTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/agents/DeleteAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/GetAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/TransportRegisterAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/TransportSearchAgentAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetAgentAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterAgentAction.java
plugin/src/test/java/org/opensearch/ml/action/agents/DeleteAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/agents/GetAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/agents/RegisterAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/agents/TransportSearchAgentActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RegisterAgentTransportActionTests.java

[When an conversational agent is registered with a hidden model, then the agent will be treated as hidden too. We don't want to expose any information for the hidden model.]

implementing hidden agent

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/dataset/MLInputDataType.java
common/src/main/java/org/opensearch/ml/common/dataset/QuestionAnsweringInputDataSet.java
common/src/main/java/org/opensearch/ml/common/input/MLInput.java
common/src/main/java/org/opensearch/ml/common/input/nlp/QuestionAnsweringMLInput.java
common/src/main/java/org/opensearch/ml/common/input/nlp/TextSimilarityMLInput.java
common/src/main/java/org/opensearch/ml/common/model/QuestionAnsweringModelConfig.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensor.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLRegisterModelMetaInput.java
common/src/test/java/org/opensearch/ml/common/MLCommonsClassLoaderTests.java
common/src/test/java/org/opensearch/ml/common/dataset/QuestionAnsweringInputDatasetTest.java
common/src/test/java/org/opensearch/ml/common/input/nlp/QuestionAnsweringMLInputTest.java
common/src/test/java/org/opensearch/ml/common/model/QuestionAnsweringModelConfigTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringTranslator.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModelTest.java

support question answering mode
Backport https://github.com/opensearch-project/ml-commons/pull/2208 from main to 2.13

[Backport 2.13] support question answering model (#2208)

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/dataset/MLInputDataType.java
common/src/main/java/org/opensearch/ml/common/dataset/QuestionAnsweringInputDataSet.java
common/src/main/java/org/opensearch/ml/common/input/MLInput.java
common/src/main/java/org/opensearch/ml/common/input/nlp/QuestionAnsweringMLInput.java
common/src/main/java/org/opensearch/ml/common/input/nlp/TextSimilarityMLInput.java
common/src/main/java/org/opensearch/ml/common/model/QuestionAnsweringModelConfig.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensor.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLRegisterModelMetaInput.java
common/src/test/java/org/opensearch/ml/common/MLCommonsClassLoaderTests.java
common/src/test/java/org/opensearch/ml/common/dataset/QuestionAnsweringInputDatasetTest.java
common/src/test/java/org/opensearch/ml/common/input/nlp/QuestionAnsweringMLInputTest.java
common/src/test/java/org/opensearch/ml/common/model/QuestionAnsweringModelConfigTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringTranslator.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModelTest.java

l### Description
support question answering mode
Backport #2208 from main to 2.x 

[Backport 2.x] support question answering model (#2208)

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java

[updating ml_connector schema version which was missing in [here](https://github.com/opensearch-project/ml-commons/pull/1835/files#r1530774020)]

updating ml_connector schema version

---

.github/CODEOWNERS
MAINTAINERS.md

adding xinyual as maintainer

---

release-notes/opensearch-ml-common.release-notes-2.13.0.0.md

2.13 release note

---

plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java

change default agent framework flag to true due to GA

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRAGSearchProcessorIT.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAResponseProcessor.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/ext/GenerativeQAParameters.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/ChatCompletionInput.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/ChatCompletionOutput.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/DefaultLlmImpl.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/Llm.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/LlmIOUtil.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAResponseProcessorTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/ext/GenerativeQAParamExtBuilderTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/ext/GenerativeQAParametersTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/llm/ChatCompletionInputTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/llm/ChatCompletionOutputTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/llm/DefaultLlmImplTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/llm/LlmIOUtilTests.java

Add support for Cohere and others.
- [ x] New functionality includes testing.
- [ x] All tests pass

Add support for Cohere and others.

---

common/src/main/java/org/opensearch/ml/common/model/Guardrails.java
common/src/main/java/org/opensearch/ml/common/model/MLGuard.java
common/src/test/java/org/opensearch/ml/common/model/GuardrailsTests.java
common/src/test/java/org/opensearch/ml/common/model/MLGuardTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java
plugin/src/test/java/org/opensearch/ml/utils/TestData.java

guardrails bug fixes and IT for creating guardrails

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java

Remove flat_object type for guardrails to support a list of stopwords.
An example as following,
```
PUT /test
{
"mappings": {
"properties": {
"guardrails": {
"type": "flat_object"
}
}
}
}
PUT /test/_doc/1
{
"guardrails": {
"input_guardrail": {
"stop_words": [
{
"index_name": "words0",
"source_fields": ["title"]
},
{
"index_name": "words1",
"source_fields": ["title"]
}
],
"regex": ["regex1", "regex2"]
},
"output_guardrail": {
"stop_words": [
{
"index_name": "words0",
"source_fields": ["title"]
}
],
"regex": ["regex1", "regex2"]
}
}
}
The response
{
"error": {
{
"type": "mapper_parsing_exception",
"reason": "failed to parse field [guardrails] of type [flat_object] in document with id '1'. Preview of field's value: 'null'"
}
],
"type": "mapper_parsing_exception",
"reason": …
```

fix guardrails mapping

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactoryTests.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java

set only_run_on_ml_node default value to false

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java

* Fix connector can use subfield of secrectArn to bypass extraction of credential from AWS
* Forbid all kinds of ARN subfield
* Adjust annotation

[Backport 2.x] Fix connector can use subfield of secrectArn to bypass extraction of credential from AWS (#2320)

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java

Revert adding subfield filter in MLCreateConnectorInput

---

common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java
plugin/src/main/java/org/opensearch/ml/action/controller/CreateControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/DeleteControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/DeployControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/GetControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/UndeployControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/UpdateControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/controller/CreateControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/controller/DeleteControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/controller/GetControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/controller/UpdateControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/UpdateModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeActionTests.java

[For hidden model we don't want to show model id in the exception message to the customer. This PR is removing model id for hidden model wherever possible.]

filter model id for hidden model cases

---

docs/tutorials/aws/AIConnectorHelper.ipynb

Fix no model group index issue in connector helper notebook

fix no model group index issue in connector helper notebook

---

common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java

fixing isHidden null issue

---

plugin/src/main/java/org/opensearch/ml/action/controller/DeleteControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeActionTests.java

making Boolean type for isHidden

---

plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileRequest.java
plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/stats/MLStatsNodesRequest.java
plugin/src/main/java/org/opensearch/ml/action/stats/MLStatsNodesTransportAction.java
plugin/src/main/java/org/opensearch/ml/profile/MLModelProfile.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLProfileAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLStatsAction.java
plugin/src/main/java/org/opensearch/ml/stats/MLModelStats.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/utils/IndexUtils.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileRequestTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/stats/MLStatsNodeResponseTests.java
plugin/src/test/java/org/opensearch/ml/action/stats/MLStatsNodesRequestTests.java
plugin/src/test/java/org/opensearch/ml/action/stats/MLStatsNodesTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLProfileActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLStatsActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLTrainAndPredictIT.java
plugin/src/test/java/org/opensearch/ml/stats/MLModelStatsTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java

[Filtering hidden model info from model profiling for users other than superadmin]

Filtering hidden model info from model profiling for users other than superadmin

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/VisualizationsTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/VisualizationsToolTests.java
ml-algorithms/src/test/resources/org/opensearch/ml/engine/tools/visualization.json
ml-algorithms/src/test/resources/org/opensearch/ml/engine/tools/visualization_not_found.json
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestBaseAgentToolsIT.java
plugin/src/test/java/org/opensearch/ml/tools/MockLLM.java
plugin/src/test/java/org/opensearch/ml/tools/PromptHandler.java
plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java
plugin/src/test/java/org/opensearch/ml/tools/VisualizationsToolIT.java

Move visualization tool to ml-commons
https://github.com/opensearch-project/skills/issues/294
https://github.com/opensearch-project/skills/pull/296

Move visualization tool to ml-commons

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/VisualizationsTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/VisualizationsToolTests.java
ml-algorithms/src/test/resources/org/opensearch/ml/engine/tools/visualization.json
ml-algorithms/src/test/resources/org/opensearch/ml/engine/tools/visualization_not_found.json
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestBaseAgentToolsIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestSearchIndexToolIT.java
plugin/src/test/java/org/opensearch/ml/tools/MockLLM.java
plugin/src/test/java/org/opensearch/ml/tools/PromptHandler.java
plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java
plugin/src/test/java/org/opensearch/ml/tools/VisualizationsToolIT.java

Backport https://github.com/opensearch-project/ml-commons/commit/85d0c9e2b8807162de9afe7c915801b75e486064 from https://github.com/opensearch-project/ml-commons/pull/2363

[Backport 2.x] Move visualization tool to ml-commons

---

build.gradle
common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/transport/model/MLUpdateModelInput.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLRegisterModelMetaInput.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/transport/model/MLUpdateModelInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLRegisterModelMetaInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLRegisterModelMetaRequestTest.java
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java
ml-algorithms/build.gradle
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/utils/MLNodeUtils.java
plugin/src/test/java/org/opensearch/ml/action/models/UpdateModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/prediction/TransportPredictionTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/utils/MLNodeUtilsTests.java

[Backport 2.x] ML Model Interface (#2357)

---

docs/tutorials/agent_framework/Chatbot_with_RAG.md
docs/tutorials/agent_framework/RAG_with_conversational_flow_agent.md
docs/tutorials/agent_framework/build_your_own_chatbot.md
docs/tutorials/conversational_search/conversational_search_with_Cohere_Command.md

fix agent framework document

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Add IT for interface

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java

Backport of https://github.com/opensearch-project/ml-commons/pull/2415

[Backport to 2.x] add deploySetting in registering pretrained models (#2415)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java

Backport of https://github.com/opensearch-project/ml-commons/pull/2415

[Backport to 2.14] add deploySetting in registering pretrained models (#2415)

---

release-notes/opensearch-ml-common.release-notes-2.14.0.0.md

Update 2.14 release notes to include recent ITs and bug fixes.

update 2.14 release notes

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLFlowAgentIT.java

Add integration test case: flow agent + CatIndexTool.

add IT for flow agent with CatIndexTool

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceIngestProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceIngestProcessorIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Check issue #2473
Resolve #2473

fix error of ML inference processor in foreach processor

---

docs/remote_inference_blueprints/bedrock_connector_titan_embedding_blueprint.md
docs/tutorials/semantic_search/generate_embeddings_for_arrays_of_object.md

1. add titan embeeding v2 to blueprint
2. fine tune and fix some error 

add titan embeeding v2 to blueprint

---

docs/remote_inference_blueprints/bedrock_connector_anthropic_claude_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_titan_embedding_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_titan_multimodal_embedding_blueprint.md
docs/remote_inference_blueprints/open_ai_connector_completion_blueprint.md
docs/remote_inference_blueprints/sagemaker_connector_blueprint.md
docs/tutorials/agent_framework/RAG_with_conversational_flow_agent.md
docs/tutorials/agent_framework/build_your_own_chatbot.md

Some small fix for blueprint docs

Small fix in blueprint docs

---

plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLExecuteActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/error/ErrorMessageFactoryTests.java

Unwrap the root cause to return when agent execution gets an exception.
resolve #2443

fix error message with unwrapping the root cause

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/connector/ConnectorAction.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLExecuteConnectorAction.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLExecuteConnectorRequest.java
common/src/test/java/org/opensearch/ml/common/connector/AwsConnectorTest.java
common/src/test/java/org/opensearch/ml/common/connector/HttpConnectorTest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLExecuteConnectorRequestTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandler.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/ConnectorTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandlerTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/ConnectorToolTests.java
plugin/src/main/java/org/opensearch/ml/action/connector/ExecuteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/execute/TransportExecuteTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/connector/ExecuteConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestConnectorToolIT.java

Add connector tool which can invoke REST API

Add connector tool

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/agent/MLAgent.java
common/src/main/java/org/opensearch/ml/common/dataset/TextDocsInputDataSet.java
common/src/main/java/org/opensearch/ml/common/model/MLDeploySetting.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/test/java/org/opensearch/ml/common/agent/MLAgentTest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java
plugin/build.gradle

Forward port #2485 to main branch
This should close #2483, thanks to @dbwiddis 

[Backport main] Remove strict version dependency to compile minimum compatible version

---

docs/remote_inference_blueprints/bedrock_connector_titan_embedding_blueprint.md

Users using OpenSearch version 2.11 can also connect the connector.
[issues link](https://github.com/opensearch-project/ml-commons/issues/2492)
- [o] New functionality has been documented.

Titan Embedding Connector Blueprint content referenced by users of OpenSearch 2.11 version #2517 

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLFlowAgentIT.java

Spotless apply for https://github.com/opensearch-project/ml-commons/pull/2460
Spotless apply for https://github.com/opensearch-project/ml-commons/pull/2460

Fix:run spotless apply for branch Backport/backport 2448 to 2.x

---

plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelAction.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java

This PR should resolve https://github.com/opensearch-project/ml-commons/issues/2419

Fix model still deployed after calling undeploy API

---

plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelAction.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java

[backport 2.x] Fix model still deployed after calling undeploy API (#2510)

---

plugin/src/test/java/org/opensearch/ml/rest/RestConnectorToolIT.java

fix flaky IT

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestBedRockInferenceIT.java
plugin/src/test/resources/org/opensearch/ml/rest/templates/BedRockConnectorBodies.json

backport https://github.com/opensearch-project/ml-commons/pull/2495

[Backport-2.x] Backport fix bedrock preprocess func

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java

disable jvm memory circuit breaker for IT

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelation.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/ConversationIndexMemory.java
plugin/src/main/java/org/opensearch/ml/action/agents/DeleteAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/TransportRegisterAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/DeleteControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java

add IMMEDIATE refresh policy

---

release-notes/opensearch-ml-common.release-notes-2.15.0.0.md

update release notes for 2.15

---

common/src/main/java/org/opensearch/ml/common/model/ModelGuardrail.java
common/src/test/java/org/opensearch/ml/common/model/ModelGuardrailTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java

change guardrail field name

---

common/src/main/java/org/opensearch/sdk/SdkClient.java
common/src/main/java/org/opensearch/sdk/SdkClientUtils.java
common/src/test/java/org/opensearch/sdk/SdkClientUtilsTests.java
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/helper/ConnectorAccessControlHelper.java
plugin/src/test/java/org/opensearch/ml/action/tasks/DeleteTaskTransportActionTests.java

Improves the `SdkClientUtils` class implementations to handle all of the unwrapping of CompletionException and possibly double-wrapped ExecutionExceptions from checked root causes.

[Feature/multi_tenancy] Improve exception unwrapping to handle all cases

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
common/src/main/java/org/opensearch/ml/common/agent/MLAgent.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentDeleteRequest.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentGetRequest.java
common/src/test/java/org/opensearch/ml/common/agent/MLAgentTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentDeleteRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/agents/DeleteAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/GetAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/TransportRegisterAgentAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteAgentAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetAgentAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterAgentAction.java
plugin/src/test/java/org/opensearch/ml/action/agents/DeleteAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/agents/GetAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/agents/RegisterAgentTransportActionTests.java

[Agent Create + Delete + Get for multi-tenancy including sdkclient interface implementation]

Agent Create + Delete + Get for multi-tenancy including sdkclient interface implementation

---

common/src/main/java/org/opensearch/ml/common/conversation/ConversationalIndexConstants.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateInteractionTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/DeleteConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetConversationsTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetInteractionTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetInteractionsTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/SearchConversationsTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/SearchInteractionsTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionTransportAction.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateInteractionTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/DeleteConversationTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationsTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetInteractionTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetInteractionsTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/SearchConversationsTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/SearchInteractionsTransportActionsTests.java

[removing experimental from the Conversation memory feature]

removing experimental from the Conversation memory feature

---

plugin/src/main/java/org/opensearch/ml/action/agents/DeleteAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/GetAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/model_group/GetModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/SearchModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/SearchModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/helper/ConnectorAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClient.java
plugin/src/test/java/org/opensearch/ml/action/agents/DeleteAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/SearchModelGroupTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/GetModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/UpdateModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/helper/ModelAccessControlHelperTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelGroupManagerTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClientTests.java

[Feature/multi_tenancy] Migrate Model APIs using SDKClient

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/MLStaticMockBase.java

Enable tests with mockStatic in MLEngineTest
https://github.com/opensearch-project/ml-commons/issues/2581

Enable tests with mockStatic in MLEngineTest

---

docs/remote_inference_blueprints/bedrock_connector_ai21labs_jurassic_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_anthropic_claude_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_titan_multimodal_embedding_blueprint.md

Make all Bedrock model blueprints in a more aligned manner, so that we can help to create model interface automatically for Bedrock models

Make all Bedrock model blueprints in a tidier format

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java

bump ml config index schema version that was missed in (https://github.com/opensearch-project/ml-commons/pull/1995)
(https://github.com/opensearch-project/ml-commons/issues/2630)

bump ml config index schema version

---

common/src/main/java/org/opensearch/ml/common/connector/MLPreProcessFunction.java
plugin/src/test/resources/org/opensearch/ml/rest/templates/BedRockMultiModalConnectorBodies.json

Change multimodal connector name to bedrock multimodal connector

Change multimodal connector name to bedrock multimodal connector

---

common/src/main/java/org/opensearch/ml/common/utils/ModelInterfaceUtils.java
common/src/test/java/org/opensearch/ml/common/utils/ModelInterfaceUtilsTest.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java
plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java

This PR will enable automated model interface generation on AWS managed llms (Bedrock models), to unblock Fractal team

Automated model interface generation on aws llms

---

build.gradle

change ml-commons build version to a feature version

change ml-commons build version to a feature version

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploader.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploaderTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelGroupManagerTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

add acknowledge check for index creation in missing places

add acknowledge check for index creation in missing places

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java

Manually backport PR Add #2725

[backport 2.13] Add logging for throttling and guardrail in connector

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java

Manually backport PR https://github.com/opensearch-project/ml-commons/pull/2725

[Backport 2.14] Add logging for throttling and guardrail in connector

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Add stashcontext to connector getter to avoid no permission issue

Add StashContext to connector getter

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

[excluding remote models from max node per node setting. Backport PR from [PR](https://github.com/opensearch-project/ml-commons/pull/2732/files)

[BACKPORT 2.9] excluding remote models from max node per node setting

---

plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/SdkClientFactory.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java

Add concurrency support to DDB client. Following changes has been included:
* Set sequence number in CRUD method response. 
* Set or update sequence number in case of create.
* Increment sequence number during update 
* Set data object under _source field

Add concurrency support to DDB client

---

release-notes/opensearch-ml-common.release-notes-2.16.0.0.md

Add release note for 2.16

---

release-notes/opensearch-ml-common.release-notes-2.16.0.0.md

Update release note

---

docs/remote_inference_blueprints/batch_inference_openAI_connector_blueprint.md
docs/remote_inference_blueprints/batch_inference_sagemaker_connector_blueprint.md

Connector Blueprints for offline batch inference against SageMaker and OpenAI.
Related.
https://github.com/opensearch-project/ml-commons/issues/2488

add offline batch inference connector blueprints

---

common/src/main/java/org/opensearch/ml/common/utils/ModelInterfaceUtils.java
common/src/test/java/org/opensearch/ml/common/utils/ModelInterfaceUtilsTest.java

Add more logging for automated model interface creation

Add more logs for automated model interface creation

---

release-notes/opensearch-ml-common.release-notes-2.16.0.0.md

Add more to release note

---

release-notes/opensearch-ml-common.release-notes-2.16.0.0.md

Add release note

---

docs/tutorials/guardrails/use_bedrock_guardrails.md

add tutorial for Bedrock Guardrails

---

.gitignore
common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/sdk/SdkClient.java
common/src/main/java/org/opensearch/sdk/SdkClientDelegate.java
common/src/main/java/org/opensearch/sdk/client/LocalClusterIndicesClient.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java
common/src/test/java/org/opensearch/sdk/GetDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/PutDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/SdkClientSettingsTests.java
common/src/test/java/org/opensearch/sdk/SdkClientTests.java
common/src/test/java/org/opensearch/sdk/SdkClientUtilsTests.java
common/src/test/java/org/opensearch/sdk/SearchDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/UpdateDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/client/LocalClusterIndicesClientTests.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClient.java
plugin/src/test/java/org/opensearch/ml/action/connector/GetConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportCreateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/UpdateModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelGroupManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java
plugin/src/test/java/org/opensearch/ml/utils/TenantAwareHelperTests.java

Implements filtering by tenant ID in `LocalClusterIndicesClient` and `RemoteClusterIndicesClient`.

[Feature/multi_tenancy] Implement tenant id in Local and Remote Cluster Search Clients

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java

delete model chunks for other models except remote model

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutorTest.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Merging both https://github.com/opensearch-project/ml-commons/pull/2821 and https://github.com/opensearch-project/ml-commons/pull/2824 to 2.x
Resolves CI error in https://github.com/opensearch-project/ml-commons/pull/2821

[Backport 2.x] Enhance: support skip_validating_missing_parameters in connector

---

plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java

This change includes following bug fixes:
* Update DDB table fails to update if both attributeUpdates and attributeUpdateExpression is specified. Moved all updates to make use of `attributeUpdateExpression`
* Using non-system index for remote opensearch cluster.

Using expression attributes to update document source 

---

build.gradle
common/src/main/java/org/opensearch/ml/common/CommonValue.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

[
1. Adding sdkClient for task manager to create task
2. Updating snapshot to 2.16
3. making master key id unique for multi-tenancy
]

adding sdkClient for task manager to create task + updating snapshot + making master key id unique for multi_tenancy

---

memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java

Add refresh policy for missing ones
https://github.com/opensearch-project/ml-commons/issues/1883

Add refresh policy for missing ones

---

plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java

Adds more tenant ID checks for connector update and delete.

[Feature/multi_tenancy] Fix Connector Update and Delete tenant awareness

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java

Excludes the just-deleted document from the `DeleteByQuery` for models.  Deleted documents can still show up in search hits, and in edge cases can cause the delete by query to fail.

[Feature/multi_tenancy] Exclude the document just deleted from the model delete by query

---

release-notes/opensearch-ml-common.release-notes-2.17.0.0.md

add 2.17 release note

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRAGSearchProcessorIT.java

Add back RAG IT tests that use Converse API.

---

plugin/src/main/java/org/opensearch/ml/action/controller/CreateControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/DeleteControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/GetControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/UpdateControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCreateControllerAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteControllerAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetControllerAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdateControllerAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/test/java/org/opensearch/ml/action/controller/CreateControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/controller/DeleteControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/controller/GetControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/controller/UpdateControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateControllerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteControllerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetControllerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateControllerActionTests.java
plugin/src/test/java/org/opensearch/ml/settings/MLFeatureEnabledSettingTests.java

Add feature enable setting for controller index

---

plugin/src/main/java/org/opensearch/ml/action/batch/TransportBatchIngestionAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetTaskAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/test/java/org/opensearch/ml/action/batch/TransportBatchIngestionActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/GetTaskTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionActionTests.java

Add the feature flag for offline batch ingestion.

add feature flag for offline batch ingestion

---

release-notes/opensearch-ml-common.release-notes-2.17.1.0.md

add 2.17.1 release notes

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java

fixing unit test for multi_tenancy

---

plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessageFactory.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLExecuteActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/error/ErrorMessageFactoryTests.java

[Backport PR from [2458](https://github.com/opensearch-project/ml-commons/pull/2458)]

fix error message with unwrapping the root cause (#2458)

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/connector/ConnectorAction.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLExecuteConnectorAction.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLExecuteConnectorRequest.java
common/src/test/java/org/opensearch/ml/common/connector/AwsConnectorTest.java
common/src/test/java/org/opensearch/ml/common/connector/HttpConnectorTest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLExecuteConnectorRequestTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandler.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/ConnectorTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandlerTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/ConnectorToolTests.java
plugin/src/main/java/org/opensearch/ml/action/connector/ExecuteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/execute/TransportExecuteTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/connector/ExecuteConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestConnectorToolIT.java

* Add connector tool (#2512)
* expose connector action parameter
* add connector tool
* fix ut
* fix it
* fix flaky test
---------
(cherry picked from commit a0272f2138254cf47a4e82c01173f8fb2ba0a7be)
* fix invalid class
---------

[Backport 2.x] Add connector tool (#2516)

---

plugin/build.gradle

…ompatible version (#2486)
* [Feature/multi_tenancy] Remove strict version dependency to compile minimum compatible version (#2485)
* Remove strict version dependency to compile minimum compatible version
* Only declare version constants once
---------
* Remove unnecessary dependency
* remove space
---------

[Backport Feature/multi_tenancy] Remove strict version dependency to compile minimum compatible version (#2485)

---

common/build.gradle
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceIngestProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java

Manual backport due to conflict #2985
https://github.com/opensearch-project/ml-commons/issues/2974

[Backport 2.16]  Fix ml inference ingest processor always return list using JsonPath

---

plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelGroupActionIT.java

* adding immediate refresh to delete model group request
* fix format violations
* add IT tests
* remove thread sleep
---------

adding immediate refresh to delete model group request (#2514)

---

common/src/main/java/org/opensearch/sdk/client/LocalClusterIndicesClient.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelGroupActionIT.java

[fixing integ tests and refresh in delete action]

fixing integ tests and refresh in delete action

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceIngestProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/ModelExecutor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorFactoryTests.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceIngestProcessorIT.java

* ml inference ingest processor support for local models

ml inference ingest processor support for local models (#2508)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactory.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactoryTests.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

* add setting to allow private IP
* fix ut
---------

add setting to allow private IP (#2534)

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java

changes for PR 2534

---

common/build.gradle
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceIngestProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java

Manual backport due to conflict https://github.com/opensearch-project/ml-commons/pull/2985
https://github.com/opensearch-project/ml-commons/issues/2974

[Backport 2.15] Fix ml inference ingest processor always return list using JsonPath

---

plugin/src/test/java/org/opensearch/ml/settings/MLFeatureEnabledSettingTests.java

fixing unit test

---

common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/output/MLPredictionOutput.java
common/src/test/java/org/opensearch/ml/common/output/MLPredictionOutputTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java
plugin/src/main/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/tasks/GetTaskTransportActionTests.java

Backport https://github.com/opensearch-project/ml-commons/pull/3080

[Backport 2.17] Enhance batch job task management by adding default action types (#3080)

---

common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/output/MLPredictionOutput.java
common/src/test/java/org/opensearch/ml/common/output/MLPredictionOutputTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java
plugin/src/main/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/tasks/GetTaskTransportActionTests.java

Backport https://github.com/opensearch-project/ml-commons/pull/3080

[Backport 2.x] Enhance batch job task management by adding default action types (#3080)

---

docs/remote_inference_blueprints/bedrock_connector_titan_embedding_blueprint.md

tune titan embedding model blueprint to support V2

tune titan embedding model blueprint for v2

---

docs/remote_inference_blueprints/bedrock_connector_converse_blueprint.md

connector blueprint for amazon bedrock converse

---

DEVELOPER_GUIDE.md

As of October 2nd 2024, you will need to ask for maintainer approval to run the GitHub
CI/CD workflow actions to see your code changes build on pushing your PR.

Updates dev guide to inform the workflow approval step

---

docs/remote_inference_blueprints/bedrock_connector_titan_multimodal_embedding_blueprint.md

Add bedrock multimodal build-in function usage example in doc
https://github.com/opensearch-project/ml-commons/issues/3060

Add bedrock multimodal build-in function usage example in doc

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java

[updating task and corresponding unit tests]

updating task and corresponding unit tests

---

.github/workflows/CI-workflow.yml

upgrading upload artifact to v4
More in [this discussion](https://github.com/opensearch-project/ml-commons/pull/3139#issuecomment-2436053272)

upgrading upload artifact to v4

---

release-notes/opensearch-ml-common.release-notes-2.18.0.0.md

[updating the release notes for 2.18]

updating the release notes for 2.18

---

docs/tutorials/rerank/rerank_pipeline_with_bge-rerank-m3-v2_model_deployed_on_Sagemaker.md

Add tutorial for bge-reranker-m3-v2, multilingual cross-encoder model on SageMaker
Add a tutorial document for bge-reranker-m3-v2, multilingual cross-encoder model on SageMaker. 
Resolves #2845
- [*] Commits are signed per the DCO using `--signoff`.

Add tutorial for bge-reranker-m3-v2, multilingual cross-encoder model on SageMaker

---

common/src/main/java/org/opensearch/ml/common/input/parameter/MLAlgoParams.java

Fix: typo in MLAlgoParams

---

.github/workflows/CI-workflow.yml

Enable custom start commands and options to resolve GHA issues
https://github.com/opensearch-project/opensearch-build/issues/5178
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CO …

Enable custom start commands and options to resolve GHA issues

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java

* increase the wait timeout to fetch the master key
* fix UTs
---------

[backport 2.14] increase the wait timeout to fetch the master key (#3151) (#3178)

---

ml-algorithms/build.gradle

[upgrading commons-io and protobuf-java to avoid CVE issues]
Resolves  CVE Issues: 
1. https://advisories.opensearch.org/advisories/CVE-2024-7254
2. https://advisories.opensearch.org/advisories/CVE-2024-47554

upgrading commons-io and protobuf-java to avoid CVE issues

---

release-notes/opensearch-ml-common.release-notes-1.3.20.0.md

release note for 1.3.20.0

---

spi/src/main/java/org/opensearch/ml/common/spi/memory/Memory.java

Fix: typo in Memory interface

---

.github/CODEOWNERS
MAINTAINERS.md

* adding more log to debug the testVisualizationFound issue
* changing back
* adding mingshi as maintainer
---------

Adding back Mingshi as Maintainer. (#3367)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java

[Backport 2.16] increase the wait timeout to fetch the master key

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java

increase the wait timeout to fetch the master key (#3151) (#3177)

---

common/src/main/java/org/opensearch/ml/common/output/execute/anomalylocalization/AnomalyLocalizationOutput.java
common/src/main/java/org/opensearch/ml/common/output/execute/samplecalculator/LocalSampleCalculatorOutput.java
common/src/test/java/org/opensearch/ml/common/output/execute/anomalylocalization/AnomalyLocalizationOutputTests.java
common/src/test/java/org/opensearch/ml/common/output/execute/samplecalculator/LocalSampleCalculatorOutputTest.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLExecuteActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Fix JsonGenerationException error by adding root object wrapper in LocalSampleCalculatorOutput and AnomalyLocalizationOutput.
Resolves https://github.com/opensearch-project/ml-commons/issues/3413

Fix JsonGenerationException error in Local Sample Calculator and Anomaly Localization Execution Response

---

client/build.gradle
common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
search-processors/build.gradle

Adds the spotless apply change to all build.gradle files
Addresses https://github.com/opensearch-project/ml-commons/pull/3450

add spotless to all build.gradle files

---

common/src/main/java/org/opensearch/ml/common/output/execute/anomalylocalization/AnomalyLocalizationOutput.java
common/src/main/java/org/opensearch/ml/common/output/execute/samplecalculator/LocalSampleCalculatorOutput.java
common/src/test/java/org/opensearch/ml/common/output/execute/anomalylocalization/AnomalyLocalizationOutputTests.java
common/src/test/java/org/opensearch/ml/common/output/execute/samplecalculator/LocalSampleCalculatorOutputTest.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLExecuteActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Backport https://github.com/opensearch-project/ml-commons/pull/3434 to 2.x

[Backport 2.x] Fix JsonGenerationException error in Local Sample Calculator and Anomaly Localization Execution Response

---

docs/remote_inference_blueprints/deepseek_connector_chat_blueprint.md

Update DeepSeek connector blueprint to include a step to add connector endpoint to trusted URLs and remove `stream` parameter.

Update DeepSeek connector blueprint

---

docs/remote_inference_blueprints/deepseek_connector_chat_blueprint.md

Backport https://github.com/opensearch-project/ml-commons/pull/3460 to 2.x

[Backport 2.x] Update DeepSeek connector blueprint

---

plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

fixing connector validation

---

common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle

Fix ai.djl:api CVE by upgrading the version from  0.28.0 to 0.31.1

fix CVE from ai.djl dependency

---

common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle

[Backport] CVE fix

---

common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle

[[Backport 2.19] CVE fix #3482]

[Backport 2.19] CVE fix

---

docs/tutorials/aws/RAG_with_DeepSeek_Chat_model.md
docs/tutorials/aws/RAG_with_DeepSeek_R1_model_on_Bedrock.md
docs/tutorials/aws/RAG_with_DeepSeek_R1_model_on_Sagemaker.md

link DeepSeek demo notebook to tutorials

link DeepSeek demo notebook to tutorials

---

plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterAgentAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRegisterAgentActionTests.java

[adding tenantId in the agent registration request for multi-tenancy]

adding tenantId in the agent registration request for multi-tenancy

---

release-notes/opensearch-ml-common.release-notes-2.19.0.0.md

Release note for 2.19.0 release

Release note for 2.19.0 release

---

plugin/src/main/java/org/opensearch/ml/action/agents/TransportSearchAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/models/SearchModelTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/agents/TransportSearchAgentActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java

Signed-off-by: Dhrubo Saha <dhrubo@amazon.com>
(cherry picked from commit 5432f25e8a8097332dbfee5eabbfb9fcce5beb6e)

[BACKPORT PR[ remainig sdk client changes for search (#3522)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

* applying sdkclient changes to config index
Signed-off-by: Dhrubo Saha <dhrubo@amazon.com>
* addressed comments
Signed-off-by: Dhrubo Saha <dhrubo@amazon.com>
---------
Signed-off-by: Dhrubo Saha <dhrubo@amazon.com>
(cherry picked from commit eccfd4484c79555868022c761091ce649e999ab9)

[BACKPORT TO 2.19] applying sdkclient changes to config index (#3521)

---

.github/workflows/CI-workflow.yml

[Release 3.0] Add JDK23 support to github actions
https://github.com/opensearch-project/ml-commons/issues/1140
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#devel …

[Release 3.0] Add JDK23 support to github actions

---

plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java

Before
After
https://github.com/opensearch-project/ml-commons/issues/3408

Fix last_updated_time not updating in model group updates

---

plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelAction.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelActionTests.java

* updating bulk update to use sdkclient
* addressed comments
---------

[BACKPORT TO 2.X] updating bulk update to use sdkclient (#3546)

---

release-notes/opensearch-ml-common.release-notes-2.19.1.0.md

release note for 2.19.1

---

docs/tutorials/ml_inference/semantic_search/semantic_search_for_long_document.md

Add a tutorial for how to build semantic search for long document with ML inference processor.

add tutorial: semantic search for long document with ML inference processor

---

docs/tutorials/ml_inference/semantic_search/optimize_vector_search_with_cohere_compressed_embedding.md

add tutorial: optimize vector search with Cohere compressed embedding

add tutorial: optimize vector search with Cohere compressed embedding

---

docs/tutorials/ml_inference/semantic_search/optimize_vector_search_with_cohere_compressed_embedding.md

add binary embedding to tutorial

add binary embedding to tutorial

---

plugin/build.gradle

fix build error
https://github.com/opensearch-project/ml-commons/issues/3593

fix build error

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
plugin/src/test/java/org/opensearch/ml/rest/RestBedRockInferenceIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestCohereInferenceIT.java

Remove private api key and fix failure IT

Remove private api key

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/CatIndexToolTests.java

https://github.com/opensearch-project/ml-commons/issues/3616

fix building error due to a breakding change from core

---

common/src/main/java/org/opensearch/ml/common/dataset/QuestionAnsweringInputDataSet.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/QAConstants.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/SentenceHighlightingQATranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/sentence/DefaultSentenceSegmenter.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/sentence/Sentence.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/sentence/SentenceSegmentationConfig.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/sentence/SentenceSegmenter.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/SentenceHighlightingQAModelIT.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/SentenceHighlightingQAModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/SentenceHighlightingQATranslatorTest.java

This PR adds support for sentence highlighting in the Question Answering model. This feature allows the model to identify and highlight the most relevant sentences in a context that answer a given question, rather than extracting specific answer spans.
* Register model:
* To register a sentence highlighting QA model, you must specify the model type as `sentence_highlighting` in the model configuration:
```
{
"name": "sentence-highlighting-qa-model",
"version": "1.0.0",
"description": "A question answering model that highlights relevant sentences in the context",
"model_format": "TORCH_SCRIPT",
"function_name": "QUESTION_ANSWERING",
"model_config": {
"model_type": "sentence_highlighting",
"framework_type": "HUGGINGFACE_TRANSFORMERS",
},
"model_content_hash_value": "abcdef123456789", …
```

Support sentence highlighting QA model

---

common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/Predictable.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionStreamingAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java

This pr is mainly for the community to have an early review about the streaming feature in ml plugin.
It's the first part about rest streaming api.
Currently this pr can't be built successfully, as it depends on the new streaming feature from opensearch.
https://github.com/opensearch-project/ml-commons/issues/3328

rest stream predict api

---

release-notes/opensearch-ml-common.release-notes-3.0.0.0-alpha1.md

Add release note 3.0 alpha1
[Resolves #[Issue number to be closed when this PR is merged]
](https://github.com/opensearch-project/opensearch-build/issues/3747#issuecomment-2705433971)

Add release note 3.0 alpha1

---

plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

[fixing the circuit breaker issue for remote model]

fixing the circuit breaker issue for remote model

---

release-notes/opensearch-ml-common.release-notes-3.0.0.0-alpha1.md

Add breaking change to release note

Add breaking change to release note

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java

move llm interface construction to agentUtils

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/FunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/FunctionCallingFactory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/LLMMessage.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/OpenaiV1ChatCompletionsFunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/IndexMappingTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/ListIndexTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/McpSseTool.java

openai v1 chat completions function calling

---

release-notes/opensearch-ml-common.release-notes-3.0.0.0-beta1.md

add release note for 3.0 beta1 release
https://github.com/opensearch-project/opensearch-build/issues/3747

add release note for 3.0 beta1 release

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/BedrockConverseDeepseekR1FunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/BedrockConverseFunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/FunctionCallingFactory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/OpenaiV1ChatCompletionsFunctionCalling.java

function calling bug fix

---

plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java

Add more logs to troubleshot flaky test
https://github.com/opensearch-project/ml-commons/issues/3347

Add more logs to troubleshot flaky test

---

plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java

add sdk implementation to the connector search. This is not changing any existing functionality. This is just using sdk client wrapper which eventually invokes client for opensource.

add sdk implementation to the connector search

---

plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/SearchModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/SearchTaskTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/tasks/SearchTaskTransportActionTests.java

[sdk client implementation for search connector, model group and task]

sdk client implementation for search connector, model group and task

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/BedrockConverseDeepseekR1FunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/BedrockConverseFunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/BedrockMessage.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/FunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/FunctionCallingFactory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/LLMMessage.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/OpenaiMessage.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/OpenaiV1ChatCompletionsFunctionCalling.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/function_calling/BedrockConverseDeepseekR1FunctionCallingTests.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/function_calling/BedrockConverseFunctionCallingTests.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/function_calling/OpenaiV1ChatCompletionsFunctionCallingTests.java

function calling for openai v1, bedrock claude and deepseek

---

release-notes/opensearch-ml-common.release-notes-3.0.0.0-beta1.md

Add more release notes to 3.0.0-beta-1 release

Add more release notes to 3.0.0-beta-1 release

---

release-notes/opensearch-ml-common.release-notes-2.19.2.0.md

Add release notes for 2.19.2

---

release-notes/opensearch-ml-common.release-notes-3.0.0.0.md

Add release note for 3.0, which combines all PRs from alpha, beta and GA

Add release note for 3.0

---

plugin/build.gradle

upgrade http client to version align with core

upgrade http client to version align with core

---

plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java

add more logging to deploy/undeploy flows for better debugging

add more logging to deploy/undeploy flows for better debugging

---

memory/build.gradle
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/Predictable.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/McpConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionStreamingAction.java
plugin/src/main/plugin-metadata/plugin-security.policy
search-processors/build.gradle

This is the third pr for model inference streaming on feature branch. It supports model inference streaming with the OpenAI endpoint.
https://github.com/opensearch-project/ml-commons/issues/3328
The RFC, https://github.com/opensearch-project/ml-commons/issues/3630

openai streaming poc

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/Predictable.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/McpConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelationTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/sparse_encoding/TextEmbeddingSparseEncodingModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingDenseModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_similarity/TextSimilarityCrossEncoderModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/tokenize/SparseTokenizerModelTest.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionStreamingAction.java
plugin/src/test/java/org/opensearch/ml/action/connector/UpdateConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLExecuteTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java

fix UT and spotless

---

plugin/build.gradle

A quick fix. In long term way, we should address the issue https://github.com/opensearch-project/ml-commons/issues/3843.
https://github.com/opensearch-project/ml-commons/issues/3842

quick fix for guava noclass issue

---

common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorRequestTests.java
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java

[adding / as a valid character as for pre-trained model we allow `/` 
refer to this issue: https://github.com/opensearch-project/ml-commons/issues/3853
]

adding / as a valid character

---

common/src/main/java/org/opensearch/ml/common/transport/prompt/MLUpdatePromptAction.java
common/src/main/java/org/opensearch/ml/common/transport/prompt/MLUpdatePromptInput.java
common/src/main/java/org/opensearch/ml/common/transport/prompt/MLUpdatePromptRequest.java
common/src/test/java/org/opensearch/ml/common/transport/prompt/MLUpdatePromptActionTest.java
common/src/test/java/org/opensearch/ml/common/transport/prompt/MLUpdatePromptInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/prompt/MLUpdatePromptRequestTest.java
plugin/src/main/java/org/opensearch/ml/action/prompt/GetPromptTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/prompt/TransportCreatePromptAction.java
plugin/src/main/java/org/opensearch/ml/action/prompt/UpdatePromptTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/prompt/MLPromptManager.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdatePromptAction.java
plugin/src/test/java/org/opensearch/ml/action/prompt/TransportCreatePromptActionTests.java
plugin/src/test/java/org/opensearch/ml/action/prompt/UpdatePromptTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/prompt/MLPromptManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdatePromptActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Implements an API to update a prompt
Resolves #3711 

UPDATE Prompt API 

---

common/src/main/java/org/opensearch/ml/common/transport/prompt/MLPromptSearchAction.java
plugin/src/main/java/org/opensearch/ml/action/prompt/SearchPromptTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLSearchPromptAction.java
plugin/src/test/java/org/opensearch/ml/action/prompt/SearchPromptTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchPromptActionTests.java

Implements an API to search a prompt
Resolves #3711 

SEARCH Prompt API 

---

release-notes/opensearch-ml-common.release-notes-3.1.0.0.md

Updates release notes to add bug fixes
N/A

update 3.1.0 release notes

---

docs/remote_inference_blueprints/standard_blueprints/sagemaker_semantic_highlighter_standard_blueprint.md

Add blueprint for semantic highlighter model on AWS Sagemaker. 
Follow up to 
https://github.com/opensearch-project/opensearch-py-ml/pull/513
https://github.com/opensearch-project/neural-search/issues/1182

Add blueprint for semantic highlighter model on AWS Sagemaker

---

common/src/main/java/org/opensearch/ml/common/memorycontainer/MLMemoryContainer.java
common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/MLCreateMemoryContainerInput.java
common/src/main/resources/index-mappings/ml_memory_container.json
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportCreateMemoryContainerAction.java

Revise user memory index field

Revise user memory index field

---

docs/tutorials/agent_framework/Agentic_RAG.md

add agentic rag tutorial

---

common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentUpdateInput.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentUpdateInputTest.java
plugin/src/test/java/org/opensearch/ml/action/agents/UpdateAgentTransportActionTests.java

Currently, agent update API allows partial updates to its fields. For example, 
```
PUT _plugins/_ml/agents/{{agent_id}}
{
"name": "UPDATED agent"
}
```
This will only update the agent name field and leave other fields as-is. However, when updating sub-fields of `llm` and `memory`, `llm.model_id` and `memory.type` are required. 
This PR will make those fields also optional during an update operation (the result agent will keep values from before the update), so that it is consistent with other fields.
-----
Verified the below cases which are also included in UT:
1. Update `llm.parameters.max_iteration` only:
```
PUT {{endpoint}}/_plugins/_ml/agents/{{agent_id}}
{
"llm": {
"max_iteration": 50
}
}
}
```
2. Update `memory.session_id` only:
```
PUT …
```

[FIX] allow partial updates to llm and memory fields in MLAgentUpdateInput

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLIndex.java
common/src/main/java/org/opensearch/ml/common/memorycontainer/MLMemoryContainer.java
common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java
common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryStorageConfig.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/MLCreateMemoryContainerAction.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/MLCreateMemoryContainerInput.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/MLCreateMemoryContainerRequest.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/MLCreateMemoryContainerResponse.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/MLMemoryContainerGetAction.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/MLMemoryContainerGetRequest.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/MLMemoryContainerGetResponse.java
common/src/main/resources/index-mappings/ml_memory_container.json
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportCreateMemoryContainerAction.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportGetMemoryContainerAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCreateMemoryContainerAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetMemoryContainerAction.java

Implement create and add memory container API
Part of #3979

Implement create and add memory container API

---

common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/MLCreateMemoryContainerRequest.java
common/src/test/java/org/opensearch/ml/common/memorycontainer/MLMemoryContainerTests.java
common/src/test/java/org/opensearch/ml/common/memorycontainer/MemoryStorageConfigTests.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/MLCreateMemoryContainerInputTests.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/MLCreateMemoryContainerRequestTests.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/MLCreateMemoryContainerResponseTests.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/MLMemoryContainerGetRequestTests.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/MLMemoryContainerGetResponseTests.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportCreateMemoryContainerAction.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportGetMemoryContainerAction.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportCreateMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportGetMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetMemoryContainerActionTests.java

[adding unit tests for create and get memory container functionalities: 
https://github.com/opensearch-project/ml-commons/pull/4050
]

adding unit tests for create and get memory container functionalities

---

build.gradle
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportCreateMemoryContainerActionTests.java

adding more unit tests and upgrading jacoco

adding more unit tests and upgrading jacoco

---

common/src/main/java/org/opensearch/ml/common/settings/MLCommonsSettings.java
common/src/main/java/org/opensearch/ml/common/settings/MLFeatureEnabledSetting.java
common/src/test/java/org/opensearch/ml/common/settings/MLCommonsSettingsTests.java
common/src/test/java/org/opensearch/ml/common/settings/MLFeatureEnabledSettingTests.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportCreateMemoryContainerAction.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportGetMemoryContainerAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCreateMemoryContainerAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetMemoryContainerAction.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportCreateMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportGetMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/settings/MLFeatureEnabledSettingTests.java

[adding feature flag for agentic memory]

adding feature flag for agentic memory

---

plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportDeleteMemoryContainerAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteMemoryContainerAction.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportDeleteMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteMemoryContainerActionTests.java

Add feature flag for delete memory container

Add feature flag for delete memory container

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/QueryPlanningPromptTemplate.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/QueryPlanningTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/QueryPlanningToolTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestQueryPlanningToolIT.java

The default prompt is updated to give more reliable responses.
With this change the instructions are sent in the user prompt instead of system prompt.
Steps to use the queryPlannerTool:
Step 1: Enable Agentic Search
```
PUT /_cluster/settings/
{
"persistent": {
"plugins.ml_commons.agentic_search_enabled": "true",
}
}
```
Step 2: Register OpenAI Model
```
POST /_plugins/_ml/models/_register
{
"name": "My OpenAI model: gpt-4o",
"connector": {
"name": "My openai connector: gpt-40",
"description": "The connector to openai chat model",
"version": 1,
"protocol": "http",
"model": "gpt-4o"
},
"openAI_key": "<YOUR_OPENAI_KEY>"
},
"actions": [
{
"action_type": "predict",
"method": "POST",
"url": …
```

Fix Default prompt of Query Planner Tool

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/constant/CommonValueTests.java
plugin/src/test/java/org/opensearch/ml/profile/MLModelProfileTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionActionTests.java

adding more unit tests

---

.github/CODEOWNERS
MAINTAINERS.md

Update maintainer list to add @pyek-bot 
Related to https://github.com/opensearch-project/.github/issues/377

Update maintainer list

---

docs/tutorials/ml_inference/language_identification/ml_inference_with_language_identification_ingest.md

Change suggested instance type in tutorial

Change suggested instance type in tutorial

---

common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle

[Opensearch core reverted a [PR](https://github.com/opensearch-project/OpenSearch/pull/19430) which is breaking the build in ml-commons. This PR is fixing that issue.]

fixing build issue in ml-commons

---

common/src/main/java/org/opensearch/ml/common/settings/MLCommonsSettings.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Fix model deploy issue and address other comments in #4003
Resolves #4205

Fix model deploy issue and address other comments in #4003

---

common/src/main/java/org/opensearch/ml/common/memorycontainer/MLWorkingMemory.java
common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java
common/src/main/java/org/opensearch/ml/common/memorycontainer/WorkingMemoryType.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLAddMemoriesInput.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLAddMemoriesInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLAddMemoriesRequestTest.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/TransportAddMemoriesAction.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemorySearchServiceTests.java

Further refactor on working memory related class

---

plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/TransportSearchMemoriesAction.java
plugin/src/main/java/org/opensearch/ml/helper/MemoryContainerHelper.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportCreateMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportSearchMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportUpdateMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemoryInfoTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemoryOperationsServiceTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingServiceTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportAddMemoriesActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportDeleteWorkingMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportGetWorkingMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportSearchMemoriesActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportUpdateMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/helper/MemoryContainerHelperTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteWorkingMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetWorkingMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/MemorySearchQueryBuilderTests.java

Add UT coverages

---

plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportSearchMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/TransportUpdateMemoryContainerActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportAddMemoriesActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportGetWorkingMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportSearchMemoriesActionTests.java

Add more UT coverages

---

common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLDeleteMemoriesByQueryAction.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLDeleteMemoriesByQueryRequest.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLDeleteMemoriesByQueryRequestTests.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/TransportDeleteMemoriesByQueryAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteMemoriesByQueryAction.java

```
POST /_plugins/_ml/memory_containers/797imZkBx9qVSdxjWYtu/memories/long_term/_delete_by_query
{
"query": {
"match": {
"memory_type": "SEMANTIC"
}
}
}
```
```
{
"took": 99,
"timed_out": false,
"deleted": 8,
"batches": 1,
"version_conflicts": 0,
"noops": 0,
"retries": {
"bulk": 0,
"search": 0
},
"throttled_millis": 0,
"requests_per_second": "Infinity",
"throttled_until_millis": 0
}
```

Add a generic delete by query API

---

common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLDeleteMemoriesByQueryAction.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLDeleteMemoriesByQueryResponse.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLDeleteMemoriesByQueryResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/TransportDeleteMemoriesByQueryAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteMemoriesByQueryAction.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportDeleteMemoriesByQueryActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteMemoriesByQueryActionTests.java

Migrate API business logic from rest layer to transport layer to follow our ML plugin API develop pattern. Also try to add more UT coverage to fix CI

fix: refactor memory delete by query API to avoid anti pattern

---

.github/workflows/require-approval.yml

Update approver matching to be exact match

Update approver matching to be exact match

---

plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionStreamAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionStreamActionTests.java

When running the predict stream API on a security-enabled cluster, we encountered this error and received `Failed to find model` error despite confirming that the model exists. 
```
[2025-10-02T22:31:00,372][WARN ][o.o.s.c.SecurityFlsDlsIndexSearcherWrapper] [data1] search action for .plugins-ml-model is not allowed for a non adminDN user
```
The issue was caused by performing model searches without stashing context. Tested with security enabled cluster, and this change should fix the issue. …

Fix stream predict with security enabled
