plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
plugin/src/main/java/org/opensearch/ml/model/MLModel.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/training/TrainingITTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

1. Add ML model calss.
2. Separate model id and task id

refactor persisting ML model

---

ml-algorithms/build.gradle

Use latest version of tribuo to fix modify thread group permission issue
https://github.com/opensearch-project/ml-commons/issues/67

use latest version of tribuo to fix modify thread group permission issue

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizer.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImpl.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/CountMinSketch.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/CountSketch.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/Counter.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/HashMapCounter.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/Hashmap.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/HybridCounter.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/Input.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/Output.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImplTests.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/anomalylocalization/HybridCounterTests.java

Signed-off-by: lai <laijiang@amazon.com>
This change contains the implementation of the core anomaly localization solution. It does not have integration with ml-commons, which will be in separate pr from after this.

add anomaly localization implementation

---

build-tools/repositories.gradle
build.gradle

Signed-off-by: Amit Galitzky <amgalitz@amazon.com>
Removed jcenter dependency as it is no longer operating. We have mavenCentral() as a fallback.
resolves #120 

Remove jcenter dependency

---

common/src/main/java/org/opensearch/ml/common/parameter/MLTrainingOutput.java
common/src/main/java/org/opensearch/ml/common/transport/training/MLTrainingTaskRequest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/Model.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/model/MLTask.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLTrainingAction.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskCache.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/training/TrainingITTests.java
plugin/src/test/java/org/opensearch/ml/model/MLTaskTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/utils/IntegTestUtils.java

Support training ML model in either sync or async way.
For example, PPL user should be able to train ML model in sync way; and user can use async way if the model training will be time consuming.
Main changes:
1. Support `async` URL parameter in train API. Add `?async=true` if need to train model in async way, by default will train model in sync way.
2. If train model in sync way, won't persist task in index.
3. For sync way, will return both model id and task id. For async way, will just return task id and user need to poll task to know its state/progress.
4. Use `GetRequest` to get model in predict task runner
For more information …

support train ML model in either sync or async way

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImplTests.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Signed-off-by: lai <57818076+wnbts@users.noreply.github.com>
This pr implements integration [step 4 and 5](https://github.com/opensearch-project/ml-commons/blob/main/docs/how-to-add-new-function.md#step-4-add-implementation-1) for anomaly localization.

anomaly localization integration step 4 and 5

---

common/src/main/java/org/opensearch/ml/common/dataframe/ColumnType.java
common/src/main/java/org/opensearch/ml/common/dataframe/ColumnValue.java
common/src/main/java/org/opensearch/ml/common/dataframe/ColumnValueBuilder.java
common/src/main/java/org/opensearch/ml/common/dataframe/ColumnValueReader.java
common/src/main/java/org/opensearch/ml/common/dataframe/FloatValue.java
common/src/test/java/org/opensearch/ml/common/dataframe/ColumnValueBuilderTest.java
common/src/test/java/org/opensearch/ml/common/dataframe/ColumnValueReaderTest.java
common/src/test/java/org/opensearch/ml/common/dataframe/ColumnValueTest.java
common/src/test/java/org/opensearch/ml/common/dataframe/FloatValueTest.java

Support float type in data frame.
@jackiehanyang , you need to add float type in `MLCommonsOperator#convertRowIntoExprValue` method.
#128 

support float type in data frame

---

common/src/main/java/org/opensearch/ml/common/dataframe/ColumnType.java
common/src/main/java/org/opensearch/ml/common/dataframe/ColumnValue.java
common/src/main/java/org/opensearch/ml/common/dataframe/ColumnValueBuilder.java
common/src/main/java/org/opensearch/ml/common/dataframe/ColumnValueReader.java
common/src/main/java/org/opensearch/ml/common/dataframe/LongValue.java
common/src/main/java/org/opensearch/ml/common/dataframe/ShortValue.java
common/src/test/java/org/opensearch/ml/common/dataframe/ColumnValueBuilderTest.java
common/src/test/java/org/opensearch/ml/common/dataframe/ColumnValueReaderTest.java
common/src/test/java/org/opensearch/ml/common/dataframe/ColumnValueTest.java
common/src/test/java/org/opensearch/ml/common/dataframe/LongValueTest.java
common/src/test/java/org/opensearch/ml/common/dataframe/ShortValueTest.java

Support short and long data type 
#128 

support short and long type in data frame

---

common/src/main/java/org/opensearch/ml/common/dataframe/DefaultDataFrame.java
common/src/main/java/org/opensearch/ml/common/parameter/AnomalyDetectionParams.java
common/src/main/java/org/opensearch/ml/common/parameter/FunctionName.java
common/src/main/java/org/opensearch/ml/common/parameter/MLOutputType.java
common/src/test/java/org/opensearch/ml/common/parameter/AnomalyDetectionParamsTest.java
gradle.properties
gradle/wrapper/gradle-wrapper.properties
gradlew
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/ad/AnomalyDetection.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/contants/TribuoOutputType.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ModelSerDeSer.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/TribuoUtil.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/ad/AnomalyDetectionTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/clustering/KMeansTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/regression/LinearRegressionTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Integrate tribuo anomaly detection algorithm which based on libSVM. Check this doc https://tribuo.org/learn/4.1/docs/features.html#anomaly-detection
#98 

integrate tribuo anomaly detection based on libSVM

---

common/build.gradle

From @jackiehanyang , SQL build will throw JarHell error
```
> Task :doctest:runRestTestCluster FAILED
Exec output and error:
| Output for ./bin/opensearch-plugin:warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
| -> Installing file:/home/runner/work/sql/sql/plugin/build/distributions/opensearch-sql-1.3.0.0-SNAPSHOT.zip
| -> Downloading file:/home/runner/work/sql/sql/plugin/build/distributions/opensearch-sql-1.3.0.0-SNAPSHOT.zip
| -> Failed installing file:/home/runner/work/sql/sql/plugin/build/distributions/opensearch-sql-1.3.0.0-SNAPSHOT.zip
| -> Rolling back file:/home/runner/work/sql/sql/plugin/build/distributions/opensearch-sql-1.3.0.0-SNAPSHOT.zip
| -> Rolled back …
```

fix jarhell error from SQL build

---

common/src/main/java/org/opensearch/ml/common/breaker/MLCircuitBreakerService.java
common/src/main/java/org/opensearch/ml/common/breaker/MemoryCircuitBreaker.java
common/src/main/java/org/opensearch/ml/common/parameter/AnomalyDetectionParams.java
common/src/main/java/org/opensearch/ml/common/parameter/FunctionName.java
docs/how-to-add-new-function.md
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/ad/AnomalyDetectionLibSVM.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/ad/AnomalyDetectionLibSVMTest.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java

Rename tribuo AD algorithm name.

rename tribuo AD algorithm name

---

common/src/main/java/org/opensearch/ml/common/parameter/MLTask.java

Fix the parse error for EpochMilli in Task APIs

fix EpochMilli parse error in MLTask

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/SearchModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java

ML indices are protected as system index in Security Plugin. This PR fixed no permission issue in security enabled cluster.

fix permission when accessing ML system indices

---

common/src/main/java/org/opensearch/ml/common/transport/task/MLTaskSearchAction.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/models/SearchTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/AbstractMLSearchAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLSearchModelAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLSearchTaskAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java

Add Search Task API and Refactor search actions and handlers.
More unit tests will be added in the next PRs.

Add Search Task API and Refactor search actions and handlers

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImpl.java

Signed-off-by: lai <57818076+wnbts@users.noreply.github.com>
This pr adds a minimum size to have at least that many top contributor candidates for further sorting.

add minimum top contributor candidate queue size

---

plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java

Fix update task semaphore.
Don't return task id for sync request. For sync request, the task is only cached in memory and will be removed once task done. Return task id for sync request may confuse user. We just need to return task id for async request.

fix update task semaphore; don't return task id for sync request

---

plugin/src/main/java/org/opensearch/ml/task/MLExecuteTaskRunner.java

Signed-off-by: lai <57818076+wnbts@users.noreply.github.com>
Executables are not running on the task thead pool like train/predict tasks and hang when implementation contains async callbacks.

use threadpool in execute task runner

---

client/build.gradle
client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
scripts/build.sh

Publish ml client to maven. 
Run `./gradlew publishAllPublicationsToStagingRepository` , then can see these files under `build/local-staging-repo`
```
.
└── org
└── opensearch
└── ml
└── opensearch-ml-client
├── 1.3.0.0-SNAPSHOT
│   ├── maven-metadata.xml
│   ├── maven-metadata.xml.md5
│   ├── maven-metadata.xml.sha1
│   ├── maven-metadata.xml.sha256
│   ├── maven-metadata.xml.sha512
│   ├── opensearch-ml-client-1.3.0.0-20220305.010646-1-javadoc.jar
│   ├── opensearch-ml-client-1.3.0.0-20220305.010646-1-javadoc.jar.md5
│   ├── opensearch-ml-client-1.3.0.0-20220305.010646-1-javadoc.jar.sha1
│   ├── opensearch-ml-client-1.3.0.0-20220305.010646-1-javadoc.jar.sha256
│   ├── opensearch-ml-client-1.3.0.0-20220305.010646-1-javadoc.jar.sha512
│   ├── …
```

publish ml client to maven

---

client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
common/src/main/java/org/opensearch/ml/common/parameter/AnomalyDetectionParams.java
common/src/main/java/org/opensearch/ml/common/parameter/FunctionName.java
common/src/main/java/org/opensearch/ml/common/parameter/KMeansParams.java
common/src/main/java/org/opensearch/ml/common/parameter/LinearRegressionParams.java
common/src/main/java/org/opensearch/ml/common/parameter/MLInput.java
common/src/main/java/org/opensearch/ml/common/parameter/MLModel.java
common/src/main/java/org/opensearch/ml/common/parameter/MLTask.java
common/src/test/java/org/opensearch/ml/common/dataframe/DataFrameBuilderTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/TribuoUtil.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImplTests.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/utils/TribuoUtilTest.java
plugin/src/test/java/org/opensearch/ml/action/training/TrainingITTests.java
plugin/src/test/java/org/opensearch/ml/indices/MLInputDatasetHandlerTests.java
plugin/src/test/java/org/opensearch/ml/stats/MLStatsTests.java

1. Don't return verbose error message when use input invalid enum.
2. Fix some code style
Test:
```
POST /_plugins/_ml/_train/kmeans
{
"k": 2,
"iterations": 10,
"distance_type": "SINE"
},
"input_query": {
"query": {
"bool": {
"filter": [
{
"range": {
"k1": {
"gte": 0
}
}
}
]
}
},
"size": 10
},
"input_index": [
"test_data"
]
}
{
"error": {
{
"type": "illegal_argument_exception",
"reason": "Wrong distance type"
}
],
"type": "illegal_argument_exception",
"reason": "Wrong distance type"
},
"status": 400
}
```
Close #163 
For more information on following Developer Certificate of Origin and signing off …

fix verbose error message thrown by invalid enum

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetModelActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelActionIT.java
plugin/src/test/java/org/opensearch/ml/utils/TestData.java

Add integration tests for all model APIs. Rebased on PR 167.

Add integ tests for model APIs

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLTrainAndPredictIT.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

Add security IT.
`./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Dhttps=true -Duser=admin -Dpassword=admin --tests="org.opensearch.ml.rest.SecureMLRestIT"`

add security IT

---

common/src/main/java/org/opensearch/ml/common/parameter/AnomalyDetectionParams.java
common/src/main/java/org/opensearch/ml/common/parameter/BatchRCFParams.java
common/src/main/java/org/opensearch/ml/common/parameter/FitRCFParams.java
common/src/main/java/org/opensearch/ml/common/parameter/KMeansParams.java
common/src/main/java/org/opensearch/ml/common/parameter/LinearRegressionParams.java
common/src/main/java/org/opensearch/ml/common/parameter/LocalSampleCalculatorInput.java
common/src/main/java/org/opensearch/ml/common/parameter/MLModel.java
common/src/main/java/org/opensearch/ml/common/parameter/SampleAlgoParams.java
common/src/test/java/org/opensearch/ml/common/TestHelper.java
common/src/test/java/org/opensearch/ml/common/parameter/KMeansParamsTest.java
common/src/test/java/org/opensearch/ml/common/parameter/LinearRegressionParamsTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizationInput.java

When pass non-integer value like Double, OpenSearch parser will parse value to Double, then convert it into int. This PR adds more strict checking, will throw exception if pass double value to int field.
Close #164 https://github.com/opensearch-project/OpenSearch/issues/2375

more strict check on input parameters by applying non-coerce mode

---

plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

- Fix no permission to create model/task index bug. ML model and task index are system index. Need to stash thread context to create.
- Add security IT for train/predict API

fix no permission to create model/task index bug;add security IT for train/predict API

---

common/src/main/java/org/opensearch/ml/common/parameter/FunctionName.java

When test today's tarball on multi-node cluster, we see `failed to parse ActionRequest into MLTrainingTaskRequest` error
```
POST _plugins/_ppl
{
"query": "source=nyc_taxi | fields timestamp,value | ad time_field='timestamp'"
}
{
"error": {
"reason": "There was internal problem at backend",
"details": "failed to parse ActionRequest into MLTrainingTaskRequest",
"type": "UncheckedIOException"
},
"status": 503
}
```
SQL is using client from main branch, so When parse action request, it will try to map `BATCh_RCF` to the 8th enum, but `FunctionName` in 1.3 only have 7 enum items. So will fail to parse. This PR moves `ANOMALY_LOCALIZATION` to the last position to avoid such issue in future.
```
public enum FunctionName {
LINEAR_REGRESSION,
KMEANS, …
```

move anomaly localization to the last position to avoid BWC issue

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteTaskActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetTaskActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchTaskActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchTaskActionTests.java

Do not exclude tests for restful actions and ensure coverage is 80%. Added IT for each Model/Task API. More tests can be added in future PRs if necessary. 

add more UT and IT for rest actions

---

.github/workflows/CI-workflow.yml

use 1.3.0 docker to run CI

---

release-notes/opensearch-ml-common.release-notes-1.3.0.0.md

Fix the name of the release note file.

rename the release note file

---

client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/clustering/KMeans.java
plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java
plugin/src/test/java/org/opensearch/ml/action/stats/MLStatsNodeResponseTests.java
plugin/src/test/java/org/opensearch/ml/action/stats/MLStatsNodesResponseTests.java
plugin/src/test/java/org/opensearch/ml/action/training/TrainingITTests.java
plugin/src/test/java/org/opensearch/ml/action/trainpredict/TrainAndPredictITTests.java
plugin/src/test/java/org/opensearch/ml/params/MLInputTests.java
plugin/src/test/java/org/opensearch/ml/utils/IntegTestUtils.java
plugin/src/test/java/org/opensearch/ml/utils/TestData.java

add more IT for train/predict and train&predict action

add more IT for train/predict and train&predict action

---

.github/workflows/CI-workflow.yml
plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java

1. Add more unit tests coverage for task/model rest actions. 
2. Remove support for JDK 8 for 2.0 into Main branch.

add more UT for model/task rest actions, remove support for JDK8

---

plugin/build.gradle

Signed-off-by: Amit Galitzky <amgalitz@amazon.com>
Removes unnecessary `-oss` flavor from `build.gradle`. OpenSearch exported `oss` flavor flag until now (all versions up to 1.3.0) and will remove it after. https://github.com/opensearch-project/OpenSearch/pull/1751

Remove oss flavor

---

build.gradle
scripts/build.sh

Add support for -Dbuild.version_qualifier=alpha1.
Part of https://github.com/opensearch-project/opensearch-build/issues/1632.

Add support for -Dbuild.version_qualifier in ml common

---

.github/workflows/CI-workflow.yml
build.gradle
client/build.gradle
common/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle

To Support build ML-Common using JDK 17, we also need to upgrade the following dependencies.
java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor  -> upgrade to "io.freefair.lombok" version "6.4.1"
opensearch-ml-algorithms:test errors -> upgrade to name: 'mockito-core', version: '4.4.0'
For be consistent with all plugins -> sourceCompatibility = targetCompatibility = JavaVersion.VERSION_11

add support for JDK 17

---

.github/workflows/CI-workflow.yml
build.gradle
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java
plugin/src/test/java/org/opensearch/ml/action/training/TrainingITTests.java
plugin/src/test/java/org/opensearch/ml/action/trainpredict/TrainAndPredictITTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchTaskActionIT.java
scripts/build.sh

Add qualifier to version
###
https://github.com/opensearch-project/ml-commons/issues/258

add qualifier to version

---

.github/workflows/CI-workflow.yml

Remove JDK 14 per request in https://github.com/opensearch-project/ml-commons/issues/266 and https://github.com/opensearch-project/opensearch-plugins/issues/132

drop support for JDK 14

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/GetModelITTests.java
plugin/src/test/java/org/opensearch/ml/action/models/GetModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/DeleteTaskTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/GetTaskTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/SearchTaskTransportActionTests.java

Add UT/IT Coverage for action/models and action/tasks.

add more UT coverage for model/task transport actions

---

build.gradle

Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Remove additional vars in build.gradle that are not used
#258

Remove additional vars in build.gradle that are not used

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/stats/StatNames.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

Add circuit breaker trigger count stat.

add circuit breaker trigger count stat

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Add more test to improve coverage of abstract search action

add more test to improve coverage of abstract search action

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/RestMLExecuteActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Add UT for RestMLExecuteAction, and remove it out from the jacoco exclusive list.

Add UT for ml rest execute action

---

common/src/main/java/org/opensearch/ml/common/transport/MLTaskRequest.java
common/src/main/java/org/opensearch/ml/common/transport/execute/MLExecuteTaskRequest.java
common/src/main/java/org/opensearch/ml/common/transport/prediction/MLPredictionTaskRequest.java
common/src/main/java/org/opensearch/ml/common/transport/training/MLTrainingTaskRequest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/task/MLExecuteTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/task/MLExecuteTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

1. support dispatching execute task;
2. don't dispatch ML task again
3. add request id to track the request easily

support dispatching execute task; don't dispatch ML task again

---

plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java

We found security test `testReadOnlyUser_CanSearchModels` failed. Debug locally and found ML model index mapping is wrong: filed `algorithm` was set as `text` type
So when search with this query, will return empty result.
```
POST /_plugins/_ml/models/_search
{
"query": {
"bool": {
"filter": [
{
"term": {
"algorithm": "KMEANS"
}
}
]
}
}
}
```
This PR fix this bug by setting mapping in create index request. Will backport this to 1.x . …

create model/task index with correct mapping

---

.github/workflows/CI-workflow.yml

Re-enable docker image tests for 2.0.

reenable docker image tests

---

.github/workflows/CI-workflow.yml

bump version to 1.3.2 in CI workflow

bump version to 1.3.2 in CI workflow

---

ml-algorithms/build.gradle

[Backport to 1.3] bump tribuo version to 4.2.1

---

ml-algorithms/build.gradle

[Backport to 1.x] bump tribuo version to 4.2.1

---

build.gradle

Remove the rc1 qualifier in main.

Remove rc1 qualifier in main branch

---

plugin/build.gradle
scripts/build.sh

Follow https://github.com/opensearch-project/opensearch-build/issues/1916 and use custom plugin to publish zips to maven.
[306](https://github.com/opensearch-project/ml-commons/issues/306)
Run ./gradlew publishPluginZipPublicationToZipStagingRepository, and identified the local-staging-repo directory created.
tree ./
./
├── libs
│   ├── opensearch-ml-2.0.0.0-SNAPSHOT.jar
│   └── opensearch-ml-2.0.0.0-rc1-SNAPSHOT.jar
├── local-staging-repo
│   └── org
│       └── opensearch
│           └── plugin
│               └── opensearch-ml-plugin
│                   ├── 2.0.0.0-SNAPSHOT
│                   │   ├── maven-metadata.xml
│                   │   ├── maven-metadata.xml.md5
│                   │   ├── maven-metadata.xml.sha1
│   …

Use custom plugin to publish zips to maven

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/main/java/org/opensearch/ml/utils/MLNodeUtils.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskDispatcherTests.java
plugin/src/test/java/org/opensearch/ml/utils/MLNodeUtilsTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

We plan to support dynamic role in OpenSearch. Refer to this PR https://github.com/opensearch-project/OpenSearch/pull/3436 and issue https://github.com/opensearch-project/OpenSearch/issues/2877
This PR is to change the task dispatcher to support ML node. Will check if cluster has any node with "ml" role first. If yes, will dispatch ML task to "ml" nodes; otherwise will dispatch to data nodes.
close #79

dispatch ML task to ML node first

---

.github/workflows/CI-workflow.yml
build.gradle

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 1.3.4.
Part of https://github.com/opensearch-project/opensearch-build/issues/2205

Incremented version to 1.3.4.

---

build.gradle

Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/ml-commons/pull/2
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/ml-commons/issues/357 …

[backport 1.3]Staging for version increment automation

---

plugin/build.gradle

We used version of jackson for `jackson-databind`. This PR fixed that to use same `jackson-databind` version as OpenSearch core.

fix jackson databind version: use same version as OpenSearch core

---

plugin/build.gradle

fix jackson databind version: use same version as OpenSearch core

[Backport 1.3] fix jackson databind version: use same version as OpenSearch core

---

.github/workflows/CI-workflow.yml
build.gradle
plugin/build.gradle

fix jackson databind version: use same version as OpenSearch core

[Backport 1.x] fix jackson databind version: use same version as OpenSearch core

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
common/src/main/java/org/opensearch/ml/common/input/parameter/clustering/RCFSummarizeParams.java
common/src/test/java/org/opensearch/ml/common/input/parameter/clustering/RCFSummarizeParamsTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/clustering/KMeans.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/clustering/RCFSummarize.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/clustering/SerializableSummary.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/MathUtil.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/TribuoUtil.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/clustering/RCFSummarizeTest.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Adding RCFSummarize clustering algo into ml-commons
Issue Link here: https://github.com/opensearch-project/ml-commons/issues/356 
- [* ] New functionality includes testing.
- [* ] All tests pass
- [* ] New functionality has been documented.
- [* ] New functionality has javadoc added
- [* ] Commits are signed per the DCO using --signoff 

Add clustering function - RCFSummarize

---

client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/MLTask.java
common/src/test/java/org/opensearch/ml/common/MLModelTests.java
common/src/test/java/org/opensearch/ml/common/transport/model/MLModelGetResponseTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndex.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLSearchModelAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLSearchTaskAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLStatsAction.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/indices/MLIndicesHandlerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLStatsActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/IntegTestUtils.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

ML model content stored as text by mistake in index. This PR fixed index mapping and store model content as binary.

fix index mapping

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
common/src/main/java/org/opensearch/ml/common/dataframe/DataFrame.java
common/src/main/java/org/opensearch/ml/common/dataframe/DefaultDataFrame.java
common/src/main/java/org/opensearch/ml/common/input/parameter/regression/LogisticRegressionParams.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/regression/LogisticRegression.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/contants/TribuoOutputType.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/TribuoUtil.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/regression/LogisticRegressionTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/helper/LogisticRegressionHelper.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java
plugin/src/test/java/org/opensearch/ml/action/training/TrainingITTests.java

Add Tribuo Logistic Regression into ML-Common.
UTs and ITs of logistic regression are included in the PR. Addressed comments from the previous PR.
https://github.com/opensearch-project/ml-commons/issues/318

Add Logistic Regression algorithm

---

common/src/main/java/org/opensearch/ml/common/input/parameter/regression/LinearRegressionParams.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/regression/LinearRegression.java

Increase the number of iteration for epochs to improve convergence of linear regression. 

increase the default epochs to 1000 for linear regression

---

plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java

ForkJoinPool problem is fixed. Reenabling the prediction tests for KMeans. 
https://github.com/oracle/tribuo/issues/223

reenable KMEANS predict IT tests

---

build.gradle

Change back to OpenSearch version 2.3 for 2.3 branch.

bump to version 2.3

---

README.md

Signed-off-by: cwillum <cwmmoore@amazon.com>
Replaced the link to the Forum discussion in the README.md file so that it points to the OpenSearch forum rather than the defunct Open Distro forum.
This fixes the issue for the ML Commons plugin in [#921](https://github.com/opensearch-project/documentation-website/issues/921).

Replace Forum link in ML Commons plugin README.md

---

plugin/src/main/java/org/opensearch/ml/rest/AbstractMLSearchAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/utils/RestActionUtilsTests.java

"_source field" to be recognized in search model api.
This PR fixes the bug reported in the issue https://github.com/opensearch-project/ml-commons/issues/419
Test api request and response with '_source' field:
Without specifying '_source' field:
https://github.com/opensearch-project/ml-commons/issues/419

Bug fix: filter _source field in search model api

---

.github/workflows/CI-workflow.yml
build.gradle
plugin/build.gradle

Increment version to 1.3.6 and remove jackson force version to avoid build Conflicts.

increment version to 1.3.6 and remove jackson force version

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java

Delete all chunks in delete Model API for custom models.
DELETE _plugins/_ml/models/"model-ids"
{
"_index" : ".plugins-ml-model",
"_id" : "x95LqoMBr6prntZN5AQJ",
"_version" : 2,
"result" : "deleted",
"_shards" : {
"total" : 2,
"successful" : 1,
"failed" : 0
},
"_seq_no" : 37,
"_primary_term" : 7
}

update delete model TransportAction to support custom model

---

plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileNodeRequest.java
plugin/src/main/java/org/opensearch/ml/action/stats/MLStatsNodeRequest.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetModelActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLStatsActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLTrainAndPredictIT.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Migrate client transports to Apache HttpClient / Core 5.x. Also removed deprecated packages and migrated them to active substitutes.
1. Closes #460
2. Previously ml-commons will fail in CI workflow because OpenSearch 3.0 has many breaking changes, including migration to the Apache HttpClient / Core 5.x . So we did this fix to unblock infra team's CI workflow.

Migrate client transports to Apache HttpClient / Core 5.x

---

ml-algorithms/build.gradle
plugin/build.gradle

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
Backport of https://github.com/opensearch-project/ml-commons/pull/487 to `1.x`
Closes https://github.com/opensearch-project/ml-commons/issues/485

[Backport] [1.x] Address CVE-2022-42889 by updating commons-text (#487)

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java

* update delete model TransportAction to support custom model
Back ported from custom model branch. Also, added a few lines to delete custom model chunks if the model metaData is not found.

[Backport] update delete model TransportAction to support custom model

---

.github/workflows/CI-workflow.yml
plugin/src/test/java/org/opensearch/ml/action/custom_model/CustomModelITTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCustomModelActionIT.java

Found several issues when run on windows
1. `CustomModelITTests#testCustomModelWorkflow` will fail to clean up local file cache.  Test code run successfully, but test framework failed to cleanup temp local files.
```
at __randomizedtesting.SeedInfo.seed([D97C315DD114CE48]:0)
at org.apache.lucene.util.IOUtils.rm(IOUtils.java:341)
at org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:209)
at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at …
```

test windows build

---

ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForestTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java

Increase the test coverages by 5% each in ml-algorithm code and branches, to reach the 90% and 80% bar.

add more test coverage to ModelHelper and FileUtils

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java

adding unit tests to TransportUploadModelAction to improve test coverage

add test coverage to transportUploadModelAction

---

common/src/main/java/org/opensearch/ml/common/transport/forward/MLForwardAction.java
common/src/main/java/org/opensearch/ml/common/transport/sync/MLSyncUpAction.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/FileUtils.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/unload/TransportUnloadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/upload/TransportUploadModelAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java

Address security review comments by adding trusted URL regex, so user can set their own trusted URL regex to avoid uploading model from untrusted source.

add trusted URL regex

---

ml-algorithms/build.gradle
plugin/build.gradle

Back port the commons-text upgrading to 1.10 to fix the CVE. 
This commit is tested successfully with 1.3.6 artifacts and dependencies. The CI build failure is because of the 1.3.7 dependencies not ready.

backport: Address CVE-2022-42889 by updating commons-text

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/test/java/org/opensearch/ml/utils/IndexUtilsTests.java

This PR should change the max_ml_task_per_node into dynamic settings
Previously the max_ml_task_per_node is static set in MLTaskManager class, which is hard to change. Now we can easily change this parameter through API.

change the max_ml_task_per_node into dynamic settings

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

Adds more security IT test for upload and load APIs.

Adds security IT for new upload and load APIs

---

release-notes/opensearch-ml-common.release-notes-2.4.0.0.md

add ml-commons release notes for 2.4

add ml-commons release notes for 2.4

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

When disk circuit breaker is open, the upload model task will never completed/failed.
The original design of `String errorMsg = checkAndAddRunningTask(mlTask, maxUploadTasksPerNode);` will never throw exceptions, will throw exception by checking `errorMsg`. Now circuit breaker will throw limit exceed exception inside `checkAndAddRunningTask`, so we should move this method inside the try block.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-cert …

fix running tasks when circuit breaker is open

---

plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java

When upgrade from older version, will check if need to upgrade model/task index mapping. As model/task index is system index, so we need to stash thread context first, otherwise it throws no permission exception.
Error log
```
OpenSearchSecurityException[no permissions for [] and User [name=admin123, backend_roles=[], requestedTenant=]]
at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:363)
at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:149)
at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:217)
at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:78)
at …
```

fix no permission bug when update index mapping

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

Need to wait for upload task to complete before running load model in security tests.
The tests are running successful against the 2.4 release candidate. Launched all integration tests against a local cluster and run tests with security. 
./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Dhttps=true -Duser=admin -Dpassword=admin
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#devel …

wait for upload task to complete in security tests

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
common/src/main/java/org/opensearch/ml/common/input/Constants.java
common/src/main/java/org/opensearch/ml/common/input/InputHelper.java

* Support the generic ml ppl command.
Signed-off-by: Jing Zhang <jngz@amazon.com>
* Change algorithm name ad to rcf.
Signed-off-by: Jing Zhang <jngz@amazon.com>
* Rename the method from execute to run. Add InputHelper to handle arguments.
Signed-off-by: Jing Zhang <jngz@amazon.com>
* Add header for InputHelper.
Signed-off-by: Jing Zhang <jngz@amazon.com>
* Move all constants to the common.
Signed-off-by: Jing Zhang <jngz@amazon.com>
Signed-off-by: Jing Zhang <jngz@amazon.com>
This PR is a partial forwarding of port changes in branch 2.x ([commit #484](https://github.com/opensearch-project/ml-commons/commit/d5f51ae3a7d46af469ee373812bd6d6147e47d49)) to main branch.
This PR partially resolves …

Forwarding port changes in 2.4 to main branch (Support the generic ml ppl command) 

---

common/src/main/java/org/opensearch/ml/common/transport/load/LoadModelResponse.java
common/src/main/java/org/opensearch/ml/common/transport/upload/MLUploadInput.java
common/src/main/java/org/opensearch/ml/common/transport/upload/UploadModelResponse.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/clustering/KMeans.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/FileUtils.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/cluster/MLCommonsClusterManagerEventListener.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/profile/MLModelProfile.java
plugin/src/main/java/org/opensearch/ml/profile/MLPredictRequestStats.java
plugin/src/main/java/org/opensearch/ml/task/MLExecuteTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskCache.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

* refactor model cache and thread pool
* address comments
This PR is a partial forwarding of port changes in branch 2.x ([commit #496](https://github.com/opensearch-project/ml-commons/commit/a246eba61bad32f41e1ec85892e3f81bee1783e3)) to main branch.
For more information on following Developer …

Forwarding port changes in 2.4 to main branch (refactor model cache and thread pool)

---

plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java

If reload a loaded model on single node cluster, the load model task status will always show as RUNNING. The reason is the task not removed from cache when update task, so it could be updated as RUNNING after completed.

fix running task when reload loaded model on single node cluster

---

plugin/build.gradle

Resolve dependency version conflict in build file
Previously build will fail due to com.google.code.gson package version conflict

Resolve dependency version conflict in build file

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java

* update delete model TransportAction to support custom model
This PR is a partial forwarding of port changes in branch 2.x ([commit #497](https://github.com/opensearch-project/ml-commons/commit/15a3530ecb13916bcba895ab828a040cbb38c5d6)) to main branch. …

Forwarding port changes in 2.4 to main branch ([Backport] update delete model TransportAction to support custom model)

---

common/src/main/java/org/opensearch/ml/common/breaker/DiskCircuitBreaker.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModel.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/custom_model/CustomModelITTests.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCustomModelActionIT.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestData.java

* add integ tests for new APIs: upload/load/unload
* run custom model actions in one test to mitigate resouce usage
* fix disk circuit breaker
* add integ test for upload/load/unload actions
This PR is a partial forwarding of port changes in branch 2.x ([commit #500](https://github.com/opensearch-project/ml-commons/commit/819418cd9baa5061e128015ade3dc1495497caaf)) to main branch.
This PR partially resolves [#553](https://github.com/opensearch-project/ml-commons/issues/553) and [OpenSearch-SQL …

Forwarding port changes in 2.4 to main branch (add integ tests for new APIs: upload/load/unload)

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #503](https://github.com/opensearch-project/ml-commons/commit/8c8e2a595e84b374c08e45df255dfe8b63b9b8ea)) to main branch.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer …

Forwarding port changes in 2.4 to main branch (add custom model size limit)

---

.github/workflows/CI-workflow.yml
plugin/src/test/java/org/opensearch/ml/action/custom_model/CustomModelITTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCustomModelActionIT.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #504](https://github.com/opensearch-project/ml-commons/commit/9ebd2e6fad884829781342a79157a9eba9ca5a47)) to main branch. …

Forwarding port changes in 2.4 to main branch (add windows build in CI workflow)

---

plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploader.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploaderTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCustomModelChunkActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUploadModelChunkActionTests.java

This PR fixes the bug to change the model state to 'UPLOADED" when all the chunks are successfully uploaded. Previously, the model was still on "UPLOADING" state even when all the chunks are uploaded. 

change model state to UPLOADED when all chunks uploaded

---

common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaAction.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaInput.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaRequest.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaResponse.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLUploadModelChunkAction.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLUploadModelChunkInput.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLUploadModelChunkRequest.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLUploadModelChunkResponse.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLUploadModelChunkInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLUploadModelChunkRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLUploadModelChunkResponseTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploader.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelMetaCreate.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/TransportCreateModelMetaAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/TransportUploadModelChunkAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCreateModelMetaAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUploadModelChunkAction.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploaderTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelMetaCreateTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportCreateModelMetaActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportUploadModelChunkActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateModelMetaActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUploadModelChunkActionTests.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #495](https://github.com/opensearch-project/ml-commons/commit/711031da6e23c0b3d9c12ce2c8ecd169dc038d0d)) to main branch.

Forwarding port changes in 2.4 to main branch (changes to custom model chunk upload api)

---

ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForestTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #510](https://github.com/opensearch-project/ml-commons/commit/fb07dcb679b080bba9cd3c386bee2c4835d6e36e)) to main branch.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer …

Forwarding port changes in 2.4 to main branch (add more test coverage to ModelHelper and FileUtils)

---

ml-algorithms/build.gradle
plugin/build.gradle

[Backport to 1.3] force protobuf-java version as 3.21.9

---

ml-algorithms/build.gradle
plugin/build.gradle

force protobuf-java version as 3.21.9

force protobuf-java version as 3.21.9

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #511](https://github.com/opensearch-project/ml-commons/commit/7d8a311fbeb8beae05170103a82acfd58da07dce)) to main branch.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#d …

Forwarding port changes in 2.4 to main branch (add test coverage to transportUploadModelAction)

---

build.gradle
plugin/build.gradle

fix junit version

---

common/src/main/java/org/opensearch/ml/common/input/parameter/regression/LogisticRegressionParams.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensor.java
common/src/test/java/org/opensearch/ml/common/input/parameter/regression/LogisticRegressionParamsTest.java
common/src/test/java/org/opensearch/ml/common/output/model/ModelTensorTest.java
common/src/test/java/org/opensearch/ml/common/output/model/ModelTensorsTest.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #517](https://github.com/opensearch-project/ml-commons/commit/65343d7305527fc040fd96b2c98971ebd5a0f104)) to main branch.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/mai …

Forwarding port changes in 2.4 to main branch (Add more unit test coverage to output.model and input.parameter in commons pakage)

---

common/src/main/java/org/opensearch/ml/common/transport/forward/MLForwardResponse.java
common/src/main/java/org/opensearch/ml/common/transport/sync/MLSyncUpResponse.java
common/src/test/java/org/opensearch/ml/common/transport/forward/MLForwardInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/forward/MLForwardRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/forward/MLForwardResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelNodeResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelNodesRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelNodesResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/MLLoadModelRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpNodeRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpNodeResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpNodesResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/training/MLTrainingTaskRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelNodeResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelNodesRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelNodesResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadModelRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload/UploadModelResponseTest.java

* add test coverage to common package
* improve unit test coverage for forward, load, unload and upload class
* improve unit test coverage for sync, training, unload and load class
* code improvement after review
This PR is a partial forwarding of port changes in branch 2.x ([commit #514](https://github.com/opensearch-project/ml-commons/commit/6f47975b098aa65a78a5aff90caf1e478babab3 …

Forwarding port changes in 2.4 to main branch (Add test coverage to common package)

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateModelMetaActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCustomModelChunkActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLLoadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLProfileActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUnloadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUploadModelActionTests.java

* add unit tests to improve test coverage in plugin package
This PR is a partial forwarding of port changes in branch 2.x ([commit #516](https://github.com/opensearch-project/ml-commons/commit/dee3cdfd21536a035ab74069eaad7ebbf0081892)) to main branch. …

Forwarding port changes in 2.4 to main branch (add unit tests to improve test coverage in plugin package)

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/test/java/org/opensearch/ml/utils/IndexUtilsTests.java

* change the max_ml_task_per_node into dynamic settings
* Trying to bypassing the flaky test
Signed-off-by: Sicheng Song <114637679+b4sjoo@users.noreply.github.com
This PR is a partial forwarding of port changes in branch 2.x ([commit #530](https://github.com/opensearch-project/ml-commons/commit/10a1af06a89094e70677410f8c1b47d2ce372dd4)) to main branch.
For more information on …

Forwarding port changes in 2.4 to main branch (change the max_ml_task_per_node into dynamic settings)

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #529](https://github.com/opensearch-project/ml-commons/commit/f0cf53f8f9c8e91a7e423817e7b879410ca536fb)) to main branch.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-o …

Forwarding port changes in 2.4 to main branch (Adds security IT for new upload and load APIs)

---

plugin/build.gradle

This PR is a partial forwarding of port changes in branch 2.x ([commit #536](https://github.com/opensearch-project/ml-commons/commit/77666469faa0e8dd9c13e2dc1a927d1086b3dfca)) to main branch. …

Forwarding port changes in 2.4 to main branch (test coverage ratio changes for build.gradlew in plugin package)

---

release-notes/opensearch-ml-common.release-notes-2.4.0.0.md

This PR is a partial forwarding of port changes in branch 2.x ([commit #538](https://github.com/opensearch-project/ml-commons/commit/1772dd649514842c8277bb04c4e82f63d25c2914)) to main branch.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certific …

Forwarding port changes in 2.4 to main branch (add ml-commons release notes for 2.4)

---

release-notes/opensearch-ml-common.release-notes-2.4.0.0.md

This PR is a partial forwarding of port changes in branch 2.x ([commit #540](https://github.com/opensearch-project/ml-commons/commit/d5f50b923f272bdae7758b89ca25f6af8504ea96)) to main branch.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/mai …

Forwarding port changes in 2.4 to main branch (move custom model related PRs to experimental features)

---

plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #545](https://github.com/opensearch-project/ml-commons/commit/5b42aec414be10ab618154411e8780d60737e998)) to main branch.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/mai …

Forwarding port changes in 2.4 to main branch (fix no permission bug when update index mapping)

---

release-notes/opensearch-ml-common.release-notes-2.4.0.0.md

This PR is a partial forwarding of port changes in branch 2.x ([commit #548](https://github.com/opensearch-project/ml-commons/commit/4b8d1ffe91bff7d9b0fd047a4cdb9888b1cea37a)) to main branch. …

Forwarding port changes in 2.4 to main branch (add bug fix changes to release notes)

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

This PR is a partial forwarding of port changes in branch 2.x ([commit #551](https://github.com/opensearch-project/ml-commons/commit/20c067b72bba3a762a9e1b5c00f7f8fb9ed35e2a)) to main branch.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-o …

Forwarding port changes in 2.4 to main branch (wait for upload task to complete in security tests)

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/action/unload/TransportUnloadModelActionTests.java

* unit tests coverage for load/unload/syncup
This PR is a partial forwarding of port changes in branch 2.x ([commit #592](https://github.com/opensearch-project/ml-commons/commit/231499d2a2050c2a80c93929339d7a83adbecab4)) to main branch.

Forwarding port changes in 2.4 to main branch (unit tests coverage for load/unload/syncup)

---

.gitignore
client/build.gradle
common/build.gradle
common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/model/TextEmbeddingModelConfig.java
common/src/test/java/org/opensearch/ml/common/model/TextEmbeddingModelConfigTests.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaRequestTest.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/HuggingfaceTextEmbeddingTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/HuggingfaceTextEmbeddingTranslatorFactory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/ONNXSentenceTransformerTextEmbeddingTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelMetaCreateTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportCreateModelMetaActionTests.java

Add more parameters for text embedding model
1. model max length: how many tokens the model can support at most
2. pooling method: we only support mean pooling method in 2.4 release, this PR add cls pooling support
3. normalize result: boolean, will normalize result if this is true.

add more parameters for text embedding model

---

plugin/build.gradle

jackson-databind and jackson-annotations were added as api dependencies in server of opensearch core. The security plugin now gets these dependencies transitively and does not need direct dependencies on the jars.
PR in core where the dependencies are added: https://github.com/opensearch-project/OpenSearch/pull/5366
Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)
Maintenance
This PR will resolve https://github.com/opensearch-project/ml-commons/issues/634 …

Remove jackson-databind and jackson-annotations dependencies now coming from core

---

common/src/main/java/org/opensearch/ml/common/MLTask.java
common/src/test/java/org/opensearch/ml/common/MLTaskTests.java
common/src/test/java/org/opensearch/ml/common/transport/forward/MLForwardInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/forward/MLForwardRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/load/LoadModelNodesRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/task/MLTaskGetResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/upload/TransportUploadModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/profile/MLModelProfile.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileNodeResponseTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileResponseTests.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLProfileActionTests.java

1. ML task may run on multiple nodes. We save all worker nodes as String in ML task doc which is not easy to use. This PR changed worker nodes in MLTask as List<String>
2. Add target worker node to cache

change task worker node to list; add target worker node to cache

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/test/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeActionTests.java

For some edge case like worker node crashed, the ML task may stay in the cache forever. This PR fixed that issue by adding timeout setting (default 10 minutes). Sync up job will check ML task in cache expired or not. If expired, will reset task and model status and remove task from cache to avoid memory leak. 
Also fixed one issue for reloading a model which already loaded on some node. For example,  user can load model to node1, then target worker nodes is `[ node1 ]`, after model loaded, user may load model again on node2. Then target worker node becomes `[ node2 ]`. This is not expected. This PR checks if the new target worker nodes include all old loaded nodes (for this example, it's `[ node 1]`). If not, will throw exception. So if user …

add ML task timeout setting and clean up expired tasks from cache

---

MAINTAINERS.md

Updated MAINTAINERS.md to match opensearch-project recommended format.

Updated MAINTAINERS.md format

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/model/TextEmbeddingModelConfig.java
common/src/test/java/org/opensearch/ml/common/model/TextEmbeddingModelConfigTests.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaRequestTest.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/HuggingfaceTextEmbeddingTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/HuggingfaceTextEmbeddingTranslatorFactory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/ONNXSentenceTransformerTextEmbeddingTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelMetaCreateTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportCreateModelMetaActionTests.java

1. Add more pooling method
2. Refactor to align with DJL code: change poolingMethod to poolingMode, use string in translator. 

add more pooling method and refactor

---

common/src/main/java/org/opensearch/ml/common/transport/upload/MLUploadInput.java
ml-algorithms/build.gradle
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/main/java/org/opensearch/ml/action/upload/TransportUploadModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

We need security review model first. We don't have enough time for that. So disable prebuilt model for 2.5. 

disable prebuilt model

---

common/src/main/java/org/opensearch/ml/common/transport/upload/MLUploadInput.java
ml-algorithms/build.gradle
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/upload/TransportUploadModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

This reverts commit 26435dee2f5fb21b6c47bdb8d1f1e54312e76225.
Jackson is no longer in core, so reverting changes made for https://github.com/opensearch-project/ml-commons/issues/634

Revert "Remove jackson-databind and jackson-annotations dependencies now coming from core (#652)"

---

plugin/build.gradle

Backport PR from https://github.com/opensearch-project/ml-commons/pull/652

[backport 2.5] Revert "Remove jackson-databind and jackson-annotation s dependencies now coming from core"

---

plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java

It's not recommended to run ML tasks on data node. This PR changes only run on ml node setting default value to true. So ML tasks will only run on ML node by default. 

change only run on ml node setting default value to true

---

plugin/src/test/java/org/opensearch/ml/bwc/MLCommonsBackwardsCompatibilityIT.java
plugin/src/test/java/org/opensearch/ml/bwc/MLCommonsBackwardsCompatibilityRestTestCase.java

Change the inheritance of the `MLCommonsBackwardsCompatibilityIT.java` to be extended from `MLCommonsBackwardsCompatibilityRestTestCase.java`, which previously from `MLCommonsRestTestCase.java`

Change the inheritance of the BWC test file

---

plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java

tune error message for no ML node case

tune error message for no ML node case

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/bwc/MLCommonsBackwardsCompatibilityIT.java

Description
This PR will fix the bwc test failure when incrementing to version 2.6.0.

fix bwc bug when incrementing to OS 2.6.0

---

docs/model_serving_framework/GPU_support.md

Signed-off-by: Jing Zhang <jngz@amazon.com>
Update gpu doc with docker test.

Update gpu doc with docker test.

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/transport/sync/MLSyncUpNodeResponse.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpNodeResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelMetaCreate.java
plugin/src/main/java/org/opensearch/ml/cluster/MLCommonsClusterManagerEventListener.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java

When load model, there are some edge cases the model state is not accurate:
1. Node crashed when loading model, then the model may stay on LOADING state forever. Should change it to LOAD_FAILED.
2. After model loaded, some ML node crashed, then the model will still stay on LOADED state. Should change it to PARTIALLY_LOADED state
3. After model loaded, all ML nodes crashed or cluster restart, then the model will still stay on LOADED state. Should change it to LOAD_FAILED state.
This PR also adds two new fields in model index: 
1. `planning_worker_node_count`: plan to deploy model to how many nodes 
2. `current_worker_node_count`: model is running on how many nodes
close https://github.com/opensearch-project/ml-commons/issues/703
By submitting …

refresh model load state in sync up cron job

---

docs/model_serving_framework/text_embedding_model_examples.md
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java

Add text embedding API example doc

add text embedding API example doc

---

docs/model_serving_framework/text_embedding_model_examples.md

Fix profile API in example doc

fix profile API in example doc

---

plugin/src/main/java/org/opensearch/ml/action/profile/MLProfileModelResponse.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLProfileAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileModelResponseTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLProfileActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

This change is to add model centric result for profile API, so that user can fetch either node centric result or model centric result or both.
https://github.com/opensearch-project/ml-commons/issues/646

Enhance profile API to add model centric result controlled by view parameter

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelActionTests.java

add planning work nodes to model

---

plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java

skip running syncup job if no model index

---

common/src/main/java/org/opensearch/ml/common/model/TextEmbeddingModelConfig.java
common/src/test/java/org/opensearch/ml/common/model/TextEmbeddingModelConfigTests.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadInputTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/HuggingfaceTextEmbeddingTranslatorFactory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/ONNXSentenceTransformerTextEmbeddingTranslator.java

tune model config: change pooling mode to optional

---

build.gradle
common/src/main/java/org/opensearch/ml/common/model/TextEmbeddingModelConfig.java
common/src/main/java/org/opensearch/ml/common/transport/upload/MLUploadInput.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

As we have published prebuilt models to OpeSearch repo, we can enable uploading prebuilt model function now.
Example:
```
POST /_plugins/_ml/models/_upload
{
"name": "huggingface/sentence-transformers/paraphrase-MiniLM-L3-v2",
"version": "1.0.1",
"model_format": "TORCH_SCRIPT"
}
```

enable prebuilt model

---

client/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle

[As mac doesn't support GPU building fails in mac. shows error :
```
Caused by: java.lang.UnsatisfiedLinkError: no onnxruntime in java.library.path: /Users/dhrubo/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
```
]

fixing gradle issue

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/DeleteTaskTransportActionTests.java

Signed-off-by: Bhavana Goud Ramaram <rbhavna@amazon.com>
This PR check the condition for model state before deleting a model. If the model is in loaded/loading/partially loaded state, it throws exception and tells user to unload the model first. Previously, the delete API would delete the model irrespective of any model state which was no desirable.
Also checks condition for task state before deleting a task. If task is in running state, it throws an exception.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-ori …

check state before deleting model or task

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/regression/LogisticRegression.java

Fix CI build complaining non-ASCII character.
`–` symbol (`0x2013`) was replaced by `-` (`0x2D`).
Fixes #736.
Note: it was fixed in https://github.com/opensearch-project/ml-commons/pull/738, but not backported into `main` branch.

Fix non-ASCII character.

---

.github/workflows/maven-publish.yml
plugin/build.gradle

backport the github action maven-publish to main branch to make it runnable.
[#734]

Publish snapshots to maven via GHA (#754)

---

.gitignore
client/build.gradle
common/build.gradle
common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/model/TextEmbeddingModelConfig.java
common/src/test/java/org/opensearch/ml/common/model/TextEmbeddingModelConfigTests.java
common/src/test/java/org/opensearch/ml/common/transport/upload/MLUploadInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaInputTest.java
common/src/test/java/org/opensearch/ml/common/transport/upload_chunk/MLCreateModelMetaRequestTest.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/HuggingfaceTextEmbeddingTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/HuggingfaceTextEmbeddingTranslatorFactory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/ONNXSentenceTransformerTextEmbeddingTranslator.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload/TransportUploadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/MLModelMetaCreateTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportCreateModelMetaActionTests.java

Backport PR #640 to main branch.

[Backport to main] add more parameters for text embedding model (#640)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/FileUtils.java

Change  `createParentDirectories` to `forceMkdir` to fix missing method issue.

change to old method to fix missing method createParentDirectories

---

.github/workflows/maven-publish.yml

Typo fix in `maven-publish` GHA workflow - branch list has to be a comma-separate list or list of entries.
I also updated `aws-actions/configure-aws-credentials` used to avoid coming deprecation.
#755 
#754
(Please, label as `backport 2.x`)

Typo fix and minor improvement in `maven-publish` GHA workflow.

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/FileUtils.java

Backport PR #758 to branch 2.6

[Backport to 2.6] change to old method to fix missing method createParentDirectories

---

.github/workflows/maven-publish.yml
client/build.gradle

There are new gradle task `publishJarsPublicationToSnapshotsRepository` which is called in GHA. It publishes client snapshot jars to the [corresponding repository](https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch-ml-client/3.0.0.0-SNAPSHOT/).
Tested with `publishPluginZipPublicationToMavenLocal`, it produced
```
$ ls -1 ~/.m2/repository/org/opensearch/opensearch-ml-client/3.0.0.0-SNAPSHOT/
maven-metadata-local.xml
opensearch-ml-client-3.0.0.0-SNAPSHOT.jar
opensearch-ml-client-3.0.0.0-SNAPSHOT.module
opensearch-ml-client-3.0.0.0-SNAPSHOT.pom
```
jar contains
```
$ tree opensearch-ml-client-3.0.0.0-SNAPSHOT/ | grep -v class
opensearch-ml-client-3.0.0.0-SNAPSHOT/
├── META-INF
│   ├── MANIFEST.MF
│   └── maven
│       ├── org.javassist
│       │   └── …
```

Add publication of jars workflow

---

plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
release-notes/opensearch-ml-common.release-notes-2.5.0.0.md

[Backport to main] tune error message for no ML node case

---

.github/workflows/maven-publish.yml

Continue work done in #764 - workaround for #778.
Having `ml-plugin` is not enough to build SQL plugin, it requires `ml-common` too. Having both together produces jar hell described in #778.
As a workaround I propose publishing a shadow jar.
Related to #778, #764, #763, #754, #755

Publish shadow jar instead of regular one.

---

plugin/build.gradle

Guava has one CVE , we need to bump to 30.0. https://nvd.nist.gov/vuln/detail/cve-2020-8908
For ml-commons, the CVE is from Checkstyle
Before this PR
```
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:8.37
...
+--- com.google.guava:guava:29.0-jre
...
```
After this PR
```
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:8.38
...
+--- com.google.guava:guava:30.0-jre
...
``` …

fix checkstyle version

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java
plugin/src/main/java/org/opensearch/ml/action/load/TransportLoadModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/load/TransportLoadModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionActionTests.java

1. change exception type to return 4xx error code rather than 5xx
2. get function name from cache
https://github.com/opensearch-project/ml-commons/issues/787

change exception type; get function name from cache

---

common/build.gradle

exclude commons-io and reflections class from ml-commons client jar
Now we are using [GHA](https://github.com/opensearch-project/ml-commons/blob/2.x/.github/workflows/maven-publish.yml#L38) to publish ml-commons jar. 
But the jar built by running `./gradlew publishShadowPublicationToSnapshotsRepository` contains other classes from commons-io and reflection
Before this PR, we can see such classes in `client/build/libs/opensearch-ml-client-2.7.0.0-SNAPSHOT.jar`, that will cause Jarhell issue for SQL plugin as it depends on both commons-utils and ml-commons client .
```
org/opensearch/commons/alerting/model/Alert.class
...
javassist/util/proxy/Proxy.class
```
After this PR, these classes will be removed from ml-commons client jar.
#778 
By submitting this pull request, I confirm that my …

exclude commons-io and reflections class from ml-commons client jar

---

docs/docker/docker-compose.yml

add docker-compose file for starting cluster with dedicated ML node
Tested locally 
```
docker-compose up -d
```
Then open OpenSearch Dashboard http://localhost:5601/
`GET _cat/nodes` can see one ML node.
```
172.18.0.4 43 99 7 0.81 0.99 1.13 -    ml             - opensearch-ml1
```

add docker-compose file for starting cluster with dedicated ML node

---

ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ModelSerDeSer.java

fix class not found exception when deserialize model [#781](https://github.com/opensearch-project/ml-commons/pull/781)

fix class not found exception when deserialize model (#781)

---

common/src/main/java/org/opensearch/ml/common/transport/unload/UnloadModelNodeResponse.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelNodeResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/unload/UnloadModelNodesResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/unload/TransportUnloadModelAction.java
plugin/src/test/java/org/opensearch/ml/action/unload/TransportUnloadModelActionTests.java

If user deploy model to multiple ML nodes, then unload model from one ML node, the model state will become `UNLOADED`. This is not correct. We should set the model state as `PARTIALLY_LOADED`. This PR fixed this bug.
[[List any issues this PR will resolve]](https://github.com/opensearch-project/ml-commons/issues/805)

set model state as partially loaded if unload model from partial nodes

---

plugin/src/main/java/org/opensearch/ml/action/unload/TransportUnloadModelAction.java
plugin/src/main/java/org/opensearch/ml/cluster/DiscoveryNodeHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/test/java/org/opensearch/ml/cluster/DiscoveryNodeHelperTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLTrainAndPredictIT.java

Add exclude nodes setting.
If user don't want to run ML tasks on some ML nodes, they can use exclude the nodes with this setting. 
#812 

add exclude nodes setting

---

.github/CODEOWNERS
MAINTAINERS.md

Baselines the MAINTAINERS.md and CODEOWNERS files to specify active and inactive maintainers of ml-commons repo.
This should resolve issue #727 

Baselines the MAINTAINERS.md and CODEOWNERS files

---

common/src/main/java/org/opensearch/ml/common/MLCommonsClassLoader.java
common/src/main/java/org/opensearch/ml/common/annotation/MLInput.java
common/src/main/java/org/opensearch/ml/common/input/MLInput.java
common/src/main/java/org/opensearch/ml/common/input/nlp/TextDocsMLInput.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelResultFilter.java
common/src/test/java/org/opensearch/ml/common/MLCommonsClassLoaderTests.java
common/src/test/java/org/opensearch/ml/common/input/nlp/TextDocsMLInputTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModel.java

Add text docs ML input.
Before this PR
```
POST /_plugins/_ml/models/<model_id>/_predict
{
"text_docs": ["today is sunny"],
"return_number": true,
"target_response": ["sentence_embedding"]
}
```
After
```
POST /_plugins/_ml/models/<model_id>/_predict
{
"text_docs": ["today is sunny"],
"result_filter": {
"return_number": true,
"target_response": ["sentence_embedding"]
}
}
```

add text docs ML input

---

plugin/build.gradle

Bumping checkstyle version for 1.3 as was done in main branch to solve CVE: https://github.com/opensearch-project/ml-commons/pull/735

bumping checkstyle version for 1.3

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ModelSerDeSer.java

This is an urgent rollback on previous SerDeSer filter because the `ObjectInputFilter.Config.ObjectInputFilter.createFilter​` will cause `java.security.AccessControlException: access denied ("java.io.SerializablePermission" "serialFilter")` on our built-in model when integrating with OpenSearch 2.7

Rollback the SerDeSer filter due to AccessControlException on normal model

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterModelMetaAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUploadModelChunkAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRegisterModelMetaActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUploadModelChunkActionTests.java

Add a setting to enable/disable local upload while registering model

Add a setting to enable/disable local upload while registering model

---

common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

Add hash value validation step in register model API.

check hash value in register model API

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java

Don't allow registering models if null hash value in model config file.

fix null hash value

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Add pre-trained model list in register api to restrict the model parameters input.

add pre-trained model list

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelation.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelationTest.java

adding model content hash value

adding model content hash value

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterModelMetaAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUploadModelChunkAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRegisterModelMetaActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUploadModelChunkActionTests.java

Add a setting to enable/disable local upload while registering model
Backported from https://github.com/opensearch-project/ml-commons/pull/873

[Backport to 2.7] Add a setting to enable/disable local upload while registering model

---

common/src/main/java/org/opensearch/ml/common/ModelAccessMode.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupInput.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLUpdateModelGroupInput.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java

Fix no corresponding backend roles user can update model issue

---

common/src/main/java/org/opensearch/ml/common/MLModelGroup.java
ml-algorithms/build.gradle
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelationTest.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploader.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportRegisterModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelITTests.java

fix model meta API and add update model group UTs

fix model meta API and add update model group UTs 

---

client/build.gradle
settings.gradle

Disable shadowjar publishing to remove race condition of normal jar publishing
https://github.com/opensearch-project/opensearch-build/pull/3434
Thanks to @prudhvigodithi @ylwu-amzn for resolving this issue.

Disable shadowjar publishing to remove race condition of normal jar publishing

---

client/build.gradle
scripts/build.sh
settings.gradle

Revert #764 to only use shadowjar publication.
ml used to publish a lot of unrelated content in jar, therefore this PR is created to only publish related classes:
https://github.com/opensearch-project/ml-commons/pull/764
However, the added `jars` publication alongside `shadow` caused some race conditions, so the github actions task was switched back to using `shadow`, without removing `jars` publication in #764.
https://github.com/opensearch-project/ml-commons/pull/779
The above race condition in gradle 7 is not observed clearly when building non-snapshot artifacts with `scripts/build.sh` but showing clear race conditions in gradle 8 after this PR:
https://github.com/opensearch-project/ml-commons/pull/892
The initial fix to this issue in #957 is not correct as it switch from shadow to …

Revert #764 to only use shadowjar publication

---

client/build.gradle

This is a backport PR combining #957 and #959
This should fix the issue on missing ml-commons package when publishing ml-client artifacts. Thanks @ylwu-amzn, @prudhvigodithi, and @peterzhuamazon 

[Backport main]Only use shadowjar publication

---

docs/model_access_control.md

model access control documentation

model access control documentation

---

.github/workflows/CI-workflow.yml
build.gradle
client/build.gradle
common/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle

Add JDK-20 support 
Part of https://github.com/opensearch-project/ml-commons/issues/891

Add JDK-20 support

---

plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/profile/MLModelProfile.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLProfileAction.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java

Backport PR https://github.com/opensearch-project/ml-commons/pull/853 to main branch

Add memory consumption estimation for models in profile API. (#853)

---

docs/model_serving_framework/text_embedding_model_examples.md

updating docs for model group id

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImplTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/cluster/DiscoveryNodeHelperTests.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskDispatcherTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Fix build. This blocks SQL plugin.
Fix build.

Fix build.

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
plugin/src/main/java/org/opensearch/ml/action/remote/TransportCreateConnectorAction.java

throw meta data exception if the master key is not provided for encryption/decryption.

throw exception when masterKey is not provided

---

plugin/src/main/java/org/opensearch/ml/action/remote/DeleteConnectorTransportAction.java

Add logs to show errors when deleting a connector that is not exist. 
Add checking connector usages before deleting. 
https://t.corp.amazon.com/V948634361

check connector usages before deleting

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorDeleteAction.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorDeleteRequest.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorGetAction.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorGetRequest.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorGetResponse.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorSearchAction.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorAction.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorRequest.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorResponse.java

add transport input and action classes for connectors in common repo.

connector transport actions, requests and  responses

---

common/src/main/java/org/opensearch/ml/common/connector/ConnectorAction.java
common/src/main/java/org/opensearch/ml/common/connector/ConnectorProtocols.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/Predictable.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/ad/AnomalyDetectionLibSVM.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/clustering/KMeans.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/clustering/RCFSummarize.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/BatchRandomCutForest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/FixedInTimeRandomCutForest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/regression/LinearRegression.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/regression/LogisticRegression.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/sample/SampleAlgo.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteModelTest.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java

refactor predictable: add method to check if model is ready

---

common/src/main/java/org/opensearch/ml/common/connector/AwsConnector.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
plugin/src/main/java/org/opensearch/ml/helper/ConnectorAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/helper/ConnectorAccessControlHelperTests.java

Add basic connector access control classes
NA

Add basic connector access control classes

---

common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/test/java/org/opensearch/ml/common/RemoteModelTests.java
common/src/test/java/org/opensearch/ml/common/connector/AwsConnectorTest.java
common/src/test/java/org/opensearch/ml/common/transport/register/MLRegisterModelInputTest.java

remote inference: add unit test for model and register model input

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/GetConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/breaker/MLCircuitBreakerService.java
plugin/src/main/java/org/opensearch/ml/breaker/MemoryCircuitBreaker.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndex.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java

add connector transport actions and disable native memory circuit breakers.

connector transport actions and disable native memory CB

---

common/build.gradle
ml-algorithms/build.gradle

change to compileOnly to avoid jarhell

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportCreateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java

remote inference: add unit test for create connector request/response

---

common/src/main/java/org/opensearch/ml/common/MLModelGroup.java
common/src/test/java/org/opensearch/ml/common/MLModelGroupTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/test/java/org/opensearch/ml/helper/ModelAccessControlHelperTests.java

See such error when register pretrained model without model group id,
```
{
"error": {
{
"type": "illegal_argument_exception",
"reason": "You cannot specify model access control parameters because the Security plugin or model access control is disabled on your cluster."
}
],
"type": "illegal_argument_exception",
"reason": "You cannot specify model access control parameters because the Security plugin or model access control is disabled on your cluster."
},
"status": 400
}
```
The reason is `input.getBackendRoles()` is not null, but it's empty.
This PR fixed the bug.
For more information on following Developer Certificate …

fix cannot specify model access control parameters error

---

docs/model_access_control.md
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdateModelGroupAction.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelGroupManagerTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateModelGroupActionTests.java

PenTest fixes: error codes and update model group fix

PenTest fixes: error codes and update model group fix

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactory.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactoryTests.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java

Fix rare private ip address bypass SSRF issue

Fix rare private ip address bypass SSRF issue

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java

Return 404 error code when the model is not found when deleting it.

leftover in the 404 Not Found return error

---

plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/helper/ModelAccessControlHelperTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelGroupManagerTests.java

modify error message when model group not unique is provided

modify error message when model group not unique is provided

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelationTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLExecuteTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java

ML config index will be system index, should stash context before reading/writing 

stash context before accessing ml config index

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java

fix init master key bug

---

plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/MLModelGroupRestIT.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

IT Security Tests for model access control

IT Security Tests for model access control

---

.github/workflows/CI-workflow.yml

Tweak workflow event so ci can retrieve credentails correctly
This is a follow up to https://github.com/opensearch-project/ml-commons/pull/1099

Tweak workflow event so ci can retrieve credentails correctly

---

release-notes/opensearch-ml-common.release-notes-2.9.0.0.md

2.9 release notes

---

plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/connector/DeleteConnectorTransportActionTests.java

Currently in deleting a connector, an IndexNotFound exception is throw when the ml_model index does not exist. But actually this deletion should be successful because there will be no models associated with the connector.
Verified the fix using local cluster.

delete connector successfully if model index is missing

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Temporarily ignore OpenAI Tests

---

.github/workflows/CI-workflow.yml

Add shell bash settings for windows github actions to export credentials
This is a follow up to https://github.com/opensearch-project/ml-commons/pull/1114

Add shell bash settings for windows github actions to export credentials

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Adds a check to skip remote inference integration tests if the API key is null

Add null key check for remote inference integration tests

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Removes @ignore from OpenAI tests

[Backport 2.9] Reenable OpenAI Remote Inference Tests

---

release-notes/opensearch-ml-common.release-notes-2.9.0.0.md

more PRs to 2.9 release notes

---

DEVELOPER_GUIDE.md

updating developer guide for CCI contributors

---

docs/tutorials/remote_inference.md

add remote inference tutorial

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java

[Backport to 2.x] remote inference: escape parameter if not valid json

---

docs/tutorials/model_auto_redeploy.md

Add model auto redeploy tutorial

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ScriptUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLStatsAction.java
plugin/src/main/java/org/opensearch/ml/stats/MLClusterLevelStat.java
plugin/src/main/java/org/opensearch/ml/utils/IndexUtils.java
plugin/src/test/java/org/opensearch/ml/model/MLModelGroupManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLStatsActionTests.java

Add more stats:
- connector count
- connector index status
- config index status
Fix model count bug: local model may have multiple chunks, the model count number should not include model chunk.
Also fine tune some error message

add more stats: connector count, connector/config index status; fix model count bug

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java

If user input array parameter, the `MLCreateConnectorInput` will fail to parse. This PR fixed that bug.

fix parameter parsing bug for create connector input

---

plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java

fix:admin with no backend role on AOS unable to create restricted model group

fix:admin with no backend role on AOS unable to create restricted model group

---

common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/test/java/org/opensearch/ml/common/connector/HttpConnectorTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java

Fix null pointer exception when input parameter is null.

fill null parameters in connector body template

---

plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/execute/TransportExecuteTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/action/training/TransportTrainingTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/trainpredict/TransportTrainAndPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelAction.java
plugin/src/main/java/org/opensearch/ml/cluster/DiscoveryNodeHelper.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/cluster/DiscoveryNodeHelperTests.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTaskDispatcherTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

Per PM's suggestion, remote model should be able to run on data or ML node by default. But we should also keep local model run on ML node by default. So we still keep `plugins.ml_commons.only_run_on_ml_node` as true, but only control local model. Add more setting to provide granular level control on remote and local model.
1. Add `plugins.ml_commons.task_dispatcher.eligible_node_role.remote_model` which controls only remote model can run on which node. Default value is `["data", "ml"]` which means the remote model can run on data node and ML node by default.
2. Add `plugins.ml_commons.task_dispatcher.eligible_node_role.local_model` which controls only remote model can run on which node. But we have `plugins.ml_commons.only_run_on_ml_node` which controls the model can only run on ML node …

add eligible node role settings

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ScriptUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLStatsAction.java
plugin/src/main/java/org/opensearch/ml/stats/MLClusterLevelStat.java
plugin/src/main/java/org/opensearch/ml/utils/IndexUtils.java
plugin/src/test/java/org/opensearch/ml/model/MLModelGroupManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLStatsActionTests.java

Backport https://github.com/opensearch-project/ml-commons/pull/1180 to 2.x

[Backport to 2.x]add more stats: connector count, connector/config index status; fix model count bug

---

plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRegisterModelActionTests.java

Add Remote Inference feature flag. It adds a check up for the feature flag setting before invoking "Create Connector", "Register Model", "Deploy Model" and "Predict Model" APIs. 
Tested this PR using a local cluster.

add feature flags for remote inference

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java

[Backport to 2.x] fix parameter parsing bug for create connector input

---

common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/test/java/org/opensearch/ml/common/connector/HttpConnectorTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java

[Backport to 2.x] fill null parameters in connector body template (#1192)

---

plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRegisterModelActionTests.java

[Backport to 2.x] add feature flags for remote inference

---

plugin/build.gradle

We bump checksyle from 10.12.0 to 10.12.2 to fix CVE-2023-2976

Bump checkstyle version for CVE fix

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRegisterModelActionTests.java

* Add a setting to enable/disable model url in register API.
* move the setting from transport to rest api
* remove transport setting
* Update plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterModelAction.java
* fix ut
* fix spotless
* address comments
* rename the setting
* fix a UT bug
---------
Backport https://github.com/opensearch-project/ml-commons/pull/871 to main

[Backport to main]Add a setting to enable/disable model url in register API. (#871)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java

When user registering a pre-build model from model list: https://artifacts.opensearch.org/models/ml-models/model_listing/pre_trained_models.json, there'll be NEP issue since the data structure is not correct in code, this PR is to fix this issue.

Fix register pre-build model error

---

plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

Backport https://github.com/opensearch-project/ml-commons/pull/940 to main

[Backport to main]enable model access control in secure reset IT (#940)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/test/java/org/opensearch/ml/rest/MLModelGroupRestIT.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

Backport https://github.com/opensearch-project/ml-commons/pull/951 to main
Reverted https://github.com/opensearch-project/ml-commons/pull/1246 since the json structure changed.

[Backport to main]fix security IT failure caused by weak password (#951)

---

docs/model_serving_framework/text_embedding_model_examples.md

* updating docs for model group id
fixing the text
updated docs
* addressing comments
---------
Backport https://github.com/opensearch-project/ml-commons/pull/980 to main

[Backport to main]updating docs for model group id (#980)

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLDeployModelActionIT.java

* Adding a failing integ test for redeploy model and fix breaking changes from OpenSearch core
* Adding model group ID changes for tests
* Fixing tests for ImmutableMap copy
* Commenting wait out task for model
* Adding a failing integ test for redeploy model and fix breaking changes from OpenSearch core
* Rebasing with 2.x
* Adding logs to debug the test in GHA
* GHA tests
* Still debugging
* Removing comment
* Removing unnecessary changes
* Removing logs
---------
Backport https://github.com/opensearch-project/ml-commons/pull/1016 to main
For more information on following Developer Certificate of Origin and signing off your commits, …

[Backport to main][2.x] Adding an integration test for redeploying a model  (#1016)

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/plugin/MachineLearningPluginTests.java
search-processors/build.gradle
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAResponseProcessor.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/client/ConversationalMemoryClient.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/ext/GenerativeQAParamExtBuilder.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/ChatCompletionInput.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/DefaultLlmImpl.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/LlmIOUtil.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/prompt/PromptUtil.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAParamUtilTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQARequestProcessorTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAResponseProcessorTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeSearchResponseTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/client/ConversationalMemoryClientTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/ext/GenerativeQAParamExtBuilderTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/ext/GenerativeQAParamUtilTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/ext/GenerativeQAParametersTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/llm/ChatCompletionInputTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/llm/DefaultLlmImplTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/llm/LlmIOUtilTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/prompt/PromptUtilTests.java
settings.gradle

#1150 
- [ x] New functionality includes testing.
- [x ] All tests pass
- [ x] New functionality has been documented.
- [ x] New functionality has javadoc added
- [ x] Commits are signed per the DCO using --signoff 

[Feature] Add Retrieval Augmented Generation search processors

---

ml-algorithms/build.gradle

Bump aws-encryption-sdk-java version to fix CVE-2023-33201

Bump aws-encryption-sdk-java to fix CVE-2023-33201

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java

In previous ml system shard replicas always stays on an arbitrary number and cannot expand automatically, which will cause unassigned shards and yellow cluster problem. This PR can resolve this issue.

Fix unassigned ml system shard replicas

---

docs/model_serving_framework/text_embedding_model_examples.md
docs/tutorials/remote_inference.md

fixing doc link

---

memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexTests.java

newStoredContext() -> stashContext() for system index ops
#1272 

fix system index access bug #1272

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLUpdateConnectorAction.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLUpdateConnectorRequest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLUpdateConnectorRequestTests.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdateConnectorAction.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportUpdateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateConnectorActionTests.java

Update connector API to partially update a connector in the ml-connector index. Verified it works with updating existing fields, adding new fields and deleting fields.
Example:
POST /_plugins/_ml/connectors/_update/4s0vGooBTRq0xHburjWW
{
"openAI_key": "new key"
}
}
GET /_plugins/_ml/connectors/4s0vGooBTRq0xHburjWW
{
...
"openAI_key": "new key"
},
...
}

update connector API

---

common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelResponse.java
common/src/test/java/org/opensearch/ml/common/transport/register/MLRegisterModelResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java

This change only applies to registering remote models. Registering a remote model doesn't need Asynchronize, it should return model_id right away in the response. 
**Before this change:**
POST /_plugins/_ml/models/_register
{
"name": "openAI-GPT-3.5 completions",
"connector_id": "kUFFL4kB4ubqQRzeQ_r-"
}
Response:
{
"task_id": "l0FIL4kB4ubqQRzeKvpV",
"status": "CREATED"
}
**After this change:**
POST /_plugins/_ml/models/_register
{
"name": "openAI-GPT-3.5 completions",
"connector_id": "kUFFL4kB4ubqQRzeQ_r-"
}
Response:
{
"task_id": "l0FIL4kB4ubqQRzeKvpV",
"status": "CREATED",
"model_id": "xxxxxxxxxxxxxx",
}

return model id in registering remote model

---

memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandler.java
memory/src/test/java/org/opensearch/ml/memory/ConversationalMemoryHandlerITTests.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryDeleteConversationActionIT.java

Fix issue where getInteractions returned different results in security-enabled and -disabled settings. Also fix a data race in deleteConversation that made that test flaky.
#1272 

2.x consistent get interactions

---

common/src/main/java/org/opensearch/ml/common/transport/deploy/MLDeployModelResponse.java
common/src/test/java/org/opensearch/ml/common/transport/deploy/MLDeployModelResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileModelResponseTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchConnectorActionTests.java

This is to add deployment status with minimum impact to the current code and API workflows. Verified it works with local environment. 
POST /_plugins/_ml/models/mUFIL4kB4ubqQRzeKvr1/_deploy
sample response for remote model
{
"task_id": "OP5JL4kB28KP1SGMupr3",
"status": "CREATED"
}
This is ridiculous - deploying a remote model doesn't need to be asyncrhonize. I need to see the deployment status right away without sending another API request to query the Task Id!
POST /_plugins/_ml/models/mUFIL4kB4ubqQRzeKvr1/_deploy
sample response for remote model
{
"task_id": "OP5JL4kB28KP1SGMupr3",
"task_type" : "DEPLOY_MODEL"
"status": "COMPLETED"
}
For non remote models, the response will be 
{
"task_id": "OP5JL4kB28KP1SGMupr3",
"task_type" : "DEPLOY_MODEL"
"status": "CREATED"
}
If the deployment …

include deployment status in deploy API response

---

release-notes/opensearch-ml-common.release-notes-2.10.0.0.md

This PR make 2.10 release notes up to date to catch up with latest OpenSearch 2.10 build, meanwhile fix an experimental feature previously classified to feature

Make 2.10 release notes up to date

---

README.md

fix spelling in Readme.md 

---

.github/workflows/auto-release.yml
README.md
common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/connector/MLPostProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/MLPreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/input/remote/RemoteInferenceMLInput.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/connector/MLPostProcessFunctionTest.java
docs/model_serving_framework/text_embedding_model_examples.md
docs/tutorials/remote_inference.md
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ScriptUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/utils/ScriptUtilsTest.java
plugin/src/main/java/org/opensearch/ml/indices/MLIndicesHandler.java
release-notes/opensearch-ml-common.release-notes-2.10.0.0.md

This PR is to rebase main branch latest code to feature branch to make sure other PRs to feature branch pass all checks.
NA

Rebase main code to feature branch

---

plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java

This PR fix the wrong error message in TransportDeplpoyModelAction class

Fix error message in TransportDeplpoyModelAction class

---

common/src/main/java/org/opensearch/ml/common/transport/deploy/MLDeployModelResponse.java
common/src/test/java/org/opensearch/ml/common/transport/deploy/MLDeployModelResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/test/java/org/opensearch/ml/action/profile/MLProfileModelResponseTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchConnectorActionTests.java

(cherry picked from commit 9992067d89317892c37848e57dfe44d274817b39)

[Backport to main]include deployment status in deploy API response

---

common/src/main/java/org/opensearch/ml/common/input/nlp/TextDocsMLInput.java
common/src/test/java/org/opensearch/ml/common/input/nlp/TextDocsMLInputTest.java

We need to support null value for some use case, for example multi-modal model needs text and image input. User who use TextDocsInputDataSet can use such format `[text, image]`, the first item is text and second is image, but they could be null, for example user may only input image, the input will be `[null, image]`

allow input null for text docs input

---

common/src/main/java/org/opensearch/ml/common/dataset/TextDocsInputDataSet.java
common/src/test/java/org/opensearch/ml/common/dataset/TextDocsInputDataSetTest.java

fix null exception in text docs data set

---

common/src/main/java/org/opensearch/ml/common/input/nlp/TextDocsMLInput.java
common/src/test/java/org/opensearch/ml/common/input/nlp/TextDocsMLInputTest.java

Backport https://github.com/opensearch-project/ml-commons/pull/1401 to 2.x

[Backport to 2.x] allow input null for text docs input (#1401)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

This PR fixed two bugs
1. When neural search plugin send text docs to remote embedding model with unescaped string, it will throw invalid json error.
2. When user register remote model with `?deploy=true`, the model won't be deployed. This part disabled by https://github.com/opensearch-project/ml-commons/pull/1329/files

fix text docs input unescaped error; enable deploy remote model

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLDeployModelActionIT.java

Redeploying Model fails on MacOS which we officially don't support for ML-Commons yet. 
Part of #844 

Ignoring Redeploy test on MacOS due to known failures

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelation.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/SearchModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

We see reindex will throw error "wrong user in reader context". That's because after stashing thread context, the user info will be gone. Security plugin will recheck user info when reindex, then throw this error.  We should restore thread context before running action listener. 

restore thread context before running action listener

---

plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/SearchTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploader.java
plugin/src/test/java/org/opensearch/ml/action/tasks/SearchTaskTransportActionTests.java

Continue of https://github.com/opensearch-project/ml-commons/pull/1418

fix more places where thread context not restored

---

plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/SearchTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/MLModelChunkUploader.java
plugin/src/test/java/org/opensearch/ml/action/tasks/SearchTaskTransportActionTests.java

[Backport to 2.x] fix more places where thread context not restored (#1421)

---

plugin/src/test/java/org/opensearch/ml/bwc/MLCommonsBackwardsCompatibilityIT.java

This PR should unblock BWC test. Now we use regex to judge if OS version is updated or not.

Fix BWC test suite

---

memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexTests.java

(cherry picked from commit 8cdac919fa05a6a7be90edf9ade64b3669e10771)
PR 2/4 bringing conversation feature to main

[Backport] fix system index access bug #1272 (#1320)

---

memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandler.java
memory/src/test/java/org/opensearch/ml/memory/ConversationalMemoryHandlerITTests.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryDeleteConversationActionIT.java

* consistent getInteractions response when security/no security
* fix deletion race condition
* cleanup
---------
(cherry picked from commit 24a629b1d10ed7469b7400dbd16184595547e282)
PR 3/4 to backport conversation features to main

[Backport] 2.x consistent get interactions (#1334)

---

plugin/src/main/java/org/opensearch/ml/action/stats/MLStatsNodeResponse.java
plugin/src/main/java/org/opensearch/ml/action/stats/MLStatsNodesResponse.java
plugin/src/main/java/org/opensearch/ml/action/stats/MLStatsNodesTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/stats/MLModelStats.java
plugin/src/main/java/org/opensearch/ml/stats/MLStatLevel.java
plugin/src/main/java/org/opensearch/ml/stats/MLStats.java
plugin/src/main/java/org/opensearch/ml/stats/MLStatsInput.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTrainingTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/stats/MLStatsNodeResponseTests.java
plugin/src/test/java/org/opensearch/ml/action/stats/MLStatsNodesTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLStatsActionTests.java
plugin/src/test/java/org/opensearch/ml/stats/MLModelStatsTests.java
plugin/src/test/java/org/opensearch/ml/stats/MLStatsInputTests.java
plugin/src/test/java/org/opensearch/ml/stats/MLStatsTests.java

[adding model level metric in node level : https://github.com/opensearch-project/ml-commons/issues/1295
With this change stat api will show metrics like:
```
{
"nodes": {
"KKGb_PrDQl2zWWIhifyFdQ": {
"algorithms": {
"text_embedding": {
"deploy": {
"ml_action_request_count": 1
},
"register": {
"ml_action_request_count": 1
},
"predict": {
"ml_action_request_count": 1
}
}
},
"models": {
"FFt4i4oBkVwzPy8kRevJ": {
"deploy": {
"ml_action_request_count": 1
},
"predict": {
"ml_action_request_count": 1
}
}
}
}
}
}
```
] …

adding model level metric in node level

---

common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/connector/MLPostProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/MLPreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/input/remote/RemoteInferenceMLInput.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/connector/MLPostProcessFunctionTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ScriptUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/utils/ScriptUtilsTest.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java

Backport PRs to 2.9
#1427 
#1407 
#1274 
#1362 

[Bakport to 2.9] Backport multiple PRs to 2.9

---

docs/remote_inference_blueprints/bedrock_connector_blueprint.md

This commit adds an example blueprint for using Amazon Bedrock within Opensearch

add bedrock blueprint doc

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java

Currently, when the last version of a model group is being deleted, the model group also gets deleted automatically along with the version. Due to this, the access control information stored in model group is getting deleted without user's knowledge and user is required to create a new model group which is undesirable. With this PR, we ensure even if the last existing version of a model group is deleted, the model group still remains without getting deleted.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin …

fix model group auto-deletion when last version is deleted

---

common/src/main/java/org/opensearch/ml/common/output/model/ModelTensors.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java

Add http status code to model tensor, so client can know if the remote model returns correctly.
For example, if Cohere text embeding model exceed quota limit, it will return 429 status code. 

add status code to model tensor

---

common/src/main/java/org/opensearch/ml/common/output/model/ModelTensors.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java

* add status code to model tensor
* fix ut
---------

[Backport to 2.x] add status code to model tensor (#1443)

---

plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaAction.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/upload_chunk/TransportRegisterModelMetaActionTests.java

After this PR, we let user register new version to an existing model group with the name alone even if model group ID is not provided. But if user does not have access to the model group in this case, we throw exception asking user to give a different name since user does not have access to the provided name

register new versions to a model group based on the name provided

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateConnectorActionTests.java

Add a setting to control the update connector API, due to its being experimental feature

Add a setting to control the update connector API

---

plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java

ML-commons predict API needs to check user permissions before the actual inference happen but the current implementation is not efficient since we need to read index for each single predict request. And fetching model info with getModel leverages the `GET` threadpool in OpenSearch Core, under heavy traffic, there might be rejection exception thrown since the threadpool is saturated.
NA

Performance enhacement for predict action by caching model info

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java

Signed-off-by: zane-neo <zaniu@amazon.com>
* Performance enhacement for predict action by caching model info (#1472)

[Backport to 2.9]Performance enhacement for predict action by caching model info (#1472)

---

plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java

For remote embedding model, error happens when ingest documents with neural-search ingest pipeline. Error says no worker nodes found for the model. But actually model already deployed.  neural-search ingest pipeline will send text_embedding request to ml-commons, in ml-commons we will translate it into remote model request. In ml-commons we can't use function name from neural-search(text-embedding), we should use the model's real function name. 
Related PR #1472 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CON …

fix no worker node exception for remote embedding model

---

release-notes/opensearch-ml-common.release-notes-2.11.0.0.md

release note 2.11.0.0

---

common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLUpdateConnectorRequest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLUpdateConnectorRequestTests.java
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/helper/ConnectorAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/test/java/org/opensearch/ml/action/connector/DeleteConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportUpdateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateConnectorActionTests.java

fix update connector API

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java

add prefix to show the error is from remote service

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java

Added create connector API for MLClient. 
Part of https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/70

Added create connector API for MLClient

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java

fix multiple docs support

---

docs/remote_inference_blueprints/bedrock_connector_anthropic_claude_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_titan_embedding_blueprint.md

add bedrock titan embedding model blueprint

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java

Expose execute api for MLClient

Expose execute api for MLClient

---

common/build.gradle
ml-algorithms/build.gradle
search-processors/build.gradle

Bump json version to address CVE-2023-5072

Bump json version to address CVE-2023-5072

---

plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java

fine tune predict API: read model from index directly

---

docs/remote_inference_blueprints/bedrock_connector_titan_embedding_blueprint.md

Fix bedrock embedding model blueprint

fix bedrock embedding model blueprint

---

.github/workflows/CI-workflow.yml

Onboarding Jenkins prod docker images to github ci check
#1455

Onboarding Jenkins prod docker images to github ci check

---

common/build.gradle
ml-algorithms/build.gradle

[Backport to 2.9] Bump json version to address CVE-2023-5072

---

memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle

Revert shadow jar and update dependency version to make IntelliJ IDEA happy
This will need to run `./gradlew :opensearch-ml-common:publishToMavenLocal` first to publish `opensearch-ml-common` to local maven repository

revert shadow jar and update dependency version

---

.gitignore
spi/src/main/java/org/opensearch/ml/common/spi/MLCommonsExtension.java
spi/src/main/java/org/opensearch/ml/common/spi/tools/Parser.java
spi/src/main/java/org/opensearch/ml/common/spi/tools/Tool.java
spi/src/main/java/org/opensearch/ml/common/spi/tools/ToolAnnotation.java

Adds generic types to Tool interfaces
In support of #1161 , #1521, #1545, #1546, #1547, #1548

Fix Tool interface javadocs and generic types

---

.github/CODEOWNERS
MAINTAINERS.md

Nominate Austin and Henry as maintainer by following this [process](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#nomination).
We already got approval from current maintainers.

add Austin and Henry as maintainer

---

release-notes/opensearch-ml-common.release-notes-2.11.1.0.md

release notes for 2.11.1.0

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java

For some model , they may took multiple input docs and output less embeddings. For example,  multi-modal model will take 2 input docs, but output just 1 embedding. 
Add a step size parameter to control the process step for integration with neural-search.

support step size for embedding model which outputs less embeddings

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java

Validate step size
This is to address comments from this PR https://github.com/opensearch-project/ml-commons/pull/1586

validate step size

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactory.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactoryTests.java

if statement to check if httpHost name is not needed as an exception is already raised when creating the httpHost object for null, empty, and whitespace hostNames

removed empty host check, inherently within httpHost object generation

---

plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdateConnectorAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateConnectorActionTests.java

Fix the 500 internal service error reported in the pen test. All parsing errors should return 400 error code showing it's coming from users.
Test: 
~~~
PUT /_plugins/_ml/connectors/zmMCmIsBaumhjugAg9cu
{
"description": null
}
Response:
{
"error": {
{
"type": "parse_exception",
"reason": "Can't get text on a VALUE_NULL at 2:18"
}
],
"type": "parse_exception",
"reason": "Can't get text on a VALUE_NULL at 2:18"
},
"status": 400
}
~~~
~~~
PUT /_plugins/_ml/connectors/zmMCmIsBaumhjugAg9cu
{
"description": "Update description"
}
Response:
{
"_index": ".plugins-ml-connector",
"_id": "zmMCmIsBaumhjugAg9cu",
"_version": 3,
"result": "updated",
"_shards": {
"total": 1,
"successful": 1,
"failed": 0
},
"_seq_no": 2,
"_primary_term": 2
}
~~~
[[List any issues this PR will …

return parsing exception 400 for parsing errors

---

plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdateConnectorAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateConnectorActionTests.java

Rebased the PR https://github.com/opensearch-project/ml-commons/pull/1593 and backport into 2.11. 

[Backport 2.11] Rebased - return parsing exception 400 for parsing errors

---

ml-algorithms/build.gradle

Publishing/Assembling of ml-commons is failing because of the below error:
```
Execution failed for task ':opensearch-ml-plugin:bundlePlugin'.
> Could not resolve all dependencies for configuration ':opensearch-ml-plugin:runtimeClasspath'.
> Conflict(s) found for the following module(s):
- org.reactivestreams:reactive-streams between versions 1.0.4 and 1.0.3
Run with:
--scan or
:opensearch-ml-plugin:dependencyInsight --configuration runtimeClasspath --dependency org.reactivestreams:reactive-streams
to get more insight on how to solve the conflict.
```
`org.reactivestreams:reactive-streams` is a transitive dependency from `awssdk`. Upgrading to fix it.
By submitting this pull request, I confirm that my contribution is made under the terms of the …

Updated version of awssdk

---

docs/remote_inference_blueprints/bedrock_connector_ai21labs_jurassic_blueprint.md

It provides a functional example of a connector blueprint to connect with AI21 Labs Jurassic to execute inferences outside OpenSearch using the remote models functionality.

Added Connector Blueprint for AI21 Labs Jurassic-2 Mid

---

client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java

Following PR https://github.com/opensearch-project/ml-commons/pull/1560, additional class casting issues have been observed for `getMlTask`
Coming from https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/131
Continuation of https://github.com/opensearch-project/ml-commons/issues/1553 and https://github.com/opensearch-project/ml-commons/pull/1580

Fixing class casting exception for MachineLearningNodeClient GetMLTask API

---

common/src/main/java/org/opensearch/ml/common/MLTask.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

backport to 2.11 for pr 1529
backport to 2.11 for pr 1529

[Backport 2.11] Read function Name from pretrained model (#1529)

---

common/src/main/java/org/opensearch/ml/common/MLTask.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

backport pr for https://github.com/opensearch-project/ml-commons/pull/1529
backport pr for https://github.com/opensearch-project/ml-commons/pull/1529

[Backport 2.x] Read function Name from pretrained model (#1529)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/ConversationIndexMemory.java

change session_id to memory_id in agent execution response
set first user question as the name of conversation 
store tool name in orgin field in the interaction

change session_id to memory_id in agent execution response

---

build.gradle
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/SearchAlertsTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/SearchAlertsToolTests.java

Adds a search alerts tool. Utilizes [getAlerts()](https://github.com/opensearch-project/common-utils/blob/main/src/main/kotlin/org/opensearch/commons/alerting/AlertingPluginInterface.kt#L135) exposed by the alerting interface in common utils.
Exposes all of the parameters offered by the interface, besides `missing` since that doesn't seem relevant (defaults to `null`). All parameters have defaults which match that of the [get alerts API](https://opensearch.org/docs/latest/observing-your-data/alerting/api/#get-alerts) for now.
The amount of parameters and/or the default values may be changed later on depending on agent performance and accuracy. For example, too much parameter tuning may lead to messy or invalid results.
Additionally, further integration testing will need to be done to …

Implement search alerts tool

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLUpdateConnectorAction.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLUpdateConnectorRequest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLUpdateConnectorRequestTests.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdateConnectorAction.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportUpdateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateConnectorActionTests.java

Backport [1227](https://github.com/opensearch-project/ml-commons/pull/1227) to main

[Backport to main] update connector API 

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLRegisterAgentResponse.java
memory/src/test/java/org/opensearch/ml/memory/ConversationalMemoryHandlerITTests.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexITTests.java
memory/src/test/java/org/opensearch/ml/memory/index/InteractionsIndexITTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Register agent API support for MLClient. This will allow flow framework to integrate with register agent API.

Register agent API support for MLClient

---

common/src/main/java/org/opensearch/ml/common/conversation/ActionConstants.java
memory/src/main/java/org/opensearch/ml/memory/ConversationalMemoryHandler.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetTracesAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetTracesRequest.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetTracesResponse.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/GetTracesTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandler.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMemoryGetTracesAction.java

Only return final results in the "List Conversation" API. Add a new API of "Get Trace" to return only traces for an interaction. 

separate get Trace actions into a new rest API

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/IndexMappingTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/IndexMappingToolTests.java

Implements a tool to fetch index settings and mappings.
In support of #1161

Implement Index Mapping Tool

---

plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java
plugin/src/main/java/org/opensearch/ml/cluster/MLCommonsClusterManagerEventListener.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Support cluster level restart model auto redeploy.
https://github.com/opensearch-project/ml-commons/issues/1641

Cluster restart model auto redeploy

---

client/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
settings.gradle
spi/build.gradle
spi/src/main/java/org/opensearch/ml/common/spi/memory/Memory.java
spi/src/main/java/org/opensearch/ml/common/spi/memory/Message.java

Add memory interface in spi.
https://github.com/opensearch-project/ml-commons/issues/1614

Memory interface in spi

---

common/src/main/java/org/opensearch/ml/common/transport/model_group/MLModelGroupGetAction.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLModelGroupGetRequest.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLModelGroupGetResponse.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLModelGroupGetRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLModelGroupGetResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/model_group/GetModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetModelGroupAction.java
plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/action/model_group/GetModelGroupITTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/GetModelGroupTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/MLModelGroupRestIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetModelGroupActionIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetModelGroupActionTests.java

Get model group API using model_group_id

Get model group API

---

common/src/main/java/org/opensearch/ml/common/conversation/ConversationMeta.java
common/src/main/java/org/opensearch/ml/common/conversation/ConversationalIndexConstants.java
memory/src/main/java/org/opensearch/ml/memory/ConversationalMemoryHandler.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateInteractionTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandler.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationsResponseTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationsTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryGetInteractionsActionIT.java

Add updated_time field in the Memory meta index. The updated_time will be updated when creating a new conversation, updating a conversation and creating a new interaction for the conversation. 

add updated_time in conversation meta index and update transport actions

---

common/src/main/java/org/opensearch/ml/common/conversation/ConversationalIndexConstants.java

Update the mapping of conversation meta from keyword to text.

change conversation meta name mapping to text to allow keyword search

---

build.gradle
client/build.gradle
common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle

Update Lombok and Gradle plugins to support JDK-21
```
> java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'
```

Update Lombok and Gradle plugins to support JDK-21

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/MLMemoryManager.java

Unlike the list interactions in the transport layer, the list interactions in the memory Manager needs to return the latest N records from latest to oldest.

use DSEC order for the interaction history in chat agent

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
common/src/main/java/org/opensearch/ml/common/transport/undeploy/MLUndeployModelsResponse.java

Adds `undeploy()` method to MLClient, invoking undeploy models API

Add Undeploy Models to MLClient

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java

Backporting https://github.com/opensearch-project/ml-commons/pull/1586 and https://github.com/opensearch-project/ml-commons/pull/1587 from 2.11 to main

Backport PRs from 2.11 to main

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java

Adds MLClient method for delete agent.
Similar to Delete Connector and Delete Model (literally a copy/paste/change-names), does not require special treatment of the response class loader.

Add Delete Agent to MLClient

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java

CI run with locale `-Dtests.locale=tr -Dtests.timezone=Cuba` https://github.com/opensearch-project/ml-commons/actions/runs/7097212068/job/19316954587?pr=1733
related to https://github.com/aws/aws-encryption-sdk-java/issues/1879

fix flaky test due to localization

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunnerTest.java

Refactored conversation creation to MLAgentExecutor so that the same memory ID could be used across multiple agents. Generated memory ID will be passed to agents as part of input parameters. Integrated memory with flow agent, with output of the flow agent being appended to additional info field of interaction. 
**Request:**
```
{
"question": "How many indexes do I have in my cluster?",
"verbose": false
}
}
```
**Response:**
```
{
"inference_results": [
{
"output": [
{
"name": "response",
"dataAsMap": {
"response": "There are 7 indexes in the cluster."
}
},
{
"name": "QuestionSuggestor",
"result": " Here are some follow up questions the Human may ask:\n\n[question1: 'How many shards are there per index?',\nquestion2: 'What is the health status of the indexes?', …
```

Refactor memory layer to be used across flow and chat agent

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
common/src/main/java/org/opensearch/ml/common/dataset/MLInputDataType.java
common/src/main/java/org/opensearch/ml/common/dataset/TextSimilarityInputDataSet.java
common/src/main/java/org/opensearch/ml/common/input/MLInput.java
common/src/main/java/org/opensearch/ml/common/input/nlp/TextSimilarityMLInput.java
common/src/test/java/org/opensearch/ml/common/dataset/TextSimilarityInputDatasetTest.java
common/src/test/java/org/opensearch/ml/common/input/MLInputTest.java
common/src/test/java/org/opensearch/ml/common/input/nlp/TextSimilarityMLInputTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_similarity/TextSimilarityCrossEncoderModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/text_similarity/TextSimilarityTranslator.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_similarity/TextSimilarityCrossEncoderModelTest.java

Adds support for (huggingface) cross encoders to ml-commons. Uses a new function name (`TEXT_SIMILARITY`) which takes as input a list of text pairs and spits out 1-dimensional tensors representing the similarity of the items in each pair. E.g.
```POST /_plugins/_ml/models/UWEvuosBD5KonuYrtwGX/_predict 
{
"query_text": "today is sunny"
"text_docs": [ 
"today is sunny",
"today is july fifth",
"it is winter"
] 
}
```
yields
```
{
"inference_results": [
{
"output": [
{
"name": "logits",
"data_type": "FLOAT32",
"shape": [
1
],
"data": [
10.939743
],
"byte_buffer": {
"array": "MAkvQQ==",
"order": "LITTLE_ENDIAN"
}
}
]
},
{
"output": [
{
"name": "logits",
"data_type": "FLOAT32",
"shape": [
1
],
"data": [
-6.067284
],
"byte_buffer": {
"array": "MSfCwA==",
"order": "LITTLE_ENDIAN"
}
}
]
},
{ …
```

Add cross encoder support

---

memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/MLMemoryManager.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemoryGetConversationsActionIT.java

1. Fix sort on get trace Api, in the case two traces with create time are `"create_time": "2023-12-05T05:14:42.823172Z"` and `"create_time": "2023-12-05T05:14:42.823833Z"` they are equally same date due to mapping field of [`create_time`](https://github.com/opensearch-project/ml-commons/blob/feature/agent_framework_dev/common/src/main/java/org/opensearch/ml/common/conversation/ConversationalIndexConstants.java#L97) is `date` not `date_nanos`, either we change type to `date_nanos` or add one more sort field.
2. Add refresh policy to update interaction api so that get conversation api will able to fetch latest data.
3. fix flaky test for conversation
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Fix sort on get trace API and flaky test of conversation

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Register Alerting and IndexMapping tool to ML plugin. Without registering tools to plugin ML agents will not be able to use Alerting and IndexMapping tool.

Register Alerting and IndexMapping tool to ML plugin

---

ml-algorithms/build.gradle

Fix Alerting tool runtime failure on ClassNotFoundException. 
```[2023-12-06T23:16:09,151][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [[dev-dsk-arjung-2c-3dee26a3.us-west-2.amazon.com](http://dev-dsk-arjung-2c-3dee26a3.us-west-2.amazon.com/)] fatal error in thread [opensearch[[dev-dsk-arjung-2c-3dee26a3.us-west-2.amazon.com](http://dev-dsk-arjung-2c-3dee26a3.us-west-2.amazon.com/)][opensearch_ml_predict][T#8]], exiting
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
at org.opensearch.commons.alerting.model.Table.<init>(Table.kt) ~[?:?]
at org.opensearch.ml.engine.tools.SearchAlertsTool.run(SearchAlertsTool.java:74) ~[?:?]
at org.opensearch.ml.engine.algorithms.agent.MLChatAgentRunner.lambda$runReAct$7(MLChatAgentRunner.java:512) ~[?:?]
at …
```

Fix Alerting tool runtime failure on ClassNotFoundException

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunnerTest.java

Handle empty memory type in flow agent configuration. Note that conversational agent still requires memory type to be defined.
Test agent configuration
```
POST _plugins/_ml/agents/_register
{
"name": "Test_Agent_For_RAG",
"type": "flow",
"description": "this is a test agent",
"app_type": "my app",
"tools": [
{
"type": "CatIndexTool",
"name": "CatIndexTool",
"description": "Use this tool to get OpenSearch index information: (health, status, index, uuid, primary count, replica count, docs.count, docs.deleted, store.size, primary.store.size).",
"include_output_in_agent_response": true
},
{
"type": "VectorDBTool",
"name": "PopulationDataTool",
"description": "Use this tool to fetch population information",
"model_id": "6nrN2YsBn9PZfduo9pOo",
"index": "my_test_data_1", …
```

Handle empty memory type in agent configuration

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/AbstractRetrieverTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/RAGTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/VectorDBTool.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

The RAGTool is added to support agent framework. It's tested to support the current two types of agent: flow and conversational(ReAct) agents. 
Here is the sample request to register RAGTools:
1. using flow agent:
```
POST /_plugins/_ml/agents/_register
{
"name": "Test_Agent_For_RagTool",
"type": "flow",
"description": "this is a test flow agent for RAG",
"tools": [
{
"type": "RAGTool",
"description": "A description of the tool",
"embedding_model_id": "<please input the embedding model id>",
"model_id": "<please input the llm model id>",
"index": "my_test_data",
"embedding_field": "embedding",
"source_field": [
"text"
],
"input": "${parameters.question}",
"prompt": "\n\nHuman:You are a professional data analysis. You will always answer question based on the given context …
```

Add RAGTool

---

.gitignore
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/CatIndexTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/CatIndexToolTests.java

Adds a CatIndexTool for the agent framework.
- This is an exact copy of the current class on `feature/agent_framework_dev` branch, except that I removed the `getName()` and `setName()` methods which duplicated the Lombok annotations.
Tests pass locally for this module, other failing tests related to memory are unassociated with this PR.
```
ml-commons git:(cat-index-tool) ./gradlew :opensearch-ml-algorithms:test
BUILD SUCCESSFUL in 1s
11 actionable tasks: 11 up-to-date
```
Fixes #1547 but on `main` this time.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/ …

Add CatIndexTool

---

plugin/src/main/java/org/opensearch/ml/action/agents/TransportRegisterAgentAction.java

Create agent with security plugin enabled results in 'no permission' error.
OpenSearch error log
```
[2023-12-13T16:21:02,446][WARN ][o.o.s.p.SecurityIndexAccessEvaluator] [90a57bde9d1b8d1c093c795895547181] indices:data/write/index for '.plugins-ml-agent' index is not allow
ed for a regular user
[2023-12-13T16:21:02,448][ERROR][o.o.m.a.a.TransportRegisterAgentAction] [90a57bde9d1b8d1c093c795895547181] Failed to index ML agent
```
Stashed thread context while writing to index. Validated change by deploying to local opensearch server
[[Create agent with security plugin enabled results in 'no permission']](https://github.com/opensearch-project/ml-commons/issues/1760)
For more …

Stash thread context when indexing agent configuration

---

common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentDeleteAction.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentDeleteRequest.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentGetAction.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentGetRequest.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLAgentGetResponse.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentDeleteActionTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentDeleteRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetActionTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/agents/DeleteAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/GetAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteAgentAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetAgentAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/agents/DeleteAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/agents/GetAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteAgentActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetAgentActionTests.java

Get and delete agent APIs

---

common/src/main/java/org/opensearch/ml/common/agent/LLMSpec.java
common/src/main/java/org/opensearch/ml/common/agent/MLAgent.java
common/src/main/java/org/opensearch/ml/common/agent/MLMemorySpec.java
common/src/main/java/org/opensearch/ml/common/agent/MLToolSpec.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLRegisterAgentAction.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLRegisterAgentRequest.java
common/src/main/java/org/opensearch/ml/common/transport/agent/MLRegisterAgentResponse.java
common/src/main/java/org/opensearch/ml/common/transport/undeploy/MLUndeployModelsResponse.java
common/src/test/java/org/opensearch/ml/common/agent/MLAgentTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLRegisterAgentActionTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLRegisterAgentRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLRegisterAgentResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/undeploy/MLUndeployModelsResponseTest.java

Add register agent action request/response 

add register action request/response

---

plugin/src/main/java/org/opensearch/ml/cluster/MLCommonsClusterEventListener.java

Fix partially response issue in profile API result. The root cause is when cluster nodes receive cluster change event(nodes add in this case), the added nodes will be put into the cache's target_worker_nodes blindly(without checking if the new nodes are eligible or not), and then trigger the auto redeploy job. The auto redeploy job can make sure the models are only deployed to eligible nodes and the deploy job can make sure the target_worker_nodes is correct.
If the added nodes put into cache, it won't get updated unless user performs model deploy, and for profile API and ML Dashboard(depends on profile API results), the target_worker_nodes and worker_nodes will show difference(target_worker_nodes has new nodes added even the node is not an eligible nodes for model running), and the model …

Fix partially response issue in profile API result

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLReActAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutorTest.java

Add agent runner interface to provide common interface for all agents. Agent runner interface defines the `run` function definition for agent runner.
Added unit test for Agent executor.

Add agent runner interface and added unit test

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java

Chatbot now retrieve all the interactions every time doing a `execute`. There are some drawbacks:
1. When the conversation grows larger and larger, it costs a lot to fetch all the interactions. 
2. Chatbot will always try to get the latest interactions once `execute` API returns but in opensearch there is a refresh delay which will make the result staled when calling a search API.
In order to address the issues above, Chatbot need an interaction id for the ongoing interaction.
1. Add `parent_interaction_id` into response of execute API.
For more information on following Developer Certificate of Origin and signing off your commits, please …

feat: add interaction id into execute response

---

common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentDeleteRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetResponseTest.java

increase test coverage for `MLAgentDeleteRequest`, `MLAgentGetRequest`,` MLAgentGetResponse` to 100%

Add tests for MLAgent Get and Delete

---

common/src/main/java/org/opensearch/ml/common/transport/update_cache/MLUpdateModelCacheNodeRequest.java

After backported #1673 to 2.x it will cause java compile failed. This PR should fix this.

Fix compilation when backport #1673

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/AbstractRetrieverTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/AgentTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/CatIndexTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/IndexMappingTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MLModelTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MathTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/NeuralSparseTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/PainlessScriptTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/RAGTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/SearchAlertsTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/VectorDBTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/VisualizationsTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/AbstractRetrieverToolTests.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/IndexMappingToolTests.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
spi/build.gradle
spi/src/main/java/org/opensearch/ml/common/spi/tools/AbstractTool.java
spi/src/test/java/org.opensearch.ml.common.spi.tools/AbstractToolTest.java

Build Abstract tool to simplify tool creation and remove boilerplate tool management implementations to abstract super class. Refactored existing tools to make use of `AbstractTool`.
Tools that extends `AbstractTool` would only need to implement `run` and `validate` methods.

Add abstract tool support

---

plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java

Change model auto redeploy enabled to true by default
Change model auto redeploy enabled to true by default

Change model auto redeploy enabled to true by default

---

plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/connector/DeleteConnectorTransportActionTests.java

When connector is already in use in a model, deleting connector will now result in 409 CONFLICT
closes #1716 

Fix: RestStatus 500 returned ml validation

---

memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionRequest.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionRequestTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/memory/MLMemoryManagerTests.java

1. Add interaction into the response of execute API.
2. Fix the issue that response won't be updated because it is not included in allowedList of `UpdateInteractionRequest`

feat: add interaction id into execute response(#1788)

---

memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/indices/MLIndicesHandler.java

add the auto expand replica setting to memory indices. 
CI would still fail due to the same test coverage issue in https://github.com/opensearch-project/ml-commons/pull/1800

add auto expand replica settings to memories

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

backport PR #1691 to 2.x
---------

[Backport 2.x] support charset input params and change default charset as utf8 (#1691)

---

plugin/src/main/java/org/opensearch/ml/cluster/DiscoveryNodeHelper.java
plugin/src/test/java/org/opensearch/ml/cluster/DiscoveryNodeHelperTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

If a node has both `data` and `ml` role, the eligible nodes will have duplicate node ids. Then deploy model will fail on the duplicate node.

fix duplicate node if node has both data and ml role

---

plugin/src/test/java/org/opensearch/ml/rest/MLModelGroupRestIT.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

This "password" triggered some security concerns. Randomizing this variable to avoid confusion as this is not password to any real resources. This PR can be used to verify the fix of the security concern. 

fix the hardcode password in IT

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/indices/MLIndicesHandler.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/indices/MLIndicesHandlerTest.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateConnectorActionTests.java

Fix the issue in https://github.com/opensearch-project/ml-commons/issues/1851, and update the url in the RestUpdateConnector UT.
CI pass depends on the fix in https://github.com/opensearch-project/ml-commons/pull/1846. 
CI failed due to:
Tests with failures:
- org.opensearch.ml.rest.RestMLRemoteInferenceIT.testOpenAIEditsModel
- org.opensearch.ml.rest.RestMLRemoteInferenceIT.testPredictRemoteModel
~~~
ERROR][o.o.m.e.a.r.RemoteModel  ] [integTest-0] Failed to call remote model.
org.opensearch.OpenSearchStatusException: Error from remote service: {
"error": {
"message": "The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations",
"type": "invalid_request_error",
"param": null,
"code": "model_not_found"
}
}
~~~
[List any issues this PR …

fix race confition in index initialization and RestUpdateConnector UT

---

build.gradle
ml-algorithms/build.gradle
plugin/build.gradle

Add kotlin stblib dependency for SearchAlertTool, issue comes from skills repo and need to fix in ml-commons. The reason of this fix described in [issue](https://github.com/opensearch-project/skills/issues/116) 
https://github.com/opensearch-project/skills/issues/116

Add kotlin stblib dependency for SearchAlertTool

---

client/build.gradle
common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/src/test/java/org/opensearch/ml/bwc/MLCommonsBackwardsCompatibilityRestTestCase.java

Bump Mockito dependencies

---

ml-algorithms/build.gradle

There are flaky tests failing on neural search plugin that need a deployed model to be used. But the pytorch model is failing to deploy due to EngineException failure with the error "Failed to load PyTorch native library". 
Since pytorch-engine can load older version of pytorch native library, it could be possible a different version is being loaded than the expected one "pytorch-engine-0.21.0.jar". Here, we are explicitly specifying the required package version to override it to resolve the issue.
Fixes the flaky test: https://github.com/opensearch-project/ml-commons/issues/1843
For more information on following Developer Certificate of Origin and signing off your commits, …

fix failing flaky tests due to pytorch library not available for dependency plugins

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchConnectorActionTests.java

When connector is not created yet, return an empty search response instead of a broken 404 with cryptic index not found message.
More description in: https://github.com/opensearch-project/ml-commons/issues/1787
Minor additional issues fixed:
- Ability to run integTest with cluster debugging. 
For example:
`./gradlew :opensearch-ml-plugin:integTest --tests org.opensearch.ml.rest.RestMLSearchConnectorActionIT.testSearchConnector_beforeConnectorCreated -Dcluster.debug=1`
- Show log output during integTest
[[List any issues this PR will resolve]](https://github.com/opensearch-project/ml-commons/issues/1787)
- [ x] New functionality includes testing.
- [x ] All tests pass
- [x ] New functionality has been documented.
- [x ] New functionality has javadoc added
- [ x] Commits are signed per the …

Issue 1787 fixing connector endpoint returns index not found

---

plugin/src/test/java/org/opensearch/ml/bwc/MLCommonsBackwardsCompatibilityRestTestCase.java

Backport of https://github.com/opensearch-project/ml-commons/pull/1711 to `2.x` (the mockito deps were updated in https://github.com/opensearch-project/ml-commons/pull/1697 backport proactively)
Part of https://github.com/opensearch-project/OpenSearch/issues/10334

[Backport] [2.x] Bump Mockito dependencies

---

plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/model_group/SearchModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/SearchModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/SearchTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/action/handler/MLSearchHandlerTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelActionIT.java
plugin/src/test/java/org/opensearch/ml/utils/RestActionUtilsTests.java

When model/model group/task is not created yet, return an empty search response instead of a broken 404 with cryptic index not found message.
More description in:
https://github.com/opensearch-project/ml-commons/issues/1878
https://github.com/opensearch-project/ml-commons/issues/1879
https://github.com/opensearch-project/ml-commons/issues/1880
https://github.com/opensearch-project/ml-commons/issues/1878
https://github.com/opensearch-project/ml-commons/issues/1879
https://github.com/opensearch-project/ml-commons/issues/1880
- [X ] New functionality includes testing.
- [ X] All tests pass
- [X ] New functionality has javadoc added
- [ X] Commits are signed per the DCO using --signoff 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Issue 1878/1879/1880 fixing index not found for model group/model/tasks

---

common/src/main/java/org/opensearch/ml/common/transport/tools/MLToolsListResponse.java
common/src/test/java/org/opensearch/ml/common/transport/tools/MLToolsListResponseTests.java
plugin/src/main/java/org/opensearch/ml/tools/GetToolTransportAction.java

Adjust ListTool response format to fix `Request failed to get to the server (status code: 502)` error when calling ListTool API
Also, adjust exception type for GetTool when there's no such tool. Now it returns 404 when no tool found
```
{
"error": {
{
"type": "status_exception",
"reason": "Failed to find tool information with the provided tool name: CatIndexTo"
}
],
"type": "status_exception",
"reason": "Failed to find tool information with the provided tool name: CatIndexTo"
},
"status": 404
}
``` …

Adjust ListTool response format

---

plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/utils/RestActionUtilsTests.java

changes to hidden model code to use OPENDISTRO_SECURITY_USER instad of ssl principal

changes to hidden model code to use OPENDISTRO_SECURITY_USER instad of ssl principal

---

plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java
plugin/src/test/java/org/opensearch/ml/utils/RestActionUtilsTests.java

(cherry picked from commit de59efc80d2a4b53917edfd941ba14bf99956639)
Backport https://github.com/opensearch-project/ml-commons/commit/de59efc80d2a4b53917edfd941ba14bf99956639 from https://github.com/opensearch-project/ml-commons/pull/1897
* changes to hidden model code to use OPENDISTRO_SECURITY_USER instad of ssl principal

[Backport 2.x] changes to hidden model code to use OPENDISTRO_SECURITY_USER instad of ssl principal (#1897)

---

plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelOnNodeAction.java

stash thread context before running forward action

---

plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java

change searchResponse method to fix breaking change in managed service

change searchResponse method to fix breaking change in managed service

---

plugin/src/main/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java

Under intensive prediction tasks, the model not deployed error can happen occasionally like below: 
```
[ERROR] Cannot execute-test. Error in load generator [0]
Cannot run task [bulk]: Request returned an error. Error type: bulk, Description: HTTP status: 400, message: Model not ready yet. Please run this first: POST /_plugins/_ml/models/Cc36M40Bxy1iWleaz3Bl/_deploy
``` 
The reason is the SyncUpJob cleans timed out deploying model tasks from all tasks not filtering prediction tasks, and a prediction task can be removed from cache when prediction is done. And the corresponding taskCache is cleared, the syncUpJob will encounter NPE and return error response for gatherInfoRequest, and in this case, SyncUpJob sends clearRoutingTable request and clear all routingTable info, the next prediction …

Fix model not deploy issue under intensive prediction tasks

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/CatIndexTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/IndexMappingTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/IndexMappingToolTests.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Adds an IndexMappingTool.   See previous dev branch PR: #1609.  
It looks like it's part of pending PR #1812 but needed to unblock end-to-end testing.

Add IndexMapping Tool

---

docs/tutorials/aws/semantic_search_with_openai_embedding_model.md

add tutorial doc for semantic search with OpenAI embedding model

---

memory/src/main/java/org/opensearch/ml/memory/ConversationalMemoryHandler.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandler.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/UpdateConversationTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/UpdateInteractionTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexTests.java
memory/src/test/java/org/opensearch/ml/memory/index/InteractionsIndexTests.java
memory/src/test/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandlerTests.java

This PR is to add user based permission check that addresses concerns in https://github.com/opensearch-project/ml-commons/issues/1901. 
The permission checks are strictly applied to all interactions/conversations. 
The PR is verified using two different login users and ensure they don't have access to each others's data
More tests cases added and Rebased to latest main branch.
[[List any issues this PR will resolve](https://github.com/opensearch-project/ml-commons/issues/1901)]
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-c …

add more user based permission check in Memory

---

plugin/src/main/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeAction.java

During intensive benchmark test, sometimes can get below error:
```
[ERROR] Cannot execute-test. Error in load generator [3]
Cannot run task [bulk]: Request returned an error. Error type: bulk, Description: HTTP status: 400, message: Model not ready yet. Please run this first: POST /_plugins/_ml/models/z7cLVI0BDnAEuuAYMD8k/_deploy
```
Even after this fix: https://github.com/opensearch-project/ml-commons/pull/1903, after investigation found sometimes taskId is null like below:
```
... c055db11-f6ff-49c3-ae7b-ae597959756e,1db175b1-1845-407e-8ef5-2ec00a655677,edf5815a-e061-4d3f-945f-fee5c4f29821,c021b4b9-764f-4ed8-b0bb-d57e3ed2d9c6,null
```
So adding this null check to by pass this issue.
NA
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Fix null taskId causing model undeploy issue

---

plugin/src/main/java/org/opensearch/ml/breaker/MemoryCircuitBreaker.java
plugin/src/test/java/org/opensearch/ml/breaker/MemoryCircuitBreakerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLMemoryCircuitBreakerIT.java

In skills repo we have a flaky test of triggering the memory circuit breaker ([ref](https://github.com/opensearch-project/skills/actions/runs/7660776972/job/20878791576?pr=148)). We try to increase the threshold value, but the issue still exists. Then we find there is a bug in `MemoryCircuitBreaker`. It use `super.threshold` to check whether CB is open. But if we update the cluster settings, `jvmHeapMemThreshold` gets updated.
In this PR I fix the bug to use `jvmHeapMemThreshold` to check CB. Add more UT and IT for this. …

[BUG FIX] Fix updating plugins.ml_commons.jvm_heap_memory_threshold takes no effect

---

.github/CODEOWNERS

This is to add @samuel-oci  to maintainer. Missing CODEWONERS file in last PR https://github.com/opensearch-project/ml-commons/pull/1937

add maintainer

---

.github/CODEOWNERS

[Backport to 2.x] add maintainer (#1951)

---

ml-algorithms/build.gradle
plugin/build.gradle
plugin/src/main/plugin-metadata/plugin-security.policy
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeployModelActionIT.java

Fixes an issue where zip files in model_cache are not getting deleted.
#844 
- [x ] All tests pass
- [ x] Commits are signed per the DCO using --signoff 

Add accessUserInformation to the plugin security policy.  (Issue # 844)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java

Fix string.format wrong parameter position, the Locale should be first parameter

Fix string.format wrong parameter position

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

The tool's parameters configured in agent registration are missing when conversational agent runs the tool.
Tested in my local environment.

bug fix - tool parameters missing

---

memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
memory/src/test/java/org/opensearch/ml/memory/index/InteractionsIndexTests.java

When deleting a memory with no interactions, the response throws an error from the bulk delete interactions which is not expected. 
This PR fixes the bug that when deleting an empty memory, the process should go through and delete it successfully.
Before the change: 
~~~
POST /_plugins/_ml/memory
{
"name": "Create a new Memory"
}
#Response
{
"memory_id": "xxxxxxxxx"
}
DELETE /_plugins/_ml/memory/xxxxxxxxx
{
"error": {
{
"type": "action_request_validation_exception",
"reason": "Validation Failed: 1: no requests added;"
}
],
"type": "action_request_validation_exception",
"reason": "Validation Failed: 1: no requests added;"
},
"status": 400
}
~~~
After this change, the empty memory is deleted successfully.
~~~
DELETE /_plugins/_ml/memory/xxxxxxxxx
{
"success": true
}
~~~ …

fix bug in delete empty memory

---

common/src/main/java/org/opensearch/ml/common/connector/functions/preprocess/BedrockEmbeddingPreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/functions/preprocess/CohereEmbeddingPreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/functions/preprocess/ConnectorPreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/functions/preprocess/OpenAIEmbeddingPreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/connector/functions/preprocess/DefaultPreProcessFunctionTest.java
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java

Escape input data to solve invalid payload error.

escape input data

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java

fix error message for deploy model and model hash content.
After changing error, when I try:
```
{
"name": "all-MiniLM-L6-v2",
"version": "1.0.0",
"model_format": "TORCH_SCRIPT",
"model_config": {
"model_type": "bert",
"embedding_dimension": 384,
"framework_type": "sentence_transformers"
},
"url": "https://github.com/opensearch-project/ml-commons/raw/2.x/ml-algorithms/src/test/resources/org/opensearch/ml/engine/algorithms/text_embedding/all-MiniLM-L6-v2_torchscript_sentence-transformer.zip?raw=true"
}
```
Then get task returns
```
{
"task_type": "REGISTER_MODEL",
"function_name": "TEXT_EMBEDDING",
"state": "FAILED",
"worker_node": [
"YGlxNankSXao_Ztt5VSprA"
],
"create_time": 1706663983561,
"last_update_time": 1706663991558,
"error": "Hash code need to be …
```

fix error message

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java

do not allow non super admin users to undeploy hidden models

do not allow non super admin users to undeploy hidden models

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

This PR should:
1. Hide the error stack tracing when we expected no model controller existed for a model.
2. Fix the rate limiter performance on the multi-node cluster.

Fix for controller error stack trace and tokenbucket

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteAgentAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLExecuteAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetAgentAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterAgentAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLSearchAgentAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/test/java/org/opensearch/ml/rest/RegisterAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteAgentActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLExecuteActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetAgentActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchAgentActionTests.java

Add a setting to enable/disable agent framework feature. Currently the setting is set to false by default.

agent framework disable/enable flag

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/IndexMappingTool.java

Updates the description of the IndexMappingTool to include the expected output format. This improves LLM performance in understanding the tool output.

Update IndexMappingTool Description

---

docs/remote_inference_blueprints/aleph_alpha_connector_luminous_base_embedding_blueprint.md

Adding an AI connector blueprint for the Aleph Alpha Luminous-Base Embedding Model.
I'm proposing to add an AI connector blueprint for the [Aleph Alpha Luminous-Base Embedding Model](https://docs.aleph-alpha.com/api/semantic-embed/) to the current collection of remote inference blueprints in [OpenSearch ML Commons](https://github.com/opensearch-project/ml-commons/tree/2.x/docs/remote_inference_blueprints).
This model is particularly effective for German language applications, providing nuanced and contextually relevant embeddings. Given the increasing demand for robust language model solutions in different languages, integrating this model could significantly enhance your offerings for German-language processing tasks.
[Issue 1925](https://github.com/opensearch-project/ml-commons/issues/19 …

AI connector blueprint for the Aleph Alpha Luminous-Base Embedding Model

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

Add memory id and parent interaction id in response.
An example,
```
The request,
POST /_plugins/_ml/agents/ZtW3XI0BS7ZuQOvZvMqS/_execute
{
"question": "how many index I have?"
}
}
Old response,
{
"inference_results": [
{
"output": [
{
"name": "response",
"dataAsMap": {
"response": "Unfortunately, without access to the tools, I do not have enough information to determine the number of indexes you currently have.",
"additional_info": {}
}
}
]
}
]
}
New response,
{
"inference_results": [
{
"output": [
{
"name": "memory_id",
"result": "ZujBbY0BRiMrBD-_tYrq"
},
{
"name": "parent_interaction_id",
"result": "Z-jBbY0BRiMrBD-_tooF"
},
{
"name": "response",
"dataAsMap": {
"response": "Unfortunately, without access to the tools, I do not have enough information to determine the …
```

add memory id and interation id for non-verbose

---

search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAResponseProcessor.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/DefaultLlmImpl.java

Scrub sensitive log messages.
#1965 
- [ x] Commits are signed per the DCO using --signoff 

Remove logging of sensitive chat history. [issue 1965]

---

build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle

There is a guava vulnerability https://github.com/opensearch-project/ml-commons/issues/1862.
There are 2 use cases in the code base that use older version of guava:
1. A dependency of Gradle plugin. spotless.
2. A dependency of Gradle core plugin checksytle.
Also, the guava dependencies are not consistent in ML-Commons. The latest version used is 32.1.2.
So to address the problems, this PR set dependency resolution strategy to use guava version 32.1.2-jre for all Gradle projects.
Verified that after this PR, my local cache under ./gradle/caches/modules-2/files-2.1/com.google.guava only contains the 32.1.2 version. 
Also after the code change, it can be seen that only the newer version of guava is being used.
By submitting this pull request, I confirm …

fix CVE-2023-2976 and upgrade guava to be consistent

---

build.gradle

Upgrade the org.apache.commons-commons-compress from 1.22 to 1.25 to resolve CVE. https://github.com/opensearch-project/ml-commons/issues/1865

fix CVE-2023-42503 due to djl models

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

The agent sends execution response after finished saving last trace and final answer.
https://github.com/opensearch-project/ml-commons/issues/1894

send agent execution response after saving memory

---

build.gradle
memory/build.gradle

Fix CVE-2023-42503 and upgrade the org.apache.httpcomponents to 5.2.2 to mitigate the delta between main and 2.x

[Backport] fix CVE-2023-42503 due to djl models (#2011)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunnerTest.java

Updating memory with all tool output results in update failure for larger tool responses. To solve the problem, memory will be optionally updated for tools with includeOutputInAgentResponse field set.

Update memory if tool output needs to be included in response

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

Conversational agent pass user original question as input to the tool that sets useoriginalinput flag as true.
The RAG tool can parse the output from LLM, actually the RAG tool needs user original question to search vector DB.

tool uses original input

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java

disable dynamic mapping for config index. Setting dynamic mapping to "strict" prevents from writing new fields into the index.

disable dynamic mapping for config index

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

Backport https://github.com/opensearch-project/ml-commons/pull/1999 from main to 2.x.

send agent execution response after saving memory (#1999)

---

memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequestTests.java

This is to address the Null value of the "name" in create a memory in the exceptions described here https://github.com/opensearch-project/ml-commons/issues/1997. They should be all handled with 400 error code.
Before this change: 
~~~
POST /_plugins/_ml/memory
{
"name": null
}
Response:
{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Can't get text on a VALUE_NULL at 2:8"}],"type":"illegal_state_exception","reason":"Can't get text on a VALUE_NULL at 2:8"},"status":500}
~~~
~~~
POST /_plugins/_ml/memory
{
"name": 999999999999999999999.....
}
Response:
{"error":{"root_cause":[{"type":"stream_constraints_exception","reason":"Number length (5628) exceeds the maximum length (1000)"}],"type":"stream_constraints_exception","reason":"Number length (5628) exceeds the maximum …

adds inputs validation for create memory

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MLModelTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/MLModelToolTests.java

Current MLModelTool hard code to fetch the `response` field from response body. However, in other non-LLM cases or non-Claude LLM services, we can not assume all of them use `response` keyword.
This PR makes response_field customizable in MLModelTool. If not provided, it will use `response` by default. This will make current API invokation behavior consistent.

enhance: make response_field customizable in MLModelTool

---

common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java

Fix some edge case can't be handled: `"[]\""`

fix edge case for validate json method

---

docs/remote_inference_blueprints/azure_openai_connector_chat_blueprint.md
docs/remote_inference_blueprints/azure_openai_connector_embedding_blueprint.md

Add connector blueprint for Azure OpenAI Embedding and Chat model.
~~**PLEASE NOTE** the blueprints in this PR contains only self-managed OpenSearch version.~~
#1367 

Add connector blueprint for Azure OpenAI Embedding and Chat model

---

common/src/main/java/org/opensearch/ml/common/connector/functions/preprocess/ConnectorPreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/functions/preprocess/DefaultPreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/functions/preprocess/RemoteInferencePreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/connector/functions/preprocess/RemoteInferencePreProcessFunctionTest.java
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/ScriptUtils.java

Add escape method for process function to make it easier to escape string in pre/post process function.

add escape method for process function

---

memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
memory/src/test/java/org/opensearch/ml/memory/ConversationalMemoryHandlerITTests.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexITTests.java

Based on the pen tests results. All the requests that fails the authentication in Memory/ConversationalSearch should return 4xx code. Currently the error code 500 internal service error is returned when such requests come.
This PR updates the error code for unauthorized requests. https://github.com/opensearch-project/ml-commons/issues/1997

update Unthrotized error code to 401

---

docs/remote_inference_blueprints/cohere_connector_chat_blueprint.md

- Adds a new Cohere Chat connector blueprint
N/A
No new functionality, just new docs 

Add Cohere Chat blueprint with RAG

---

docs/tutorials/agent_framework/RAG_with_conversational_flow_agent.md
docs/tutorials/conversational_search/conversational_search_with_Cohere_Command.md

1. add tutorial for how to use Cohere Command model with RAG pipeline
2. add tutorial for how to build RAG with Bedrock Claude model and conversational flow agent

add tutorial for conversational search

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/MLMemoryManager.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/AgentUtilsTest.java

Enhance parsing model response function for more edge cases
1. Model output is invalid json 
2. Model output has no valid field.

enhance parsing model response function for more edge cases

---

search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAResponseProcessor.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/client/ConversationalMemoryClient.java

Pen testers still pointed out "Finding: Search Pipeline / Response Processor Logs Contains Sensitive Data" not resolved. This PR is to delete the leftovers in the sensitive logs required by the pen tests. 

remove more sensitive logs in pipeline/responseProcessor logs

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java

This PR re-ordered the FunctionName by the time we introduced them to ensure backward compatibility on 2.11.
This will partly resolved #1838

Re-order the FunctionName enum class to ensure bwc in 2.11

---

common/src/main/java/org/opensearch/ml/common/transport/deploy/MLDeployModelRequest.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java

enable auto redeploy for hidden model

enable auto redeploy for hidden model

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/AgentUtilsTest.java

Chat agent runner will pass a string input json to tool , for example `"{'detectorName': 'abc', 'indices': 'sample-data' }"`, then the tool side need to parse the json string to Map, for example [PPLTool](https://github.com/opensearch-project/skills/blob/main/src/main/java/org/opensearch/agent/tools/PPLTool.java#L452). 
This PR parse the tool input json string to Map and put the parameters to tool's parameter map. 

parse tool input to map

---

memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java

Set the number of ml system index primary shards to 1

Set the number of ml system index primary shards to 1

---

docs/tutorials/semantic_search/conversation_search_with_byte_quantized_vector.md

add tutorial for semantic search with byte quantized vector and Cohere embedding model

---

common/src/main/java/org/opensearch/ml/common/dataset/AsymmetricTextEmbeddingParameters.java
common/src/main/java/org/opensearch/ml/common/model/TextEmbeddingModelConfig.java
common/src/test/java/org/opensearch/ml/common/dataset/AsymmetricTextEmbeddingParametersTest.java
common/src/test/java/org/opensearch/ml/common/input/nlp/TextDocsMLInputTest.java
common/src/test/java/org/opensearch/ml/common/model/TextEmbeddingModelConfigTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/TextEmbeddingModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingDenseModelTest.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRegisterModelActionTests.java

* add support for asymmetric embeddings
Signed-off-by: br3no <breno@veltefaria.de>
* fix NPE with sparse models
Signed-off-by: br3no <breno@veltefaria.de>
* after review
Signed-off-by: br3no <breno@veltefaria.de>
* improving code coverage
Signed-off-by: br3no <breno@veltefaria.de>
* improving javadocs
Signed-off-by: br3no <breno@veltefaria.de>
* adding unit-test for AsymmetricTextEmbeddingParameters
Signed-off-by: br3no <breno@veltefaria.de>
* after latest review
Signed-off-by: br3no <breno@veltefaria.de>
---------
Signed-off-by: br3no <breno@veltefaria.de>
(cherry picked from commit 771dbb94a9ab2f9da55dfd408e54874af76787a4)
By submitting this pull request, I confirm that my contribution is made under the terms of …

[Backport 2.x] 1799 asymmetric embeddings (#2123)

---

docs/remote_inference_blueprints/cohere_connector_chat_blueprint.md

fix cohere chat blueprint

---

common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java

This backporting PR: `https://github.com/opensearch-project/ml-commons/pull/1273/files#diff-b7237072c9ed7ab5cd15e7df01af432008783bc04031185032b241fb1169be36` didn't add the actual changes of 2.x branch to main for MLCreateConnectorInputTests.java

backporting from 2.x

---

build.gradle
ml-algorithms/build.gradle
plugin/build.gradle

Bump common-compress package to 1.26 to fix CVE

Bump common-compress package to fix CVE

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutorTest.java

Fix npe issue.
```
POST /_plugins/_ml/agents/ekQGzY0BLfzPq4u31Dfz/_execute 
{
"parameter": { }
}
Response,
"{\"error\":{\"reason\":\"System Error\",\"details\":\"Cannot invoke \\\"org.opensearch.ml.common.dataset.remote.RemoteInferenceInputDataSet.getParameters()\\\" because \\\"inputDataSet\\\" is null\",\"type\":\"NullPointerException\"},\"status\":500}"
```

fix npe issue

---

plugin/src/main/java/org/opensearch/ml/rest/RestMLExecuteAction.java
plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessage.java

Fix the error code when getting the opensearch exception.

fix error code

---

common/src/main/java/org/opensearch/ml/common/MLCommonsClassLoader.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensor.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngineClassLoader.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModelExecute.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLConversationalFlowAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLFlowAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/rcf/RCFModelSerDeSer.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/FileUtils.java
plugin/src/main/java/org/opensearch/ml/breaker/DiskCircuitBreaker.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java

Suppress [removal] AccessController in java.security has been deprecated and marked for removal
Closes https://github.com/opensearch-project/ml-commons/issues/1590

Suppress [removal] AccessController in java.security has been deprecated and marked for removal

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java

add remote predict thread pool

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/model/Guardrail.java
common/src/main/java/org/opensearch/ml/common/model/Guardrails.java
common/src/main/java/org/opensearch/ml/common/model/MLGuard.java
common/src/main/java/org/opensearch/ml/common/model/StopWords.java
common/src/main/java/org/opensearch/ml/common/transport/model/MLUpdateModelInput.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/test/java/org/opensearch/ml/common/model/GuardrailTests.java
common/src/test/java/org/opensearch/ml/common/model/GuardrailsTests.java
common/src/test/java/org/opensearch/ml/common/model/MLGuardTests.java
common/src/test/java/org/opensearch/ml/common/model/StopWordsTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Add guardrails for remote model input and output. We support two ways stop words and regex.
Example:
```
POST /_plugins/_ml/models/LHkGS44BStH5-WXNbXxT/_predict
{
"prompt": "\n\nHuman:this is a test of <stop words>\n\nnAssistant:"
}
}
The response
{
"error": {
{
"type": "illegal_argument_exception",
"reason": "guardrails triggered for user input"
}
],
"type": "illegal_argument_exception",
"reason": "guardrails triggered for user input"
},
"status": 400
}
``` …

Guardrails for remote model input and output

---

plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessage.java
plugin/src/test/java/org/opensearch/ml/utils/error/ErrorMessageTests.java

Prevent exposing internal ip addresses.
```
{
"error": {
......,
"reason": "[opensearch-cluster-master-1][192.168.31.112:9300] Node not connected"
},
"status": 500
}
```

prevent exposing internal ip

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
common/src/main/java/org/opensearch/ml/common/MLModel.java
common/src/main/java/org/opensearch/ml/common/dataset/MLInputDataType.java
common/src/main/java/org/opensearch/ml/common/dataset/QuestionAnsweringInputDataSet.java
common/src/main/java/org/opensearch/ml/common/input/MLInput.java
common/src/main/java/org/opensearch/ml/common/input/nlp/QuestionAnsweringMLInput.java
common/src/main/java/org/opensearch/ml/common/input/nlp/TextDocsMLInput.java
common/src/main/java/org/opensearch/ml/common/input/nlp/TextSimilarityMLInput.java
common/src/main/java/org/opensearch/ml/common/model/QuestionAnsweringModelConfig.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensor.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/main/java/org/opensearch/ml/common/transport/upload_chunk/MLRegisterModelMetaInput.java
common/src/test/java/org/opensearch/ml/common/MLCommonsClassLoaderTests.java
common/src/test/java/org/opensearch/ml/common/dataset/QuestionAnsweringInputDatasetTest.java
common/src/test/java/org/opensearch/ml/common/input/nlp/QuestionAnsweringMLInputTest.java
common/src/test/java/org/opensearch/ml/common/model/QuestionAnsweringModelConfigTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringTranslator.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModelTest.java

support question answering model. This PR adds question answering model to the list of existing list of models supported by ml-commons. It expects question and context and gives the answer based on the context provides. Below is a sample predict API request to QA model and its expected output
```
POST /_plugins/_ml/models/m6LBVI4BuIvXgszWP7KN/_predict
{
"question": "Where do I live",
"context":  "I am Clara. I live in Texas."
}
```
```
// Response
{
"inference_results": [
{
"output": [
{
"result": "Texas"
}
]
}
]
}
```
https://github.com/opensearch-project/ml-commons/issues/1873
For more information on following Developer Certificate of Origin and signing off your commits, …

support question answering model

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java

fix json error

---

plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java

The old test of testExecuteTask_OnLocalNode_RemoteModel is not valid anymore after the auto deployment. This new test replace the old one with newest auto deployment.

update remote model auto deploy tests in predict runner

---

plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/prediction/TransportPredictionTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRegisterModelActionTests.java

add a setting to enable/disable local model inference
https://github.com/opensearch-project/ml-commons/issues/2164

add local inference enabling/disabling setting

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

On very rare occasion the memory circuit breaker triggers when registering a remote model. Before this PR, this would throw an exception, and because registerRemoteModel is a actionListener-based method, the error would be dropped and you get a 500 (internal server error) back. This PR moves the circuit breaker check inside the try block so that the exception is caught and 'actionListen'ed.

fix remote register model / circuit breaker 500

---

common/src/main/java/org/opensearch/ml/common/FunctionName.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

Add Security IT tests for Agent Framework. The tests all verified by a local 2.13 cluster.

add agent framework security it tests

---

common/src/main/java/org/opensearch/ml/common/model/MLGuard.java

restrict stash context only for stop words system index

---

plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java

Checking if the model has auto-deploy enabled at the model level. If true, go ahead with auto deploy. Otherwise return 400 illegal_argument_exception with message asking Users to deploy model first. 
If the deploy_setting is null in the Model, by default we treat it as true.
~~~
PUT /_plugins/_ml/models/qPUJgo4BHjpQDZnR5sw4
{
"deploy_setting": {"is_auto_deploy_enabled": false}
}
POST /_plugins/_ml/models/qPUJgo4BHjpQDZnR5sw4/_predict {...}
{
"error": {
{
"type": "illegal_argument_exception",
"reason": "Model not ready yet. Please run this first: POST /_plugins/_ml/models/qPUJgo4BHjpQDZnR5sw4/_deploy"
}
],
"type": "illegal_argument_exception",
"reason": "Model not ready yet. Please run this first: POST /_plugins/_ml/models/qPUJgo4BHjpQDZnR5sw4/_deploy"
},
"status": 400
} …

check model auto deploy

---

plugin/src/main/java/org/opensearch/ml/cluster/DiscoveryNodeHelper.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/cluster/DiscoveryNodeHelperTests.java

Take agent out of the scope of only_run_on_ml_node flag.

agent out of the setting only_run_on_ml_node

---

common/src/main/java/org/opensearch/ml/common/model/MLGuard.java
common/src/test/java/org/opensearch/ml/common/model/MLGuardTests.java

Support register model with empty guardrails content. Currently we will get npe with empty guardrails when predicting.
```
POST /_plugins/_ml/models/_register?deploy=true
{
"name": "remote model",
"model_group_id": "<group_id>",
"connector_id": "<connector_id>",
"guardrails": {
}
}
```

guardrails npe

---

plugin/build.gradle

1. Remove checkstyle in favor of spotless.
2. resolve Guava dependency conflicts between com.google.guava:guava:32.0.1-jre and com.google.guava:guava:32.1.2-jre.

remove checkstyle

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java

We found connector can use subfield of `secretArn` (e.g. `secretArn.key`) to bypass extraction of credential from AWS, so we need to filter out any key string which tries to imitate the subfield of the `secretArn` of the credential map to avoid security issue. UT has added.

Fix connector can use subfield of secrectArn to bypass extraction of credential from AWS

---

search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAResponseProcessor.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/client/ConversationalMemoryClient.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/client/MachineLearningInternalClient.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/DefaultLlmImpl.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/llm/Llm.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeQAResponseProcessorTests.java
search-processors/src/test/java/org/opensearch/searchpipelines/questionanswering/generative/llm/DefaultLlmImplTests.java

Use the async version of the search pipeline process to avoid blocking (remote) calls.
Original bug - https://github.com/opensearch-project/OpenSearch/issues/10248. 
- #2334 
- [x ] New functionality includes testing.
- [x ] All tests pass
- [x ] Commits are signed per the DCO using --signoff 

Migrate RAG pipeline to async processing.

---

plugin/src/main/java/org/opensearch/ml/rest/RestMLProfileAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLStatsAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLProfileActionTests.java

[
For a newly created cluster stats api response:
```
{
"ml_model_index_status": "non-existent",
"ml_connector_index_status": "non-existent",
"ml_model_count": 0,
"ml_controller_index_status": "non-existent",
"ml_task_index_status": "non-existent",
"ml_config_index_status": "green",
"ml_connector_count": 0,
"nodes": {
"TLaJyhhfS0KeqLbdTRMJSA": {
"ml_request_count": 0,
"ml_executing_task_count": 0,
"ml_deployed_model_count": 0,
"ml_circuit_breaker_trigger_count": 0,
"ml_jvm_heap_usage": 27,
"ml_failure_count": 0,
"algorithms": {},
"models": {}
}
}
}
```
Profile api response:
```
{}
```
]
For more information on following Developer …

not sending failure message when model index isn't present

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/TextEmbeddingModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingDenseModelTest.java

The missing result filter is added to the code path where it was forgotten in an earlier PR.
#2366

Added missing result filter to inference

---

common/src/main/java/org/opensearch/ml/common/output/model/MLResultDataType.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/processor/InferenceProcessorAttributes.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceIngestProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/ModelExecutor.java
plugin/src/test/java/org/opensearch/ml/processor/InferenceProcessorAttributesTests.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorFactoryTests.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceIngestProcessorIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java
plugin/src/yamlRestTest/java/org/opensearch/ml/plugin/PluginClientYamlTestSuiteIT.java
plugin/src/yamlRestTest/resources/rest-api-spec/test/10_basic.yml
plugin/src/yamlRestTest/resources/rest-api-spec/test/20_inference_ingest_processor.yml

manually backport to 2.x because of known http package conflict in RestMLGuardrailsIT
https://github.com/opensearch-project/ml-commons/pull/2205

[Backport 2.x] Initiate MLInferencelngestProcessor

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceIngestProcessor.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceIngestProcessorIT.java

fix flaky test for rounding issue: 
```
REPRODUCE WITH: gradlew ':opensearch-ml-plugin:integTest' --tests "org.opensearch.ml.rest.RestMLInferenceIngestProcessorIT.testMLInferenceProcessorWithNestedFieldType" -Dtests.seed=D43CC64A137DA240 -Dtests.security.manager=false -Dtests.locale=hr-HR -Dtests.timezone=EST5EDT -Druntime.java=17
org.opensearch.ml.rest.RestMLInferenceIngestProcessorIT > testMLInferenceProcessorWithNestedFieldType STANDARD_ERROR
REPRODUCE WITH: gradlew ':opensearch-ml-plugin:integTest' --tests "org.opensearch.ml.rest.RestMLInferenceIngestProcessorIT.testMLInferenceProcessorWithNestedFieldType" -Dtests.seed=D43CC64A137DA240 -Dtests.security.manager=false -Dtests.locale=hr-HR -Dtests.timezone=EST5EDT -Druntime.java=17
org.opensearch.ml.rest.RestMLInferenceIngestProcessorIT …
```

Increase rounding delta from 0.005% to 0.5% on RestMLInferenceIngestProcessorIT

---

common/src/main/java/org/opensearch/ml/common/model/MLDeploySetting.java
common/src/main/java/org/opensearch/ml/common/transport/sync/MLSyncUpInput.java
common/src/main/java/org/opensearch/ml/common/transport/sync/MLSyncUpNodeResponse.java
common/src/test/java/org/opensearch/ml/common/model/MLDeployingSettingTests.java
common/src/test/java/org/opensearch/ml/common/transport/sync/MLSyncUpNodeResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java

Reuse the current cron job and transport APIs to implement auto-undeploy ML_Models based on TTL after any model is un-used for a certain time. This is to mate the automatic remote model deployment and save memory for long idling local models. Verified in a single host cluster. Will verify in bigger cluster. 
[https://github.com/opensearch-project/ml-commons/issues/1343] , https://github.com/opensearch-project/ml-commons/issues/1148

Add TTL to un-deploy model automatically

---

ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/Predictable.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ExecutionContext.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandler.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactory.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandlerTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingDenseModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactoryTests.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java

* Change httpclient from sync to async
* Change from CRTAsyncHttpClient to NettyAsyncHttpClient
* Add publisher to request
* Change sync httpclient to async
* Handle error case and return error response in actionLListener
* Fix no response when exception
* Add content type header
* Fix issues found in functional test
* Fix no response issue in functional test
* fix default step size error
* Add track inference duration for async httpclient
* Change client appsec highlight issues implementation for async httpclient
* Add UTs
* Add UTs
* Remove unused file
* Add UTs
* format code
* Change error code to honor remote service error code
* Add more UTs
* Change SSRF code to make it correct for return error stattus
* Fix failure UTs and add more UTs
* Fix failure ITs
* format code
* Fix partial …

[Backport 2.x] Change httpclient to async (#1958)

---

build.gradle

The Spotless Gradle Plugin brings in a transitive dependency on Eclipse Core Runtime 3.26.100. That version is impacted by a CVE. This forces the newest version, currently 3.29.0.
https://github.com/opensearch-project/ml-commons/issues/1863

fix CVE for org.eclipse.core.runtime

---

plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Set the mlModel info in the deployment. Also use the cached value outside of mlModel to obtain the ModelStatus.

set the mlModel info in the deploy stage

---

release-notes/opensearch-ml-common.release-notes-2.14.0.0.md

Add release note 2.14
Add release note 2.14

Add release note 2.14

---

plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java

When a model auto-deploys again after TTL expire or undeployed, it needs to check if isDeployToAllNodes is true. If so, the planningWorkerNodes needs to be set to null so the next deployment knows it's not customized deployment. 

Clear planningWorkerNodes when model auto-deploys again after undeploy

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceIngestProcessorIT.java

fix local build failure for RestMLInferenceIngestProcessorIT
when openai key is null, skip running predict

Fix local build failure for RestMLInferenceIngestProcessorIT

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ModelHelper.java

DeploySetting was not included in registering local models (pre-trained or from custom url), which was fine because it only included autoDeploy flag for remote models. Now we added TTL in the DeploySetting which applies to all models so We need to add it back.
Verified in local dev cluster.

add deploySetting in registering local models

---

plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java

This PR is add waiting for model to be undeployed to fix flaky test introduced by #2363, 
https://github.com/opensearch-project/ml-commons/actions/runs/8933312245/job/24539185907?pr=2402

Fix flaky test of visualization tool

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Add IT to auto deploy a remote model in Predict, and auto un-deploy it through TTL.

add IT for remote model automatic deploy with TTL

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandler.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandlerTest.java

Handle the throttling error in the header when the error is only returned in the headers and response body is empty. This is for a specific case discussed in the issues below. 
https://github.com/opensearch-project/ml-commons/issues/2429, https://github.com/opensearch-project/ml-commons/issues/2249

hanlde the throttling error in the response header

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLFlowAgentIT.java

IT test case: flow agent + searchIndexTool

add IT flow agent with search index tool

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/input/Constants.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorGetRequest.java
plugin/src/main/java/org/opensearch/ml/action/connector/GetConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetConnectorAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/RestActionUtilsTests.java

[adding multi tenancy settings to distinguish if that's a multi-tenancy use case or not. IF this is multi-tenant, we expect tenant_id in the header. This tenant_id will give us way to make partition of the logical resources of tenants.
In this PR, I'm just adding `tenant_id` in get connector api to show how the overall flow look like depending on the multi-tenancy settings. 
Eventually I'll raise more PRs to cover other APIs (Connectors, Tasks, Models, Model groups etc)]
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/ …

adding multi tenancy settings

---

plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/breaker/MemoryCircuitBreaker.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/utils/MLNodeUtils.java
plugin/src/test/java/org/opensearch/ml/action/prediction/TransportPredictionTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/breaker/MemoryCircuitBreakerTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLMemoryCircuitBreakerIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java
plugin/src/test/java/org/opensearch/ml/task/MLExecuteTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

This PR fixed these problems:
1. fix bug - the circuit breaker checkups are always skipped in single node cluster when Predicting a request. This PR fixes this issue ensuring the single node prediction has the same CB checkups before predicting.
2. Updated the log message to show the right content when CB is open. https://github.com/opensearch-project/ml-commons/issues/2465
3. Disable the memory CB when the threshold is 100. https://github.com/opensearch-project/ml-commons/issues/2308 
4. Added ClusterApplierService in the UTs to be compatible with latest opensearch core changes.
5. Skip the Circuit breaker checks for Remote Models in Register/Deploy/Predict. 
Verified in both single-node and multi-node clusters. UT/ITs added to cover all cases. …

fix memory CB bugs and upgrade UTs to compatible with core changes

---

docs/remote_inference_blueprints/amazon_comprehend_connector_blueprint.md

Add a connector blueprint for Amazon Comprehend. This shows how to create custom connector used by ML Inference processor.
- https://github.com/opensearch-project/ml-commons/issues/2467

add a connector blueprint for Amazon Comprehend APIs

---

docs/tutorials/semantic_search/generate_embeddings_for_arrays_of_object.md

Add tutorial: generate embedding for arrays of object

tutorial: generate embedding for arrays of object

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/agent/MLAgent.java
common/src/main/java/org/opensearch/ml/common/dataset/TextDocsInputDataSet.java
common/src/main/java/org/opensearch/ml/common/model/MLDeploySetting.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
common/src/test/java/org/opensearch/ml/common/agent/MLAgentTest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java
plugin/build.gradle

Changes the Version compatibility constants to calculate independently of constants in those OpenSearch versions.
Relates to #2483 (which can forward-port this commit to `main`)
- ~[ ] New functionality includes testing.~
- ~[ ] All tests pass~
- ~[ ] New functionality has been documented.~
- ~[ ] New functionality has javadoc added~

[Feature/multi_tenancy] Remove strict version dependency to compile minimum compatible version

---

plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelGroupActionIT.java

On successful deletion of a model group, when trying to register a new model group with same name within a few milli seconds, it gives the error "The name you provided is already being used by a model group..". Setting the refresh policy to immediate to resolve the issue.

adding immediate refresh to delete model group request

---

plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteModelGroupActionIT.java

adding immediate refresh to delete model group request
(cherry picked from commit 2b98d203ad7f1e65dbc83f9f935a3b3b75579f06)
Backport https://github.com/opensearch-project/ml-commons/pull/2514 from main to 2.x

[Backport 2.x] adding immediate refresh to delete model group request (#2514)

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLFlowAgentIT.java

Fix the error in https://github.com/opensearch-project/ml-commons/pull/2460 due to `import org.apache.hc.core5.http.ParseException; `
Fix the error in https://github.com/opensearch-project/ml-commons/pull/2460 due to `import org.apache.hc.core5.http.ParseException; `

Fix: import error on Backport/backport 2448 to 2.x

---

docs/remote_inference_blueprints/bedrock_connector_anthropic_claude3_blueprint.md

Add claude3 blueprint. The request/response body is different with claude2, so i add a new file for claude3.
claude3
```
{
"modelId": "anthropic.claude-3-sonnet-20240229-v1:0",
"contentType": "application/json",
"accept": "application/json",
"body": {
"anthropic_version": "bedrock-2023-05-31",
"max_tokens": 1000,
"messages": [
{
"role": "user",
"content": [
{
"type": "image",
"source": {
"type": "base64",
"media_type": "image/jpeg",
"data": "iVBORw..."
}
},
{
"type": "text",
"text": "What's in this image?"
}
]
}
]
}
}
```
claude2
```
{
"modelId": "anthropic.claude-v2:1",
"contentType": "application/json",
"accept": "*/*",
"body": "{\"prompt\":\"\\n\\nHuman: Hello world\\n\\nAssistant:\",\"max_tokens_to_sample\":300,\"temperature\":0.5,\"top_k\":250,\"top_p\":1,\"stop_sequences\":[\"\\n\\nH …
```

Add claud3 blueprint

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutorTest.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestBedRockInferenceIT.java
plugin/src/test/resources/org/opensearch/ml/rest/templates/BedRockConnectorBodies.json

Fix bedrock embedding generation issue
https://github.com/opensearch-project/ml-commons/issues/2490

Fix bedrock embedding generation issue

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactory.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/httpclient/MLHttpClientFactoryTests.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

We have limited no private IP allowed in connector. Some user want to use private IP. Confirmed with security team, should be fine to have a setting to control allow private IP or not. By default it's disabled, user can enable it by update setting
```
PUT _cluster/settings
{
"plugins.ml_commons.connector.private_ip_enabled": true
}
}
```
Resolve #2142

add setting to allow private IP

---

release-notes/opensearch-ml-common.release-notes-2.15.0.0.md

Add release notes for 2.15

---

plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestConnectorToolIT.java

1. Add per-defined cluster setting to disable MLSyncUpJob for JVM private OpenSearch Cluster, so that it will not create `.plugin-ml-config` index automatically every 10 seconds.
2. Skip RestConnectorToolIT if `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are not set
3. Add retry for creating connector if ML encryption master key has not been initialized yet
https://github.com/opensearch-project/ml-commons/issues/2436

fix flaky test of PredictionITTests and RestConnectorToolIT

---

plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestConnectorToolIT.java

* fix flaky test of prediction
Signed-off-by: Hailong Cui <ihailong@amazon.com>
(cherry picked from commit f28bb740e87cd520190b003011303d5a85d477d6)
backport (#2437) from main

[Backport 2.x] fix flaky test of PredictionITTests and RestConnectorToolIT (#2437)

---

plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestConnectorToolIT.java

* fix flaky test of prediction
Signed-off-by: Hailong Cui <ihailong@amazon.com>
(cherry picked from commit f28bb740e87cd520190b003011303d5a85d477d6)
backport (https://github.com/opensearch-project/ml-commons/pull/2437) from main

[Backport 2.15] fix flaky test of PredictionITTests and RestConnectorToolIT (#2437)

---

common/src/main/java/org/opensearch/sdk/GetDataObjectResponse.java
common/src/test/java/org/opensearch/sdk/GetDataObjectResponseTests.java
plugin/src/main/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClient.java
plugin/src/test/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java

Includes a String-Object source map alongside the parser for cases such as creating a model where its type and hidden status are needed prior to parsing.

[Feature/multi_tenancy] Add source map to GetDataObjectResponse

---

common/src/main/java/org/opensearch/sdk/SdkClient.java
common/src/main/java/org/opensearch/sdk/UpdateDataObjectRequest.java
common/src/main/java/org/opensearch/sdk/UpdateDataObjectResponse.java
common/src/test/java/org/opensearch/sdk/SdkClientTests.java
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/GetConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/helper/ConnectorAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClient.java
plugin/src/test/java/org/opensearch/ml/action/connector/DeleteConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/GetConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/UpdateConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/helper/ConnectorAccessControlHelperTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java

- Adds update method to SdkClient interface (full document update, does not do scripts)
- Implements update method on Local and Remote clients
- Migrates Connector Update action to use SdkClient for the updates
NOTE: this PR builds on commit 22a0ce53d8e494e269203b4de7937db122c241fa which represents PR #2507 .  Reviewers may want to focus attention on commits 100d71a19556047c6e23625bdb4229d01fe86a44 and e90b553742d124e54dfd834f863adc4edb2ad24d
Will rebase this PR against the branch when #2507 is merged.
Continuation of PR #2459 …

[Feature/multi_tenancy] Add UpdateDataObject interface, Client, and Connector Implementations

---

common/src/main/java/org/opensearch/sdk/SdkClient.java
common/src/main/java/org/opensearch/sdk/SearchDataObjectRequest.java
common/src/main/java/org/opensearch/sdk/SearchDataObjectResponse.java
common/src/test/java/org/opensearch/sdk/SdkClientTests.java
common/src/test/java/org/opensearch/sdk/SearchDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/SearchDataObjectResponseTests.java
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/SdkClientModule.java
plugin/src/test/java/org/opensearch/ml/action/connector/DeleteConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/SearchConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/UpdateConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java

- Adds search method to SdkClient interface
- Implements search method on Local and Remote clients
- Migrates Connector Search action to use SdkClient for the searching
- Updates Delete and Update connector actions which search model index to use new API
Continuation of PR https://github.com/opensearch-project/ml-commons/pull/2459

[Feature/multi_tenancy] Add SearchDataObject interface, Client, and Connector Implementations 

---

common/src/main/java/org/opensearch/sdk/SdkClient.java
common/src/main/java/org/opensearch/sdk/SdkClientUtils.java
common/src/main/java/org/opensearch/sdk/SearchDataObjectRequest.java
common/src/main/java/org/opensearch/sdk/UpdateDataObjectRequest.java
common/src/test/java/org/opensearch/sdk/SdkClientUtilsTests.java

1. Adds tenant ID to SearchDataObjectRequest.  It was already added to the other requests in #2553 
2. Refactors `unwrapAndConvertToRuntime` static method from `SdkClient` interface to new `SdkClientUtils` class
3. Adds new `getRethrownExecutionExceptionRootCause` static method to `SdkClientUtils` class to handle common pattern of throwables from `actionGet()`.   (Have not yet migrated implementations; will do those as part of future PRs.)
PR comments on multiple previous PRs.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-ce …

[Feature/multi_tenancy] Add Tenant ID to Search API, refactor and add util methods

---

ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModelExecute.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModelTest.java

upgrade djl version to 0.28.0

---

.github/workflows/CI-workflow.yml

Prepare for setting ml-commons plugin 3.0.0 baseline JDK version to JDK-21 (seems like the GA should be updated separately to take an effect)
See please https://github.com/opensearch-project/ml-commons/pull/2583

Prepare for setting ml-commons plugin 3.0.0 baseline JDK version to JDK-21

---

common/src/main/java/org/opensearch/sdk/GetDataObjectResponse.java
common/src/test/java/org/opensearch/sdk/GetDataObjectResponseTests.java
plugin/src/main/java/org/opensearch/ml/action/model_group/GetModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/helper/ConnectorAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClient.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java

Some APIs (get model group) require the full `GetResponse` object from the API.
This changes the GetDataObjectResponse to use the full `GetResponse` as the `parser`.  Since there will always be a response, there is no longer a need for `Optional`, and the `isExists()` checks are available again.
It retains the source map as-is.
This parallels the implementation in the SearchDataObjectResponse (and probably would have done it that way if I'd done search first).
This allows for even closer-to-original migration of code expecting a GetResponse. …

[Feature/multi_tenancy] Update GetDataObjectResponse to include full GetResponse parser

---

plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/SdkClientModule.java
plugin/src/main/java/org/opensearch/ml/sdkclient/util/JsonTransformer.java
plugin/src/test/java/org/opensearch/ml/sdkclient/ComplexDataObject.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/SdkClientModuleTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/TestDataObject.java
plugin/src/test/java/org/opensearch/ml/sdkclient/util/JsonTransformerTests.java

SDK DDB client update and search interface implementation. 
* Added implementation of DDB update
* Search requests are routed to search SDK client
* Update create and search to write as json attribute instead of a string under source attribute.

SDK DDB client update and search interface implementation

---

common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/input/Constants.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelInput.java
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/utils/RestActionUtils.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/RestActionUtilsTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

Modify tenant ID header naming to x-tenant-id
https://github.com/opensearch-project/ml-commons/issues/2594

Modify tenant ID header naming to x-tenant-id

---

plugin/src/main/java/org/opensearch/ml/action/connector/GetConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/test/java/org/opensearch/ml/action/connector/GetConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportCreateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelGroupManagerTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java

Set tenant ID while creating connector and model group
DDB search implementation will modify index name to be same as table name.

Set tenant ID while creating connector and model group

---

common/src/main/java/org/opensearch/sdk/UpdateDataObjectRequest.java
common/src/test/java/org/opensearch/sdk/DeleteDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/GetDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/PutDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/SearchDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/UpdateDataObjectRequestTests.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/models/UpdateModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelGroupManagerTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java

Implements needed methods in MLModelManager for the TransportRegisterModelAction when the model is remote.
Migrates all code calling non-sdk MLModelGroupManager methods and removes old method/test.
Also updates SDK request tests to include Tenant ID and creates the missing UpdateRequest test.
Still TODO:  Concurrency guarantee on update request.  Still considering the best way to do that, will follow up with another PR for that, probably tomorrow.

Implement SdkClient in TransportRegisterModelAction

---

docs/tutorials/rerank/rerank_pipeline_with_CrossEncoder_model_deployed_on_Sagemaker.md

Build tutorial for Reranking with cross-encoder model on Sagemaker.

add tutuorial for cross-encoder model on sagemaker

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceIngestProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorFactoryTests.java

add model input validation for local models in ml processor
(https://github.com/opensearch-project/ml-commons/issues/2601)

add model input validation for local models in ml processor

---

.github/workflows/CI-workflow.yml

As we are using the AL2 image for OS plugin for linux now.
We need to fall back with older nodejs versions until AL2 deprecation next year.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Temp use of older nodejs version before moving to Almalinux8

---

.github/workflows/CI-workflow.yml

[Backport 2.x] Temp use of older nodejs version before moving to Almalinux8
Backport https://github.com/opensearch-project/ml-commons/pull/2627

[Backport 2.x] Temp use of older nodejs version before moving to Almalinux8

---

common/src/main/java/org/opensearch/sdk/UpdateDataObjectRequest.java
common/src/test/java/org/opensearch/sdk/SdkClientUtilsTests.java
common/src/test/java/org/opensearch/sdk/UpdateDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/UpdateDataObjectResponseTests.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClient.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java

Tracks SeqNo and PrimaryTerm used for strong concurrency for updates.
- Adds to update requests
- Implements tracking of this version in DynamoDB
Still TODO (@arjunkumargiri  will do in another PR):
- DDB: Initialize SeqNo to 0 for new documents, but increment on overwrite
- DDB: Increment on successful update
- DDB: Return -2 on delete

[Feature/multi_tenancy] Add ifSeqNo and ifPrimaryTerm for update concurrency

---

.github/workflows/maven-publish.yml

Fix GA workflow that publishes Apache Maven artifacts:
```
* What went wrong:
Execution failed for task ':opensearch-ml-common:compileJava'.
> error: invalid source release: 21
```
Part of https://github.com/opensearch-project/ml-commons/issues/2503

Fix GA workflow that publishes Apache Maven artifacts

---

common/src/main/java/org/opensearch/sdk/PutDataObjectRequest.java
common/src/test/java/org/opensearch/sdk/PutDataObjectRequestTests.java
plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClient.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/LocalClusterIndicesClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java

Adds an `overwriteIfExists` boolean to the `PutDataObjectRequest`, defaulting to `true`.  This replicates current default `IndexRequest` behavior using `OpType.INDEX`.   If set false, uses `OpType.CREATE`.
https://github.com/opensearch-project/ml-commons/pull/2605#issuecomment-2214777743

[Feature/multi_tenancy] Support forbidding upserts in PutDataObjectRequest

---

common/src/main/java/org/opensearch/sdk/client/LocalClusterIndicesClient.java
common/src/test/java/org/opensearch/sdk/client/LocalClusterIndicesClientTests.java
common/src/test/java/org/opensearch/sdk/client/TestDataObject.java
plugin/src/main/java/org/opensearch/ml/sdkclient/SdkClientFactory.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/SdkClientFactoryTests.java

Moves the default client (LocalClusterIndicesClient) to the `ml-common` module.  This will make it accessible to tests which cannot depend on the `ml-plugin` module using:
```java
SdkClient sdkClient = new SdkClient(new LocalClusterIndicesClient(client, xContentRegistry));
```
Some changes needed to make this work:
- thread pool name constants from `MachineLearningPlugin.java` needed to be manually defined
- no dependency available (yet) to extend `OpenSearchTestCase`.  We weren't using its functionality anyway other than needing to use mocks directly.
- I had to make a copy of the `TestDataObject` class, as the `ml-plugin` test classes couldn't access it from the `ml-common` test classes.
Blockers for me moving either of the other clients:
- they required jackson dependencies (remote …

[Feature/multi_tenancy] Move the LocalClusterIndicesClient to ml-common module

---

plugin/src/main/java/org/opensearch/ml/breaker/DiskCircuitBreaker.java
plugin/src/main/java/org/opensearch/ml/breaker/MLCircuitBreakerService.java
plugin/src/main/java/org/opensearch/ml/breaker/MemoryCircuitBreaker.java
plugin/src/main/java/org/opensearch/ml/breaker/NativeMemoryCircuitBreaker.java
plugin/src/main/java/org/opensearch/ml/breaker/ThresholdCircuitBreaker.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/breaker/DiskCircuitBreakerTests.java
plugin/src/test/java/org/opensearch/ml/breaker/MLCircuitBreakerServiceTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java

change disk circuit breaker to cluster settings
https://github.com/opensearch-project/ml-commons/issues/2639

change disk circuit breaker to cluster settings

---

.github/workflows/maven-publish.yml

Fix GA workflow that publishes Apache Maven artifacts
Backport of https://github.com/opensearch-project/ml-commons/pull/2625 to `2.x`

[Backport] [2.x] Fix GA workflow that publishes Apache Maven artifacts (#2625)

---

docs/tutorials/aws/AIConnectorHelper.ipynb
docs/tutorials/aws/semantic_search_with_cohere_embedding_model.md
docs/tutorials/aws/semantic_search_with_openai_embedding_model.md

To add caching of secrets from client side to reduce API calls to secret manger in AOS, new permissions are required in the policy attached to the IAM role to fetch credentials from secret manager. 
This updates are validated using OpenAI and Cohere. 

update tutorials for caching secrets for non-aws models

---

common/src/test/java/org/opensearch/ml/common/connector/ConnectorTest.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java

Enable users to register bedrock runtime agent for calling bedrock knowledge base.
```
POST /_plugins/_ml/connectors/_create
{
"name": "Amazon Bedrock Connector: knowledge",
"description": "The connector to the Bedrock knowledge base",
"version": 1,
"protocol": "aws_sigv4",
"region": "...",
"service_name": "bedrock"
},
"access_key": "...",
"secret_key": "..."
},
"actions": [
{
"action_type": "predict",
"method": "POST",
"url": "...",
"headers": {
"content-type": "application/json",
"x-amz-content-sha256": "required"
},
"request_body": "{\"retrievalQuery\": {\"text\": \"${parameters.text}\"}}"
}
]
}
POST /_plugins/_ml/models/_register?deploy=true
{
"name": "bedrock: knowledge base",
"description": "Test connector for bedrock …
```

feat: add bedrock runtime agent for knowledge base

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MLModelTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/MLModelToolTests.java

Fix MLModelTool returns null if the response of LLM is a pure json object. It will detect wether the LLM response is a pure json object or a response string, and parse in different way.
There is similar logic in [AgentUtils.java](https://github.com/opensearch-project/ml-commons/blob/b6618b2bcd18ab7070a8b8923074d365efe89dd9/ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java#L193) for MLChatAgentRunner
https://github.com/opensearch-project/ml-commons/blob/b6618b2bcd18ab7070a8b8923074d365efe89dd9/ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java#L193
https://github.com/opensearch-project/ml-commons/issues/2654
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Fix MLModelTool returns null if the response of LLM is a pure json object

---

docs/remote_inference_blueprints/bedrock_connector_cohere_cohere.embed-english-v3_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_cohere_cohere.embed-multilingual-v3  _blueprint.md
docs/remote_inference_blueprints/bedrock_connector_cohere_cohere.embed-multilingual-v3_blueprint.md

Blueprints for cohere embedding models in bedrock.

add connector blueprint for cohere embedding models in bedrock

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MLModelTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/MLModelToolTests.java

Backport https://github.com/opensearch-project/ml-commons/commit/007b914b74850e6faec3645b6f3d8db2dc772563 from https://github.com/opensearch-project/ml-commons/pull/2655 
And fix compiling failure by removing java21 API. (main use java 21 while 2.x use java17)
https://github.com/opensearch-project/ml-commons/issues/2654

[Backport 2.x] Fix MLModelTool returns null if the response of LLM is a pure json object

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MLModelTool.java

The previous PR https://github.com/opensearch-project/ml-commons/pull/2655 includes java21 API and will block backport PR.
After fixing with this backport PR https://github.com/opensearch-project/ml-commons/pull/2675 and avoid diverge with it, this PR will remove the java 21 API as well.
https://github.com/opensearch-project/ml-commons/issues/2654

remove java21 API for aligning with BackPort PR

---

docs/remote_inference_blueprints/amazon_comprehend_connector_blueprint.md
docs/remote_inference_blueprints/amazon_textract_connector_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_ai21labs_jurassic_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_anthropic_claude3_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_anthropic_claude_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_titan_embedding_blueprint.md
docs/remote_inference_blueprints/bedrock_connector_titan_multimodal_embedding_blueprint.md

In order to conveniently enable the automated model interface, here we make Amazon managed LLM blueprints in a tidier format.

Make all Amazon managed LLM blueprints in a tidier format

---

plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java

Previously dot(.) is manually removed from table name in DDB Client. This is no longer needed as DynamoDB table name supports dot(.)
ref:https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html

Fix removal of dot(.) from table name as DDB table name supports dot(.)

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Agent will use execute thread pool. The current pool size is too small. Increase it to the same with remote predict.

increase execute thread pool size

---

plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/breaker/MemoryCircuitBreaker.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/java/org/opensearch/ml/utils/MLNodeUtils.java
plugin/src/test/java/org/opensearch/ml/action/prediction/TransportPredictionTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/breaker/MemoryCircuitBreakerTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLMemoryCircuitBreakerIT.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

Manual backport of https://github.com/opensearch-project/ml-commons/pull/2469

[Backport] exclude remote models in circuit breaker checks and fix memory CB bugs

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLConfig.java

update config index mappings to use correct field types.
In 2.13, config index mapping was updated with three new fields `configuration`, `type`, and `last_update_time`but schema version was not bumped. Due to which, the domains which were upgraded to 2.13 from previous versions did not go through update index mapping as they did not detect a schema version bump. 
During indexing, these fields got created with wrong types not as specified in the mapping. Now when such domains are going to upgrade to 2.15, with schema_version bump, the index mapping tries to get updated but will throw exception since the field types for the three fields specified above are different. Hence the index initialization fails and indexing into the `config` index wouldn't be possible. 
Hence, the PR tries to add …

update config index mappings to use correct field types

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

pass all parameters including chat_history to run tools

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/ModelExecutor.java
plugin/src/test/java/org/opensearch/ml/plugin/MachineLearningPluginTests.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceIngestProcessorIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceSearchRequestProcessorIT.java
plugin/src/test/java/org/opensearch/ml/utils/TestData.java
plugin/src/yamlRestTest/java/org/opensearch/ml/plugin/PluginClientYamlTestSuiteIT.java
plugin/src/yamlRestTest/resources/rest-api-spec/test/10_basic.yml
plugin/src/yamlRestTest/resources/rest-api-spec/test/20_inference_ingest_processor.yml
plugin/src/yamlRestTest/resources/rest-api-spec/test/30_inference_search_request_processor.yml
plugin/src/yamlRestTest/resources/rest-api-spec/test/30_inference_search_request_processor.yml 

Add initial search request inference processor
https://github.com/opensearch-project/ml-commons/issues/2173

Add initial search request inference processor

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

Currently we have a settings `plugins.ml_commons.max_model_on_node` how many models we can load in a single node. But this shouldn't include Remote models. So excluding remote model from that consideration.

excluding remote models from max node per node setting

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

excluding remote models from max node per node setting. Backport PR from [PR](https://github.com/opensearch-project/ml-commons/pull/2732/files)

[BACKPORT 2.10] excluding remote models from max node per node setting

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

[excluding remote models from max node per node setting. Backport PR from [PR](https://github.com/opensearch-project/ml-commons/pull/2732/files)]

[Backport 2.11] excluding remote models from max node per node setting

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/AgentUtilsTest.java

Fix final answer with extra meaningless symbol like `"}````
https://github.com/opensearch-project/ml-commons/issues/2649

Fix final answer with extra meaningless symbol

---

memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelation.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/indices/MLIndicesHandler.java
release-notes/opensearch-ml-common.release-notes-2.16.0.0.md

Adds the _doc key wrapper around index mapping as required by CreateIndexRequest javadoc.
See also https://github.com/opensearch-project/OpenSearch/issues/14984
When the cluster has v1 templates with patterns matching the index, without the _doc wrapper, dynamic mappings are getting enabled for the index. From below, created_time is being created as long (dynamically picked) instead of `timestamp` type which is defined in the [mapping definition](https://github.com/opensearch-project/ml-commons/blob/main/common/src/main/java/org/opensearch/ml/common/CommonValue.java#L138).
With changes in this PR by adding `_doc` wrapper, even if cluster has v1 templates, indices are getting created with expected mappings.
By submitting this pull request, I confirm that my contribution is made under the …

Add XContentType to wrap the CreateIndexRequest mappings in _doc key to fix v1 templates issue

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessorTests.java

remove extra ignoreMissing and fix JsonArray Parsing Issue
when testing terms query on ml inference processor, found the bug when parsing list or other data type in queries are throw parsing exception, this PR will fix the exception while parsing list or object types in query body. 
Added unit tests for terms query when matching multiple keywords. 
example terms query: {"query":{"terms":{"text":["car","vehicle","truck"],"boost":1.0}}}
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTI …

Fix ml inference request processor when running terms query

---

release-notes/opensearch-ml-common.release-notes-2.16.0.0.md

Add release notes due to bug fix

Add release notes

---

common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
docs/remote_inference_blueprints/batch_inference_sagemaker_connector_blueprint.md

This PR fixes the issue reported in https://github.com/opensearch-project/ml-commons/issues/2502. This is not a bug since the issue was an expected behavior based on the initial design of the Update Connector API. However, over time we think that, in the Update APIs, it's a better CX experience to merge the updated parameters with the existing ones. 
Also, some details of the sagemaker model for batch inference is added in this PR.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING. …

Merge the existing parameters when updating connectors

---

plugin/build.gradle
plugin/src/test/java/org/opensearch/ml/rest/RestSearchIndexToolIT.java

Recover search index tool it in multi node cluster 
Issue: https://github.com/opensearch-project/ml-commons/issues/2362

Test: recover search index tool it in multi node cluster

---

plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java

If `overwriteIfExists` flag is set to false, then `putDataObject` requests needs to throw an exception if the document already exists. Existing code has a bug which fails with error `nvalid ConditionExpression: Syntax error; token: \"_\", near: \"(_tenant_id\" (Service: DynamoDb, Status Code: 400, Request ID: P6GHA1O61AGC8DUCBJ1MUVIL9NVV4KQNSO5AEMVJF66Q9ASUAAJG)`

[Bug fix] Check if document exists before put operation

---

common/src/main/java/org/opensearch/ml/common/settings/SettingsChangeListener.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/Executable.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModelExecute.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/anomalylocalization/AnomalyLocalizerImpl.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelation.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/sample/LocalSampleCalculator.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/test/java/org/opensearch/ml/settings/MLFeatureEnabledSettingTests.java

[ `MLFeatureEnabledSetting` class is in `plugin` module and `algorithm` module doesn't have dependency on `plugin` module. So when we do `mlFeatureEnabledSetting.isMultiTenancyEnabled()` to the `MLAgentExecutor` class, it doesn't update the dynamic value of `ML_COMMONS_MULTI_TENANCY_ENABLED` settings. So we need a listener in algorithm module to get the update status of this settings.]

fixing agent execution for multi-tenancy

---

plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/helper/ConnectorAccessControlHelper.java

Fixes Delete Connector and Update Connector transport action handling of thread context.   Context was being restored too soon when there were multiple chained calls, and this caused subsequent calls to fail.

[Feature/multi_tenancy] Delay restoring thread context until after all client calls

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/conversation/ConversationMeta.java
common/src/main/java/org/opensearch/ml/common/conversation/ConversationalIndexConstants.java
common/src/test/java/org/opensearch/ml/common/conversation/ConversationMetaTests.java
memory/src/main/java/org/opensearch/ml/memory/ConversationalMemoryHandler.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationTransportAction.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/UpdateConversationRequest.java
memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandler.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequestTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationResponseTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationsResponseTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationsTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexITTests.java
memory/src/test/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandlerTests.java

Adding additional info for memory metadata
index mapping, `additional_info` is new added field with `flat_object` type
```json
{
".plugins-ml-memory-meta": {
"mappings": {
"_meta": {
"schema_version": 2
},
"properties": {
"additional_info": {
"type": "flat_object"
},
"application_type": {
"type": "keyword"
},
"create_time": {
"type": "date",
"format": "strict_date_time||epoch_millis"
},
"name": {
"type": "text"
},
"updated_time": {
"type": "date",
"format": "strict_date_time||epoch_millis"
},
"user": {
"type": "keyword"
}
}
}
}
}
```
API request/response samples
```shell
curl --request POST \
--url http://localhost:9200/_plugins/_ml/memory \
--header 'Content-Type: application/json' \
--data '{"name": "test memory1"}'
}
{
"memory_id": "qDjoBpEB_JGSOCujgATn"
}
curl …
```

[Enhancement]Adding additional info for memory metadata

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java

Fix delete local model twice quickly get 500 response issue
https://github.com/opensearch-project/ml-commons/issues/2793

Fix delete local model twice quickly get 500 response issue

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

[Without this change following error can happen:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "doesVersionCreateModelGroup" is null
at org.opensearch.ml.model.MLModelManager.deleteOrUpdateModelGroup(MLModelManager.java:960) ~[?:?]
at org.opensearch.ml.model.MLModelManager.deleteModel(MLModelManager.java:953) ~[?:?]
at org.opensearch.ml.model.MLModelManager.lambda$registerModel$34(MLModelManager.java:858) [opensearch-ml-multi-tenancy-2.15.0-SNAPSHOT.jar:multi-tenancy-2.15.0-SNAPSHOT]
at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90) [opensearch-core-2.15.0.jar:2.15.0]
at org.opensearch.ml.engine.ModelHelper.downloadAndSplit(ModelHelper.java:297) ~[?:?]
at …
```

code refactor not to occur nullpointer exception

---

common/src/test/java/org/opensearch/ml/common/connector/HttpConnectorTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutorTest.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

When using LLM in ml-commons connector, the prompt may contains substring like `${parameters.xxxx} `. The PRs adds a parameter named `skip_validating_missing_parameters` to enable users to configure whether to skip validating missing parameters in payload.
The user can specify this parameter in the following manner:
```
POST /_plugins/_ml/connectors/_create
{
"name": "BedRock test connector",
"description": "The connector to BedRock service for claude model",
"version": 1,
"protocol": "aws_sigv4",
"region": "us-east-1",
"service_name": "bedrock",
"anthropic_version": "bedrock-2023-05-31",
"endpoint": "bedrock-runtime.us-east-1.amazonaws.com",
"auth": "Sig_V4",
"content_type": "application/json",
"max_tokens_to_sample": 8000,
"temperature": 0.00001, …
```

Enhance: support skip_validating_missing_parameters in connector

---

common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/test/java/org/opensearch/ml/common/connector/HttpConnectorTest.java

When an array as a string in parameter, the string in list are not escaped. 
This PR will escape the string when it's a json array. 
for example, before this change: 
```
POST /_plugins/_ml/connectors/_create
{
"name": "Amazon Bedrock Connector: Claude Instant V1",
"version": "1",
"description": "The connector to bedrock Claude model",
"protocol": "aws_sigv4",
"max_tokens_to_sample": "8000",
"service_name": "bedrock",
"temperature": "1.0E-4",
"response_filter": "$.completion",
"region": "us-west-2",
"anthropic_version": "bedrock-2023-05-31",
"inputs":"please summerize the documents"
},
"access_key": " ",
"secret_key": " ",
"session_token": "" },
"actions": [
{
"action_type": "PREDICT",
"method": "POST",
"url": …
```

Support list in response body

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRAGSearchProcessorIT.java

Fix Cohere test.

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessorTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceSearchResponseProcessorIT.java

Many document to one prediction is the default config in ML Inference Search Response Processor. This PR adds one document to one prediction support following up with https://github.com/opensearch-project/ml-commons/pull/2688
in 2.16, ml inference search response processor support collect documents into a list of model input and make one prediction call.
for example, 
the search response returns as following, and we would like to use the `text` field in the document to send to model input. 
```
{
"took": 100,
"timed_out": false,
"_shards": {
"total": 22,
"successful": 22,
"skipped": 0,
"failed": 0
},
"hits": {
"total": {
"value": 2,
"relation": "gte"
},
"max_score": 1,
"hits": [
{
"_index": "test_index",
"_id": "1",
"_score": 1,
"_source": {
"text": " this is document 1"
},
{
"_index": …
```

Support one_to_one in ML Inference Search Response Processor

---

common/src/main/java/org/opensearch/ml/common/utils/ModelInterfaceUtils.java

Resolves #2829 
Sometimes will fail when cohere model is first time invoked but then work for the rest. Tested with test domain.

Fix cohere model input interface cannot validate cohere input issue

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
common/src/main/java/org/opensearch/ml/common/transport/config/MLConfigGetResponse.java
plugin/src/main/java/org/opensearch/ml/action/config/GetConfigTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/config/GetConfigTransportActionTests.java

Expose ML Config API

---

common/src/main/java/org/opensearch/ml/common/model/Guardrails.java
common/src/test/java/org/opensearch/ml/common/model/GuardrailsTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java

When the guardrails type is not setup, we use local_regex as default type.

use local_regex as default type for guardrails

---

common/src/main/java/org/opensearch/ml/common/model/Guardrails.java
common/src/test/java/org/opensearch/ml/common/model/GuardrailsTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java

* use local_regex as default type for guardrails
* add UT for model type
---------
(cherry picked from commit 7ecff1aaa17d8ee04fc0a408b49384624db0b93b)

[Backport] use local_regex as default type for guardrails (#2853) (#2856)

---

plugin/src/main/java/org/opensearch/ml/rest/RestMLExecuteAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLExecuteActionTests.java

Return agent execution error in xcontent format. If xcontent building failed, use plain text.

Agent execution error in json format

---

plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/test/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupActionTests.java

Migrates UpdateModelGroup action to use SdkClient.
Cherry-picked from #2818

[Feature/multi_tenancy] Migrate Update Model Group to SdkClient

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java

When deleting a model, its model controller must be deleted, but this is not required in multitenancy.
The `ResourceNotFound` exception was handled for the local (Node) client case. This PR handles the appropriate `OpenSearchException` with 404 status returned from the remote client.
It is likely a similar fix will be required for the DynamoDB client.
Cherry-picked from #2818 

[Feature/multi_tenancy] Handle controller index 404 on remote client

---

plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java

Adds the `tenant_id` field to the DynamoDB Item source so that it will be available for search when replicated.
Cherry-picked from #2818

[Feature/multi_tenancy] Add tenant ID field to DDB object

---

common/src/main/java/org/opensearch/ml/common/MLConfig.java
common/src/main/java/org/opensearch/ml/common/MLModelGroup.java
common/src/main/java/org/opensearch/ml/common/MLTask.java
common/src/main/java/org/opensearch/ml/common/agent/MLAgent.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupInput.java
common/src/main/java/org/opensearch/ml/common/transport/undeploy/MLUndeployModelsRequest.java

Several of the XContent parsers were missing a break statement after getting the tenant ID, causing them to continue to also execute the default.
Fixed one of these in #2867, saw another one and did a search for other copy-pasted victims, and this fixes the rest.

[Feature/multi_tenancy] Adds missing break statements following tenant ID parsing

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLConfig.java
common/src/test/java/org/opensearch/ml/common/transport/config/MLConfigGetResponseTest.java
plugin/src/test/java/org/opensearch/ml/action/config/GetConfigTransportActionTests.java

fix breaking changes in config index fields

fix breaking changes in config index fields

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLTask.java
common/src/main/java/org/opensearch/ml/common/MLTaskType.java
common/src/main/java/org/opensearch/ml/common/connector/ConnectorAction.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensors.java
common/src/main/java/org/opensearch/ml/common/transport/task/MLCancelBatchJobAction.java
common/src/main/java/org/opensearch/ml/common/transport/task/MLCancelBatchJobRequest.java
common/src/main/java/org/opensearch/ml/common/transport/task/MLCancelBatchJobResponse.java
common/src/test/java/org/opensearch/ml/common/transport/task/MLCancelBatchJobRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/task/MLCancelBatchJobResponseTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandler.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCancelBatchJobAction.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/GetTaskTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCancelBatchJobActionTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java

support get batch transform job status in get task API
//TODO: Will be adding UTs and ITs in next revision

support get batch transform job status in get task API

---

common/src/main/java/org/opensearch/ml/common/MLConfig.java

output only old fields in get config API

output only old fields in get config API

---

plugin/src/main/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportAction.java

fix http dependency in CancelBatchJobTransportAction

fix http dependency in CancelBatchJobTransportAction

---

common/src/main/java/org/opensearch/ml/common/MLModelGroup.java
common/src/main/java/org/opensearch/sdk/client/LocalClusterIndicesClient.java
common/src/test/java/org/opensearch/sdk/client/LocalClusterIndicesClientTests.java
plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/test/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/UpdateModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/register/TransportRegisterModelActionTests.java
plugin/src/test/java/org/opensearch/ml/helper/ModelAccessControlHelperTests.java

Prevents one tenant from registering a model to a model group created by a different tenant, and deleting a model group created by a different tenant.

[Feature/multi_tenancy] Make model group access control checks tenant aware

---

ml-algorithms/build.gradle

[In OpenSearch 2.16 specifically OpenSearch-ML, Bouncy Castle is still at version 1.75 and has 4 medium vulnerabilities listed against it in Black Duck:
BDSA-2023-3876/ CVE-2024-30171
BDSA-2024-1960/ CVE-2024-29857
BDSA-2023-3876/ CVE-2024-30171
BDSA-2024-2378/ CVE-2024-34447]

upgrading bounty castle version

---

common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java

Manual Backport from https://github.com/opensearch-project/ml-commons/pull/2871

[Backport 2.16] Fix custom prompt substitute with List issue in ml inference search response processor

---

plugin/src/main/java/org/opensearch/ml/utils/error/ErrorMessage.java
plugin/src/test/java/org/opensearch/ml/utils/error/ErrorMessageTests.java

Support construct ErrorMessage object with null exception.

Support null exception in ErrorMessage

---

plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java

Since DynamoDB uses both the document id and tenant id as a combined primary key, both are necessary for the delete action; other clients only need the document ID.
Also fixes the DynamoDB client to use the HASH_KEY (`_tenant_id`) rather than TENANT_ID (`tenant_id`), a subtlety that was missed in a previous change to one but not the other.

[Feature/multi_tenancy] Fix DDB client tenant id handling

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceSearchResponseProcessorIT.java

Fix RestMLInferenceSearchResponseProcessorIT: add skip when aws key is null
https://github.com/opensearch-project/ml-commons/issues/2857#issuecomment-2341768217

Fix RestMLInferenceSearchResponseProcessorIT: add skip when aws key is null

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java

The http method hard coded as POST in AWS connector executor. That caused get remote job failed. 
Resolves #2931

fix get batch task bug

---

common/src/main/java/org/opensearch/sdk/SdkClientSettings.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/sdkclient/SdkClientFactory.java
plugin/src/main/plugin-metadata/plugin-security.policy
plugin/src/test/java/org/opensearch/ml/sdkclient/SdkClientFactoryTests.java

Refactors SdkClient code as required to support (working) DDB/AOSS integration tests
- removes the temporary "local" DDB implementation
- fetches credentials from system environment (and updates gradle build to put them there)

[Feature/multi_tenancy] Fix SdkClient credential handling for AWS endpoints

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessorTests.java

When configuring ml inference processor with full_response_path is false with no output mapping throw exceptions "reason": "An unexpected error occurred: model inference output cannot find field name: $.inference_results" 
When ml inference search response processor, configuring no output mapping, then the processors will add the default output mapping as following that will add a field inference_result to the documents or search hits, reading from the json path $.inference_result in the prediction results.
```
{
"output_map": {
"inference_result": "$.inference_result"
}
}
```
But checking in the [ml inference ingest processor](https://github.com/opensearch-project/ml-commons/blob/bbaea1c3f5b141512ed81562893e5ddfb192996b/plugin/src/main/java/org/opensearch/ml/processor/MLInferenceIngestPro …

fix full_response false and no mapping exceptions

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java

Fix ML task index mapping
Resolves #2948

fix ML task index mapping

---

common/src/main/java/org/opensearch/ml/common/MLTaskState.java
common/src/main/java/org/opensearch/ml/common/MLTaskType.java
common/src/main/java/org/opensearch/ml/common/connector/MLPostProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/functions/postprocess/BedrockBatchJobArnPostProcessFunction.java
common/src/main/java/org/opensearch/ml/common/transport/task/MLCancelBatchJobAction.java
common/src/test/java/org/opensearch/ml/common/connector/functions/postprocess/BedrockBatchJobArnPostProcessFunctionTest.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCancelBatchJobAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/action/tasks/GetTaskTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCancelBatchJobActionTests.java

Fix two issues (find more details on #2954):
1. Hard coded job status parsing 
2. Bedrock jobArn escaping issue
Resolves #2954

add bedrock batch job post process function; enhance remote job status parsing

---

plugin/src/main/java/org/opensearch/ml/action/agents/TransportRegisterAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java

Adds tenant ID to a few requests that were missing them.
~NOTE: included a TODO temporarily working around model controller accidentally migrated to sdkClient in #2585. I'll follow up with another PR to remove it.~

[Feature/multi_tenancy] Add more missing tenant ids in requests

---

plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java

Deleting the model controller was inadvertently migrated to the SdkClient in #2585.
This reverts those changes and updates the tests appropriately.
Backported from #2818 

[Feature/multi_tenancy] Revert inadvertent migration of deleteController to SdkClient

---

plugin/src/main/java/org/opensearch/ml/action/controller/CreateControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/DeleteControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/GetControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/UpdateControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCreateControllerAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteControllerAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetControllerAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdateControllerAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/main/java/org/opensearch/ml/utils/MLExceptionUtils.java
plugin/src/test/java/org/opensearch/ml/action/controller/CreateControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/controller/DeleteControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/controller/GetControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/controller/UpdateControllerTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateControllerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteControllerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetControllerActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateControllerActionTests.java

This PR will add a feature enable setting for controller index, to support multi-tenancy

Add feature enable setting for controller index

---

docs/remote_inference_blueprints/bedrock_connector_anthropic_claude3_blueprint.md

Fix bedrock claude3 blueprint typo

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
plugin/src/main/java/org/opensearch/ml/action/agents/DeleteAgentTransportAction.java

Fixes too-eager restoring of context in cases where it needed to still be stashed

[Feature/multi_tenancy] Delay context restoring for initializing master key and deleting agent

---

common/src/main/java/org/opensearch/sdk/UpdateDataObjectRequest.java
common/src/main/java/org/opensearch/sdk/client/LocalClusterIndicesClient.java
common/src/test/java/org/opensearch/sdk/UpdateDataObjectRequestTests.java
common/src/test/java/org/opensearch/sdk/client/LocalClusterIndicesClientTests.java
plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClient.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java

Implements `UpdateRequest.retryOnConflict()`
- For local and remote OpenSearch client, simply passes through the setting
- For DDB Client, implements the retry logic

[Feature/multi_tenancy] Implement retryOnConflict on UpdateDataObject

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessorTests.java

Backport https://github.com/opensearch-project/ml-commons/commit/853efd6be34f981740dec99dd649754eb085de83 from https://github.com/opensearch-project/ml-commons/pull/2944

[Backport 2.16] fix full_response false and no mapping exceptions (#2944)

---

.github/workflows/CI-workflow.yml
common/src/main/java/org/opensearch/ml/common/connector/ConnectorAction.java
common/src/main/java/org/opensearch/ml/common/input/parameter/clustering/RCFSummarizeParams.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
plugin/src/main/java/org/opensearch/ml/action/batch/TransportBatchIngestionAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java

Depending on the GitHub CI workflow executes it will invoke ./gradlew build which will run tests on random parameters every time, there are locale-code's that will break a build one of them being **az-Cyrl**. The solution was to update the codebase that involved string operations such as `toUpperCase(), toLowerCase()` to `toUpperCase(Locale.Root), toLowerCase(Locale.Root)` In doing this we make the string operations language agnostic meaning it wont be affected on a computer that is set to a different language like Spanish or Turkish.  
- `./gradlew build -DTests.Locale=az-Cyrl` which previously failed now works
- `./gradlew build` builds successfully too.
**TLDR:**
- The change was to update String operations to use `Locale.Root` as a argument to avoid default Locale (which may depend on …

Prevents Locale Code build failures #2967

---

plugin/build.gradle

[build is failing if the aws credentials aren't in the system]

build is failing if the aws credentials aren't in the system

---

common/build.gradle
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceIngestProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java

In ml inference ingest processor, when using jsonpath in input_maps, the json path configuration is set with `always_return_list`, however, in connectors and in ml inference search processors, the configuration is not always return list.
Trying to use the standard  json path configuration in modelExecutor class, so that ml inference search processors and ingest processors are using the same configuration. 
The default config now is returnning the original format of the object,
in the sample doc mentioned in the issue:
for simple object like this sample item index,
```
{
"item_text":"red shoes"
}
```
, if configuring input_map as {"input": "$.item.text"},
the model input will be in original string format
```
{
"input": "red shoes"
}
```
if configuring input_map as {"input": "item.text"}, …

Fix ml inference ingest processor always return list using JsonPath

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/utils/IndexUtils.java
common/src/test/java/org/opensearch/ml/common/utils/IndexUtilsTest.java
memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/indices/MLIndicesHandler.java

Support for `.plugins-ml-config` to be available on all nodes, maximizing availability. This is because config index are small but critical.
Resolves #3002

Support index.auto_expand_replicas 0-all for .plugins-ml-config

---

common/build.gradle
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceIngestProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java

Manual backport due to conflict https://github.com/opensearch-project/ml-commons/pull/2985
https://github.com/opensearch-project/ml-commons/issues/2974

[Backport 2.14] Fix ml inference ingest processor always return list using JsonPath

---

plugin/src/test/java/org/opensearch/ml/action/MLCommonsIntegTestCase.java
plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java

* fix flaky test of PredictionITTests and RestConnectorToolIT (#2437)

[Backport 2.15] fix flaky test of PredictionITTests and RestConnectorToolIT

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/MLConfig.java

* update config index mappings to use with correct field types
(cherry picked from commit 19266992df17ce73063ebd01acb6981602ffbd94)

update config index mappings to use correct field types (#2710) (#2718)

---

common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/test/java/org/opensearch/ml/common/RemoteModelTests.java
common/src/test/java/org/opensearch/ml/common/connector/HttpConnectorTest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLConnectorGetResponseTests.java
common/src/test/java/org/opensearch/ml/common/transport/model/MLUpdateModelInputTest.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/connector/UpdateConnectorTransportActionTests.java

Manual backport due to conflict #2922 (The commit that caused the backport merge conflict)
Resolves #2890 (the initial PR that brought up the bug)
- `./gradlew build` passes on the `backport/backport-2922-to-2.x`

[Backport 2.x] populate time fields for connectors on return (#2922)

---

plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java
plugin/src/test/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployerTests.java
plugin/src/test/resources/org/opensearch/ml/autoredeploy/RemoteModelResult.json

Currently, ml-commons supports remote model auto deployment when first prediction request comes, so in MLModelAutoRedeplyer remote model auto redeployment can be  filtered out.
NA

Filter out remote model auto redeployment

---

docs/tutorials/aws/semantic_search_with_bedrock_titan_embedding_model_in_another_account.md

add tutorial for cross-account model invocation on amazon managed cluster

---

common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/connector/ConnectorAction.java
common/src/main/java/org/opensearch/ml/common/output/MLPredictionOutput.java
common/src/test/java/org/opensearch/ml/common/output/MLPredictionOutputTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtilsTest.java
plugin/src/main/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/test/java/org/opensearch/ml/action/tasks/GetTaskTransportActionTests.java

Enhance batch job task management by adding default action types

Enhance batch job task management by adding default action types

---

plugin/src/main/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/GetTaskTransportActionTests.java

change access control for batch job task APIs from connector to model group's access control

change to model group access for batch job task APIs

---

plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java
plugin/src/test/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployerIT.java
plugin/src/test/resources/org/opensearch/ml/autoredeploy/TracedSmallModelRequest.json

Fix PR #2976 bug due to missing adding function_name and algorithm in querying models

Fix PR #2976 bug due to missing adding function_name and algorithm in querying models

---

common/src/main/java/org/opensearch/sdk/SdkClient.java
common/src/test/java/org/opensearch/sdk/SdkClientTests.java
common/src/test/java/org/opensearch/sdk/client/LocalClusterIndicesClientTests.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/sdkclient/DDBOpenSearchClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClient.java
plugin/src/main/java/org/opensearch/ml/sdkclient/SdkClientFactory.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java

Removes the ability to change the value of the mutiTenancy setting: it must be initialized in `opensearch.yml`.
Two other small changes:
- When multiTenancy was false (which is was while I was figuring out how to set it), Remote client search didn't include the index name, thus returning every document in the cluster/collection.
- improved performance of removing the dot from a system index name from a match-all regex to substring, since I briefly thought this could be a problem when debugging the bug above
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/ma …

[Feature/multi_tenancy] Make tenant awareness setting static

---

common/src/test/java/org/opensearch/sdk/client/LocalClusterIndicesClientTests.java

A test added in #2968 was missing `@Test` annotation and wasn't running. Enabled the test and fixed the test to pass.

[Feature/multi_tenancy] Add missing test annotation and fix the failing test it hid

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/ingest/Ingestable.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ingest/OpenAIDataIngestion.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/ingest/S3DataIngestion.java
plugin/src/main/java/org/opensearch/ml/action/batch/TransportBatchIngestionAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java
plugin/src/test/java/org/opensearch/ml/action/batch/TransportBatchIngestionActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java

Add rate limiting to offline batch inference and ingestion. Set the default bulk size for batch ingestion to 500(optimal value from benchmark). If the batch job tasks exceeds the limits defined in the settings, ml_limit_exceeded exception will be thrown.
~~~
POST /_plugins/_ml/_batch_ingestion{...}
<if exceeding the rate limit>
{
"error": {
{
"type": "m_l_limit_exceeded_exception",
"reason": "Exceeded maximum limit for BATCH_INGEST tasks. To increase the limit, update the plugins.ml_commons.max_batch_ingestion_tasks setting."
}
],
"type": "m_l_limit_exceeded_exception",
"reason": "Exceeded maximum limit for BATCH_INGEST tasks. To increase the limit, update the plugins.ml_commons.max_batch_ingestion_tasks setting."
},
"status": 429
}
~~~
Update settings for rate limits
~~~ …

add rate limiting for offline batch jobs, set default bulk size to 500

---

common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/transport/batch/MLBatchIngestionInput.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/ingest/AbstractIngestionTests.java
plugin/src/main/java/org/opensearch/ml/action/batch/TransportBatchIngestionAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/batch/TransportBatchIngestionActionTests.java

(cherry picked from commit 6384ac3a930e63af3b8887fd32d185e499818204)

[Backport to 2.17] use connector credential in offline batch ingestion (#2989) (#3095)

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponse.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessorTests.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchResponseTests.java

Previously, ml inference search processor only writing prediction results to the hits. Now, Support ML Inference Search Processor Writing to Search Extension when many to one inference. 
Note that it's not supported for one to one inference because the order of one to one inference matters and other processors might rerank the order and mess up the order to match one to one model input and prediction results 
https://github.com/opensearch-project/ml-commons/issues/2878
```
PUT /review_string_index/_doc/1
{
"review": "Dr. Eric Goldberg is a fantastic doctor who has correctly diagnosed every issue that my wife and I have had. Unlike many of my past doctors, Dr. Goldberg is very accessible and we have been able to schedule appointments with him and his staff very quickly. We are happy to …
```

Support ML Inference Search Processor Writing to Search Extension 

---

common/build.gradle
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/ModelExecutor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessorTests.java

Enable pass query string to input_map in ml inference search response processor
```
PUT _cluster/settings
{
"persistent": {
"plugins": {
"ml_commons": {
"only_run_on_ml_node": "false",
"model_access_control_enabled": "true",
"native_memory_threshold": "99"
}
}
}
}
```
```
POST /_plugins/_ml/models/_register
{
"name": "huggingface/cross-encoders/ms-marco-MiniLM-L-6-v2",
"version": "1.0.2",
"model_format": "TORCH_SCRIPT"
}
```
```
{
"task_id": "tQ5p1ZEB4iWlnHsIf2Xw",
"status": "CREATED"
}
```
`GET /_plugins/_ml/tasks/tQ5p1ZEB4iWlnHsIf2Xw`
```
{
"model_id": "tg5p1ZEB4iWlnHsIh2U9",
"task_type": "REGISTER_MODEL",
"function_name": "TEXT_SIMILARITY",
"state": "COMPLETED",
"worker_node": [
"AahcbpI9R2OtId7Wnt0cYA"
],
"create_time": 1725862346467,
"last_update_time": 1725862356009,
"is_async": …
```

Enable pass query string to input_map in ml inference search response processor

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java

When agent runs failed, MLAgentExecutor always show the error log with `Failed to run flow agent`, no matter which type the current agent is.
```
[2024-08-07T11:07:01,763][ERROR][o.o.m.e.a.a.MLAgentExecutor] [c889f3b35c9d] Failed to run flow agent
[2024-08-07T11:11:08,935][ERROR][o.o.m.e.a.a.MLAgentExecutor] [c889f3b35c9d] Failed to run conversational agent
```

[BugFix] Fix error log to show the right agent type

---

.github/workflows/require-approval.yml

allowing backport prs to skip approval

---

plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskCache.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLProfileActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLStatsActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUndeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

fix model stuck in deploying state during node crash/cluster restart

fix model stuck in deploying state during node crash/cluster restart

---

.github/workflows/require-approval.yml

[updating the approval requirement so that it can trigger always for opensearch-trigger-bot[bot]]

updating the approval requirement

---

common/src/main/java/org/opensearch/sdk/SdkClient.java
common/src/test/java/org/opensearch/sdk/SdkClientTests.java
common/src/test/java/org/opensearch/sdk/client/LocalClusterIndicesClientTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java
plugin/src/test/java/org/opensearch/ml/sdkclient/DDBOpenSearchClientTests.java
plugin/src/test/java/org/opensearch/ml/sdkclient/RemoteClusterIndicesClientTests.java

Adds a check that all the SDKClient requests have a non-null or empty tenant id when multitenancy is enabled.  
This should not be user-facing, but exists as a check to developers.

[Feature/multi_tenancy] Validate non-null or empty tenant ID in requests when multitenancy enabled

---

plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java

This PR add textract and comprehend url to trusted enpoints, which already supported in our blueprints

Add textract and comprehend url to trusted enpoints

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

[
Currently stackTrack is having different error message:
```
org.opensearch.client.ResponseException: method [POST], host [http://[::1]:63080], URI [/_plugins/_ml/models/.  ioJyv5IBqF95HT6CBDHZ/_predict], status line [HTTP/1.1 400 Bad Request
{"error":{"root_cause":[{"type":"status_exception","reason":"Error from remote service: {\n  \"error\": {\n
\"message\": \"400: There was an error parsing the body\",\n    \"type\": \"server_error\",\n    \"param\": null,\n
\"code\": null\n  }\n}"}],"type":"status_exception","reason":"Error from remote service: {\n  \"error\": {\n
\"message\": \"400: There was an error parsing the body\",\n    \"type\": \"server_error\",\n    \"param\": null,\n
\"code\": null\n  }\n}"},"status":400}
```
Removing this integ test as this is not an issue anymore. …

unblocking the integ test pipeline for release

---

common/src/main/java/org/opensearch/ml/common/transport/deploy/MLDeployModelInput.java
common/src/main/java/org/opensearch/ml/common/transport/forward/MLForwardInput.java
common/src/test/java/org/opensearch/ml/common/transport/deploy/MLDeployModelNodesRequestTest.java
plugin/src/main/java/org/opensearch/ml/action/controller/CreateControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/controller/DeleteControllerTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/deploy/TransportDeployModelOnNodeAction.java
plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java
plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/action/syncup/TransportSyncUpOnNodeActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

…loy request
[applying multi-tenancy for forward request which is important for deploy request
purpose of TransportForwardAction.java is to forward the request to other nodes in a multi-node cluster
Also at the same time, currently in multi-tenancy, if a model is deployed, the status is not being updated in the index. Because that update wasn't happening through sdkclient.
]

applying multi-tenancy for forward request which is important for deploy request

---

release-notes/opensearch-ml-common.release-notes-2.18.0.0.md

[release note for 2.18.0 release]

release note for 2.18.0 release

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java

There is a race condition during initializing master key when encrypt/decrypt credentials in a connector. The encrypt/decrypt thread could get a null key even if the key is fetched from config index successfully in another thread.

increase the wait timeout to fetch the master key

---

plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java

Fixes and enables a non-working unit test.
- wrong argument was captured in one case
- a null (untyped) string wasn't matching `anyString()`. Mocked the non-null string that should go there.
- final test compared to CREATED but should be COMPLETED

[Feature/multi_tenancy] Fix and enable execute remote inference test

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteModelTest.java

Added new tests for missing coverage. Mainly coverage was missing for catching exceptions in the methods initModel() and asyncPredict(). Also renamed some tests to match with testing methods.
Resolves #1382
- [ X] New functionality includes testing.
- [X ] Commits are signed per the DCO using `--signoff`.

[FEATURE]Improve test coverage for RemoteModel.java

---

.github/workflows/CI-workflow.yml

[Backport 2.x] Enable custom start commands and options to resolve GHA issues
Backport https://github.com/opensearch-project/ml-commons/pull/3223
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~ …

[Backport 2.x] Enable custom start commands and options to resolve GHA issues

---

common/src/main/java/org/opensearch/ml/common/connector/MLPreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/functions/preprocess/CohereMultiModalEmbeddingPreProcessFunction.java
common/src/test/java/org/opensearch/ml/common/connector/functions/preprocess/CohereMultiModalEmbeddingPreProcessFunctionTest.java

[adding multi-modal pre-processor for cohere
Cohere multi-modal model either accepts array of texts or array of base64 images (but only 1 item in the array). So if customer wants to use images then then they can use this pre-processor. 
]

adding multi-modal pre-processor for cohere

---

common/src/main/java/org/opensearch/ml/common/connector/functions/preprocess/CohereMultiModalEmbeddingPreProcessFunction.java

[getFirst is not allowed in java 17]

getFirst is not allowed in java 17

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java

* increase the wait timeout to fetch the master key
* fix UTs

[backport 2.13] increase the wait timeout to fetch the master key (#3151) (#3178)

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java

Retrieve remote model id from registration response in IT to avoid flaky, an example is: 
```
RestBedRockInferenceIT > test_bedrock_multimodal_model_empty_imageInput_null_textInput FAILED
org.opensearch.client.ResponseException: method [POST], host [http://127.0.0.1:45675/], URI [/_plugins/_ml/models/null/_deploy], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"status_exception","reason":"Failed to find model"}],"type":"status_exception","reason":"Failed to find model"},"status":404}
at __randomizedtesting.SeedInfo.seed([7D8B7621F7A9A3F2:CB22567814C8B651]:0)
at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:501)
at app//org.opensearch.client.RestClient.performRequest(RestClient.java:384)
at …
```

Retrieve remote model id from registration response in IT to avoid flaky

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java
plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java

This PR attempts to remedy two Flaky classes 
- [RestMLGuardrailsIT.java](https://github.com/opensearch-project/ml-commons/compare/main...brianf-aws:ml-commons:flaky-it-involving-model-fix?expand=1#diff-b973f1adfdde1699a1f4f9a8b7d048b27c01c88c86a836c7c4cc3d6fbae970fb) Borrows code cleanup from https://github.com/opensearch-project/ml-commons/pull/3244 Which removes an extra call to the Task API to get the model id.
- [ToolIntegrationWithLLMTest.java](https://github.com/opensearch-project/ml-commons/compare/main...brianf-aws:ml-commons:flaky-it-involving-model-fix?expand=1#diff-072749d2af860644b27fbe28a9b486d52580d5845e9c82a537f28ed9dcd3cfd8) updates the class to specifically check for the status of the model by calling `GET /_plugins/_ml/models/ modelId` and actively blocking after 5 …

Fixes Two Flaky IT classes RestMLGuardrailsIT & ToolIntegrationWithLLMTest

---

plugin/src/main/java/org/opensearch/ml/autoredeploy/MLModelAutoReDeployer.java

fix for sync up job not working in 2.17 when upgraded from previous versions
Resolves https://github.com/opensearch-project/ml-commons/issues/3238

fix for sync up job not working in 2.17 when upgraded from previous versions

---

common/src/main/java/org/opensearch/ml/common/connector/ConnectorAction.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/connector/ConnectorActionTest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportCreateConnectorActionTests.java

This PR addresses the first part of this enhancement "Validate if connector payload has all the required fields. If not provided, throw the illegal argument exception". Validation of field credentials is added in this fix. All other validations already exist. Added new test cases corresponding to this validation, fixed all failing test cases because of this new validation and refactored some of the test case code.
Partially Resolves #1382
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~ …

[Enhancement] Enhance validation for create connector API

---

common/src/main/java/org/opensearch/ml/common/conversation/ConversationMeta.java
common/src/test/java/org/opensearch/ml/common/conversation/ConversationMetaTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationResponseTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationsResponseTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationsTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandlerTests.java

Modify getMemory(Conversation) to return the application_type parameter. Include application_type in the ConversationMeta data model. Update existing tests to validate the new parameter.
Add application_type in conversation meta and make other parts of code compatible to this new parameter
Resolves #3279

Add application_type to ConversationMeta; update tests

---

common/src/main/java/org/opensearch/ml/common/conversation/Interaction.java
common/src/test/java/org/opensearch/ml/common/conversation/InteractionTests.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequest.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateInteractionRequest.java
memory/src/main/java/org/opensearch/ml/memory/index/ConversationMetaIndex.java
memory/src/main/java/org/opensearch/ml/memory/index/InteractionsIndex.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationRequestTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateInteractionRequestTests.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexITTests.java
memory/src/test/java/org/opensearch/ml/memory/index/ConversationMetaIndexTests.java
memory/src/test/java/org/opensearch/ml/memory/index/InteractionsIndexTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/memory/MLMemoryManager.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/memory/MLMemoryManagerTests.java

Skip saving empty fields in interactions and conversations to optimize storage usage. 
Modify GET requests for interactions and conversations to return only non-null fields. 
Throw an exception if all fields in a create interaction call are empty or null. 
Add unit tests to cover the above cases.
Resolves #3250

Enhance Message and Memory API Validation and storage

---

build.gradle
common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle

Bump guava version to 32.1.3 to resolve version conflicts in neural search plugin to compile ml-commons plugin.
```
| Caused by: java.lang.IllegalStateException: jar hell!
| class: com.google.common.annotations.Beta
| jar1: /local/home/junqiu/dev/neural-search/build/testclusters/integTest-0/distro/3.0.0-ARCHIVE/plugins/opensearch-ml/guava-32.1.2-jre.jar
| jar2: /local/home/junqiu/dev/neural-search/build/testclusters/integTest-0/distro/3.0.0-ARCHIVE/plugins/opensearch-knn/guava-32.1.3-jre.jar
|       at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:316)
|       at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:215)
|       at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:675)
|       ... 11 more
``` …

Bump guava version to 32.1.3

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/regression/LinearRegression.java

Updated default optimiser from SIMPLE_SGD to ADA_GRAD
Resolves #3210

Use Adagrad optimiser for Linear regression by default

---

common/src/main/java/org/opensearch/ml/common/utils/ModelInterfaceUtils.java
plugin/src/test/java/org/opensearch/ml/utils/MLNodeUtilsTests.java

All remote embedding model will throw exception when use embedding input instead of remote input. However Neural Search uses a hardcoded value `FunctionName.TEXT_EMBEDDING` when instantiating the `MLInput`:
https://github.com/opensearch-project/neural-search/blob/7feacd67b3c7694ff4a1c1c2b430f2447a1ed4ab/src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java#L293
Therefore, we removed the required string `parameter` in input interface to enable the dual usage of remote model. In the future, we plan to use different interface on different usage in same connector as a long term fix.
Resolves #3261
For more information on following Developer Certificate of …

Fix remote model with embedding input issue

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java
plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java

This backport (`2.x`) is to improve two Flaky classes (RestMLGuardrailsIT, ToolIntegrationWithLLMTest). This was a result of https://github.com/opensearch-project/ml-commons/pull/3253
- `./gradlew  :opensearch-ml-plugin:compileJava `
- `./gradlew test`

(Backport 2.x) Fixes Two Flaky IT classes RestMLGuardrailsIT & ToolIntegrationWithLLMTest

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceIngestProcessorIT.java
plugin/src/test/java/org/opensearch/ml/utils/TestData.java

Currently local models that use the parameters map within the payload to create a request can not create objects to be used for local model prediction, when using the MLInferenceIngestProcessor. 
e.g.
```json
POST {{ _.domain }}/_plugins/_ml/_predict/text_embedding/{{ _.model_id }}
{
"content_type": "query"
},
"text_docs": ["What day is it today?"],
"target_response": ["sentence_embedding"]
}
PUT {{ _.domain }}/_ingest/pipeline/asymmetric_embedding_ingest_pipeline
{
"description": "ingest passage text and generate a embedding using an asymmetric model",
"processors": [
{
"ml_inference": {
"model_input": "{\"text_docs\":[\"${input_map.text_docs}\"],\"target_response\":[\"sentence_embedding\"],\"parameters\":{\"content_type\":\"query\"}}",
"function_name": "text_embedding", …
```

Adds preset contentRegistry for IngestProcessors

---

build.gradle
common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle

Backport https://github.com/opensearch-project/ml-commons/pull/3300 into 2.x branch

[backport 2.x] Bump guava version to 32.1.3

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/AgentUtilsTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunnerTest.java

https://github.com/opensearch-project/ml-commons/issues/3134

add action input as parameters for tool execution in conversational agent

---

plugin/build.gradle

Address CVE vulnerability in plugin/build.gradle: org.eclipse.core.runtime-3.26.100.jar by forcing version 3.29.0

Force version 3.29.0 of org.eclipse.core.runtime to address CVE vulnerabilities

---

docs/tutorials/semantic_search/asymmetric_embedding_model.md

This PR implements the tutorial required for local asymmetric model embeddings. In this specific tutorial it is done using a docker container, to help users take advantage of multi node clusters using ML Nodes. 
Resolves #3255

Tutorial for using Asymmetric models

---

common/src/main/java/org/opensearch/ml/common/utils/ModelInterfaceUtils.java
plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/utils/MLNodeUtils.java
plugin/src/test/java/org/opensearch/ml/utils/MLNodeUtilsTests.java

[backport 2.16] Fix remote model with embedding input issue #3289

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Test several time on 2.x and 2.13 (the latest branch with this test), seems not flaky. Will add it back and see if we need a fix in the future.

Remove ignore decorator for testCohereClassifyModel

---

common/src/test/java/org/opensearch/ml/common/connector/ConnectorActionTest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java

Text Block changes introduced in JDK15. Even though our main release is based on JDK21, 2.x is still based on JDK11. So to support auto bot backport of these test files in the future, reverting Text Block related changes from test cases.
Revert Text Block changes from #3260
- [] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~

Revert Text Block changes from "Enhance validation for create connector API" #3260

---

docs/tutorials/rerank/rerank_pipeline_with_bge-rerank-m3-v2_model_deployed_on_Sagemaker.md

fix post_process_function on rerank_pipeline_with_bge-rerank-m3-v2_model_deployed_on_Sagemaker.md (#3247)
Resolves #3247 

fix post_process_function on rerank_pipeline_with_bge-rerank-m3-v2_model_deployed_on_Sagemaker.md

---

common/src/main/java/org/opensearch/ml/common/conversation/ConversationMeta.java
common/src/test/java/org/opensearch/ml/common/conversation/ConversationMetaTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationResponseTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationsResponseTests.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/GetConversationsTransportActionTests.java
memory/src/test/java/org/opensearch/ml/memory/index/OpenSearchConversationalMemoryHandlerTests.java

This reverts commit d09374c3feb277a514d641dbc7bf91dce19ec303.

Revert "Add application_type to ConversationMeta; update tests (#3282)"

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceIngestProcessorIT.java
plugin/src/test/java/org/opensearch/ml/utils/TestData.java

2.18 : Backport PR for  add preset xContentRegistry to ingestProcessors for custom parametized local models
See: https://github.com/opensearch-project/ml-commons/issues/3316

[Backport 2.18] Adds preset contentRegistry for IngestProcessors (#3281)

---

common/src/main/java/org/opensearch/ml/common/connector/ConnectorAction.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/connector/ConnectorActionTest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportCreateConnectorActionTests.java

Backporting these two PRs together becasue auto backporting of 3260 failed becasue of usage of Text Blocks, 3329 is to revert the usage of Text Blocks.
Back porting #3260 and #3329
~- [ ] New functionality has been documented.~
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~

[Backport to 2.x] Backport #3260 and #3329

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

* unblocking the integ test pipeline for release
* apply spotless
* removing the integ test intirely
---------

[Backport 2.13] unblocking the integ test pipeline for release (#3159)

---

.github/workflows/CI-workflow.yml
common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/input/Constants.java
common/src/main/java/org/opensearch/ml/common/settings/SettingsChangeListener.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorGetRequest.java
common/src/main/resources/index-mappings/ml_agent.json
common/src/main/resources/index-mappings/ml_config.json
common/src/main/resources/index-mappings/ml_connector.json
common/src/main/resources/index-mappings/ml_model.json
common/src/main/resources/index-mappings/ml_model_group.json
common/src/main/resources/index-mappings/ml_task.json
gradle/wrapper/gradle-wrapper.properties
ml-algorithms/build.gradle
ml-algorithms/src/test/java/org/opensearch/ml/engine/indices/MLIndicesHandlerTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/connector/GetConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetConnectorAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/main/java/org/opensearch/ml/utils/TenantAwareHelper.java
plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/settings/MLFeatureEnabledSettingTests.java
plugin/src/test/java/org/opensearch/ml/tools/ToolIntegrationWithLLMTest.java
plugin/src/test/java/org/opensearch/ml/utils/TenantAwareHelperTests.java

In this PR, I'm just adding the primary setup required for [Multi-tenancy feature](https://github.com/opensearch-project/ml-commons/tree/feature/multi_tenancy). After this PR, I'll start raising other PRs for adding multi-tenancy in connector, model, agents etc.

Primary setup for Multi-tenancy

---

.github/workflows/CI-workflow.yml
common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/connector/AbstractConnector.java
common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/input/Constants.java
common/src/main/java/org/opensearch/ml/common/settings/SettingsChangeListener.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorGetRequest.java
common/src/main/resources/index-mappings/ml-agent.json
common/src/main/resources/index-mappings/ml-config.json
common/src/main/resources/index-mappings/ml-connector.json
common/src/main/resources/index-mappings/ml-model-group.json
common/src/main/resources/index-mappings/ml-model.json
common/src/main/resources/index-mappings/ml-task.json
gradle/wrapper/gradle-wrapper.properties
ml-algorithms/build.gradle
ml-algorithms/src/test/java/org/opensearch/ml/engine/indices/MLIndicesHandlerTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/connector/GetConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetConnectorAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/main/java/org/opensearch/ml/settings/MLFeatureEnabledSetting.java
plugin/src/main/java/org/opensearch/ml/utils/TenantAwareHelper.java
plugin/src/test/java/org/opensearch/ml/action/prediction/PredictionITTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/settings/MLFeatureEnabledSettingTests.java
plugin/src/test/java/org/opensearch/ml/utils/TenantAwareHelperTests.java

* multi-tenancy primary setup
* addressed comments
* addressed comments + fixed dependency issue
* adding more log to debug the testVisualizationFound issue
* changing back
---------

[Manual Backport to 2.x] Primary setup for Multi-tenancy (#3307)

---

plugin/src/main/java/org/opensearch/ml/action/forward/TransportForwardAction.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskCache.java
plugin/src/test/java/org/opensearch/ml/action/forward/TransportForwardActionTests.java
plugin/src/test/java/org/opensearch/ml/cluster/MLSyncUpCronTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLProfileActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLStatsActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUndeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

(cherry picked from commit bb6339ff6f4a04adb259c24cb4b3bc80625278fb)
Backport PR https://github.com/opensearch-project/ml-commons/pull/3137 to 2.13

[Backport 2.13] fix model stuck in deploying state during node crash/cluster restart (#3137)

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
common/src/main/java/org/opensearch/ml/common/connector/AwsConnector.java
common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorDeleteRequest.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLConnectorGetResponse.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLConnectorDeleteRequestTests.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLConnectorGetResponseTests.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/MultiTenantPredictable.java
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/GetConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/helper/ConnectorAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeleteConnectorAction.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/action/connector/DeleteConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/GetConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportCreateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/helper/ConnectorAccessControlHelperTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLCreateConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

[apply multi-tenancy and sdk client in Connector (Create + Get + Delete)]
By default, this is single tenant. If we enable [multi-tenancy settings](https://github.com/opensearch-project/ml-commons/blob/main/plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java#L302-L303), then the request will expect an header `x-tenant-id`. And one tenant won't be able to access other tenant's resource. 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of- …

apply multi-tenancy and sdk client in Connector (Create + Get + Delete)

---

.github/workflows/CI-workflow.yml

This PR modifies the CI pipeline to run the Spotless check on JDK 17 separately from the rest of the build process, which continues to use JDK 11, 17, and 21.
Since we bumped the org.eclipse.core.runtime to 3.29.0 to address the CVE issues in #3313, spotlessJava fails with JDK 11 since 3.29.0 is built with a minimum Required Execution Environment of Java 17.

Separate Spotless Check to JDK 17 and Exclude from other Build Process

---

.github/workflows/CI-workflow.yml

Added Spotless check step to main branch to maintain workflow consistency with 2.x branch. While version compatibility is only an issue in 2.x, maintaining parallel workflow structure prevents branch drift and simplifies future maintenance.

Add Spotless Check to maintain consistency

---

plugin/build.gradle

[updating sdk client version to reflect this change: https://github.com/opensearch-project/opensearch-remote-metadata-sdk/pull/45]

updating sdk client version

---

.github/workflows/CI-workflow.yml

Without the runs-on field, the spotless check step fails

Add runs-on field to Spotless Check step in CI

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceIngestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceIngestProcessorIT.java
plugin/src/test/java/org/opensearch/ml/utils/TestData.java

Backport PR for  add preset xContentRegistry to ingestProcessors for custom parametized local models
See: https://github.com/opensearch-project/ml-commons/issues/3316

[Backport 2.x] Adds preset contentRegistry for IngestProcessors (#3281)

---

.github/workflows/CI-workflow.yml

```
==> Running git config --global --add safe.directory /__w/ml-commons/ml-commons
/usr/bin/git config --global --add safe.directory /__w/ml-commons/ml-commons
==> Running command '/__w/_actions/codecov/codecov-action/v4/dist/codecov create-commit'
/__w/_actions/codecov/codecov-action/v4/dist/codecov create-commit --git-service github -C b777894ada4b7252b432703ece8e92261ef094e9 --pr 3399
[PYI-7170:ERROR] Failed to load Python shared library '/tmp/_MEIF9N3ND/libpython3.11.so.1.0': dlopen: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIF9N3ND/libpython3.11.so.1.0)
Warning: Codecov: Failed to properly create commit: The process '/__w/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 255
```
Currently code cove is not generating reporting. As …

downgrading codecov action

---

.github/workflows/CI-workflow.yml

Without this it pulls the code without the updates specific to the PR.

Checkout code from pull request head for spotless

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/MLModelTool.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/utils/AgentModelsSearcher.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/MLModelToolTests.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/utils/AgentModelSearcherTests.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/action/models/DeleteModelTransportActionTests.java
spi/src/main/java/org/opensearch/ml/common/spi/tools/WithModelTool.java

Manually backport to resolve dco problem  for https://github.com/opensearch-project/ml-commons/pull/3430
Backport https://github.com/opensearch-project/ml-commons/commit/570edaf8ca48f08491706175755330bd24075143 from https://github.com/opensearch-project/ml-commons/pull/3209
* add logic to detect agent before deleting
* add logic to detect agent before deleting
* add logic to detect pipelines before delete model
* check pipeline before deleting
* apply spotless
* remove useless file
* rename functions
* fix failure test
* add UT
* apply spotless
* renam
* refactor to parallel check
* concate error message
* move logic after user access check
* change agent model searcher map to set
* rename and remove useless method
* fix bug to fetch all pipelines
* apply spotless
* apply spotless
* …

[Backport 2.x] Check before delete

---

common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java
memory/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/ModelExecutor.java
plugin/src/main/java/org/opensearch/ml/searchext/MLInferenceRequestParameters.java
plugin/src/main/java/org/opensearch/ml/searchext/MLInferenceRequestParametersExtBuilder.java
plugin/src/main/java/org/opensearch/ml/searchext/MLInferenceRequestParametersUtil.java
plugin/src/test/java/org/opensearch/ml/plugin/MachineLearningPluginTests.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessorTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceSearchRequestProcessorIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceSearchResponseProcessorIT.java
plugin/src/test/java/org/opensearch/ml/searchext/MLInferenceRequestParametersExtBuilderTests.java
plugin/src/test/java/org/opensearch/ml/searchext/MLInferenceRequestParametersUtilTests.java

Introduce Ml Inference Search Request Extension, this is adding ml_inference search extension during search request/query phase,
For the search response side, I already introduced a  `ml_inference` search response extension in earlier PR released in 2.18.  [Support ML Inference Search Processor Writing to Search Extension](https://github.com/opensearch-project/ml-commons/commit/09aa6ea0b108c29ff074292278370c2f5e772688)
https://github.com/opensearch-project/ml-commons/issues/3286
https://github.com/opensearch-project/ml-commons/issues/3054 …

Introduce Ml Inference Search Request Extension

---

plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportCreateConnectorActionTests.java

Add DeepSeek url as a trusted endpoint, preventing users from having to manually add it to use the model.
Resolves https://github.com/opensearch-project/ml-commons/pull/3436#discussion_r1931211336

Add DeepSeek as a trusted endpoint

---

plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsActionTests.java

This PR  aims to undeploy modelIds that have no nodes associated to them so as to keep the intention of undeploy truthful.
When performing undeploy if the model has no nodes associated to it then it will reset the index to UNDEPLOY status
Here is an example of why this code change is needed
This secnario is for the `PARTIALLY_DEPLOYED` issue.
1. Have nodes a,b,c,d in cluster associated with `modelID:@` i.e. peform deploy on it
2. Bring a,b down while having the syncup job running
3. By Now sync up will make this PARTIALLY_UNDEPLOYED
4. stop sync up
5. Bring other 2 c,d down and bring 2 nodes (these now have new ids 1,2)
6. bring the other two nodes back which have different ids so now the cluster has (1,2,3,4)
But the model index says `PARTIALLY_DEPLOYED` and no nodes are servicing
This …

Undeploy models with no WorkerNodes

---

plugin/build.gradle

Java 11 builds will fail with current spotless implementation e.g.
```
% sdk use java 11.0.25-amzn 
Using java version 11.0.25-amzn in this shell.
%  ./gradlew spotlessApply                     
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details
[Incubating] Problems report is available at: file:///Users/iflorbri/IdeaProjects/ml-commons/build/reports/problems/problems-report.html
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':opensearch-ml-plugin'.
> java.io.IOException: Failed to load eclipse jdt formatter: java.lang.RuntimeException: org.tukaani.xz.XZFormatException: Input is not in the XZ format
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug …
```

Fixes spotless on Java 11

---

common/src/main/java/org/opensearch/ml/common/connector/MLPostProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/MLPreProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/functions/postprocess/BedrockRerankPostProcessFunction.java
common/src/main/java/org/opensearch/ml/common/connector/functions/preprocess/BedrockRerankPreProcessFunction.java
common/src/test/java/org/opensearch/ml/common/connector/functions/postprocess/BedrockRerankPostProcessFunctionTest.java
common/src/test/java/org/opensearch/ml/common/connector/functions/preprocess/BedrockRerankPreProcessFunctionTest.java

Amazon Bedrock introduced Rerank model support. OpenSearch can invoke Rerank models on Bedrock by writing custom pre and post processing function, but pre-built function is good for performance.
I implemented new four classes. 
- BedrockRerankPostProcessFunction
- BedrockRerankPreProcessFunction
- BedrockRerankPostProcessFunctionTest
- BedrockRerankPreProcessFunctionTest
BedrockRerankPreProcessFunction converts input from ml-commons to request payload of Bedrock Rerank API as follows.
**input**
```
{
"query_text": "What is the capital city of America?",
"text_docs": [
"Carson City is the capital city of the American state of Nevada.",
"The Commonwealth of the Northern Mariana Islands is a group of islands in the Pacific Ocean. Its capital is Saipan.",
"Washington, D.C. (also known as …
```

Add pre and post process functions for Bedrock Rerank API #3254

---

docs/tutorials/aws/RAG_with_DeepSeek_Chat_model.md
docs/tutorials/aws/RAG_with_DeepSeek_R1_model_on_Bedrock.md
docs/tutorials/aws/RAG_with_DeepSeek_R1_model_on_Sagemaker.md

This tutorial introduces how to use DeepSeek model deployed on Sagemaker to build RAG in OpenSearch 

add tutorial for RAG with DeepSeek R1 model on Sagemaker

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java

Fix guardrail it for 2.19

---

common/src/main/java/org/opensearch/ml/common/transport/search/MLSearchActionRequest.java
common/src/test/java/org/opensearch/ml/common/transport/search/MLSearchActionRequestTest.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/SearchConversationsTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/TransportSearchAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/SearchConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/SearchModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/SearchModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/SearchTaskTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/agents/TransportSearchAgentActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelITTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/SearchTaskTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchAgentActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchConnectorActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchModelGroupActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMemorySearchConversationsActionTests.java

In this PR, I'm making MLSearchActionRequest as a subclass of SearchActionRequest to follow the standard. Previously I wasn't quite extending the SearchActionRequest, as I had another SearchActionRequest object in the class and it was being read and written twice. 

changing MLSearchActionRequest to an instance subclass of SearchActionRequest

---

client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java

[addressing client changes due to adding tenantId in the apis]

addressing client changes due to adding tenantId in the apis

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java

This PR fixes CI issues seen in the skills repo when testing with security. 
ref: https://github.com/opensearch-project/skills/actions/runs/13076372692/job/36489480535
This PR surrounds the call to the `.plugins-ml-connector` index in a stashed context to ensure the action runs in a trusted system context.
The security plugin has logic to scrub results when searching on system indices or getting individual documents for regular users. Plugins must surround calls to system indices to run in the trusted system context. …

Run the Get Connector request in a stashed threadcontext

---

plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsActionTests.java

This is a manual backport to the feature/multi_tenancy branch.
Needed to adapt the Mockito doAnswer to different parameters to make sure test passed. 
Fixes https://github.com/opensearch-project/ml-commons/pull/3380#issuecomment-2637924367
- ./gradlew test
- ./gradlew spotlessApply

Backport/backport 3380 to feature/multi tenancy

---

plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsActionTests.java

Reverts opensearch-project/ml-commons#3505

Revert "Backport/backport 3380 to feature/multi tenancy"

---

plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java

fix null decrypted credential while getting batch predict job status

fix null decrypted credential while getting batch predict job status

---

plugin/src/main/java/org/opensearch/ml/action/agents/TransportSearchAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/models/SearchModelTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/agents/TransportSearchAgentActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java

[remaining sdk client changes for search operations]

remaining sdk client changes for search operations

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

applying sdkclient (wrapper of client) to config index during index related operations

applying sdkclient changes to config index

---

plugin/src/main/java/org/opensearch/ml/action/register/TransportRegisterModelAction.java

[adding tenantId for inline connector in model registration]

adding tenantId for inline connector in model registration

---

client/build.gradle
common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle

Upgraded mockito in all the packages and made sure the failing test testcases in #3546 are passing.
Did not run all the test cases in local to save time(takes 30 mins).
MERGE ONLY AFTER JDK 23 BUILD PASSES

Mockito upgrade to support JDK 23

---

plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsActionTests.java

There is a code change that requires to check the response of the model undeploy response object to check that the model has been marked as not found on all nodes.
Previously when we received a `{}`response it was assumed that  no nodes are servicing the model but it turns out there was a code change that didn't update the model index but reported back that it couldn't find the model 
```
{
"ZSDYur-iTNezJKo8KibrkA": {
"stats": {
"pt2r8ZQBFvLEBI9XgEUD": "not_found"
}
},
"6sw6aS_BTXiX2U-Xww_lNw": {
"stats": {
"pt2r8ZQBFvLEBI9XgEUD": "not_found"
}
},
"_I3xR4dLQSuKhbO06lpoGQ": {
"stats": {
"pt2r8ZQBFvLEBI9XgEUD": "not_found"
}
},
"Jd1kEmnoTWyeJkalOiAakg": {
"stats": {
"pt2r8ZQBFvLEBI9XgEUD": "not_found"
}
}
}
```
A. Normal case
1. deploy model
2. undeploy model (you get shape like above but …

[main] Undeploy code change: add edge case for models that are marked as not found in cache #3520

---

docs/remote_inference_blueprints/amazon_comprehend_connector_blueprint.md

There was a typo in the doc. 'Comrehend'-> 'Comprehend'
Typo is fixed
None

TypoFix in amazon_comprehend_connector_blueprint.md

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessorTests.java

fix ignoreFailure was not parsing properly in ml inference search processors 

fix ignoreFailure flag in ml inference search processors

---

common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle

address CVEs CVE-2025-25193, CVE-2025-24970, CVE-2024-57699

---

DEVELOPER_GUIDE.md
dev-docker-compose.yml
docs/docker/dev-docker-compose.yml

While working on a recent issue, I faced challenges figuring out how to test my implementation locally. Thankfully, @brianf-aws guided me on how to run `ml-commons` from the source code.
To help new contributors avoid similar confusion, I’ve added clear instructions on how to build and run OpenSearch from source, enabling them to test their changes effectively.

Add instructions to run OpenSearch from source code

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/ModelExecutor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessorTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceSearchRequestProcessorIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceSearchResponseProcessorIT.java

fix optional mappings in ml inference search processors by adding new parameters `optional_input_map` and  `optional_output_map`. Please refer to the REST IT test to see the sample settings.
[[Resolves #[Issue number to be closed when this PR is merged]
](https://github.com/opensearch-project/ml-commons/issues/3563)](https://github.com/opensearch-project/ml-commons/issues/3563)

fix optional mappings in ml inference search processors

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceSearchRequestProcessorIT.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLInferenceSearchResponseProcessorIT.java

Earlier the RestMLInferenceSearchRequestProcessorIT has an IT test rewrites to a range query searching on a keyword field, it's flaky, so change to querying an integer field to return stable search result. 

Fix flaky IT test on range query in RestMLInferenceSearchRequestProcessorIT

---

plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionAction.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLPredictionActionTests.java

In stead of using user input algorithm we use model type extracting from model cache to check local or remote model, this will fix disable local model will cause remote neural search failure issue

Use model type to check local or remote model

---

docs/tutorials/ml_inference/semantic_search/optimize_vector_search_with_cohere_compressed_embedding.md

Fix template query link on documentation

Fix template query link on documentation

---

docs/tutorials/conversational_search/conversational_search_with_Bedrock_Claude.md
docs/tutorials/conversational_search/conversational_search_with_OpenAI.md

Add tutorial for RAG of OpenAI and bedrock

add tutuorial for RAG of openai and bedrock

---

client/build.gradle
client/src/main/java/org/opensearch/ml/client/MachineLearningClient.java
client/src/main/java/org/opensearch/ml/client/MachineLearningNodeClient.java
client/src/test/java/org/opensearch/ml/client/MachineLearningClientTest.java
client/src/test/java/org/opensearch/ml/client/MachineLearningNodeClientTest.java
memory/src/main/java/org/opensearch/ml/memory/action/conversation/CreateConversationResponse.java
memory/src/test/java/org/opensearch/ml/memory/action/conversation/CreateConversationResponseTests.java

Reverts opensearch-project/ml-commons#3475 to unblock Flow Framework

Revert "Added Conversation API in MLClient"

---

plugin/src/test/java/org/opensearch/ml/rest/RestMLRemoteInferenceIT.java

Update the CB setting to 100 to bypass the memory check for remote models.
https://github.com/opensearch-project/ml-commons/issues/3544

update CB setting to 100 to bypass memory check

---

plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java

fixing security integ test

---

plugin/build.gradle

2.24.2 version of log4j introduces an exception: https://github.com/apache/logging-log4j2/issues/3234, causing flakiness in test cases. Removing this will use the version used in openSearch core (currently 2.21.0)
Resolves #3550

Remove forcing log4j version to 2.24.2

---

.github/workflows/CI-workflow.yml
common/src/test/java/org/opensearch/ml/common/transport/agent/MLAgentGetResponseTest.java
common/src/test/java/org/opensearch/ml/common/transport/agent/MLRegisterAgentRequestTest.java
docs/tutorials/agent_framework/build_your_own_chatbot.md
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/AgentUtilsTest.java
plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLFlowAgentIT.java
plugin/src/test/java/org/opensearch/ml/rest/SecureMLRestIT.java
plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

fix failure ITs and syntax error in CI workflow
In this PR: https://github.com/opensearch-project/ml-commons/pull/3243, the CI checks on Linux and Windows are passing but docker is failing and if check carefully, it's caused by missing tool: CatIndexTool. This PR is to fix the failure ITs in docker env.
In this PR: https://github.com/opensearch-project/ml-commons/actions/runs/13847649530/job/38749255141?pr=3652 the CI workflow has syntax issue, this PR also fix this.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate- …

fix failure ITs and syntax error in CI workflow

---

common/src/main/java/org/opensearch/ml/common/output/model/ModelTensorOutput.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensors.java
common/src/test/java/org/opensearch/ml/common/output/model/ModelTensorOutputTest.java
common/src/test/java/org/opensearch/ml/common/output/model/ModelTensorsTest.java

Previous we have missed the parser method for `ModelTensorOutput` and `ModelTensors`, now we add it back and its corresponding UTs to avoid potential bugs.

Add parser for ModelTensorOutput and ModelTensors

---

plugin/src/test/java/org/opensearch/ml/utils/TestHelper.java

OpenSearch core is renaming the search node role to warm node role: https://github.com/opensearch-project/OpenSearch/pull/17573 which breaks the compilation in ml-commons.

fix compilation error

---

common/src/main/java/org/opensearch/ml/common/output/model/ModelTensorOutput.java
common/src/main/java/org/opensearch/ml/common/output/model/ModelTensors.java
common/src/test/java/org/opensearch/ml/common/output/model/ModelTensorOutputTest.java
common/src/test/java/org/opensearch/ml/common/output/model/ModelTensorsTest.java

Manually backport #3658 to 2.11

[Backport 2.11] Add parser for ModelTensorOutput and ModelTensors 

---

plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java

The model search for delete connector incorrectly overwrote the search for connector ID with one for tenant ID. 
There is no need to handle tenant ID in searching, as it is handled by the sdk client when tenant awarness is set, see [here](https://github.com/opensearch-project/opensearch-remote-metadata-sdk/blob/65802084bd0a496e32204154c73c6698de3647eb/core/src/main/java/org/opensearch/remote/metadata/client/impl/LocalClusterIndicesClient.java#L434-L451) and [here](https://github.com/opensearch-project/opensearch-remote-metadata-sdk/blob/65802084bd0a496e32204154c73c6698de3647eb/remote-client/src/main/java/org/opensearch/remote/metadata/client/impl/RemoteClusterIndicesClient.java#L513-L525).
Also removed the (redundant) filtering in the search for models in a model group. This properly …

Fix model search for deleting connector

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLChatAgentRunner.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/BedrockConverseFunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/FunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/FunctionCallingFactory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/LLMMessage.java

Bedrock converse claude function calling

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/AwsConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/ConnectorUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/HttpJsonConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/arrow/RemoteModelStreamProducer.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/metrics_correlation/MetricsCorrelationTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/sparse_encoding/TextEmbeddingSparseEncodingModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingDenseModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_similarity/TextSimilarityCrossEncoderModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/tokenize/SparseTokenizerModelTest.java
plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLPredictionStreamingAction.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/main/plugin-metadata/plugin-security.policy
plugin/src/test/java/org/opensearch/ml/action/connector/UpdateConnectorTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/deploy/TransportDeployModelActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLExecuteTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainAndPredictTaskRunnerTests.java
plugin/src/test/java/org/opensearch/ml/task/MLTrainingTaskRunnerTests.java
spi/build.gradle

This pr is the second part following the pr https://github.com/opensearch-project/ml-commons/pull/3599.
The pr is mainly for the community to have an early review about the streaming feature in ml plugin.
Currently this pr can't be built successfully, as it depends on the new streaming feature from opensearch.
https://github.com/opensearch-project/ml-commons/issues/3328

support llm streaming on top of arrow flight

---

.github/workflows/CI-workflow.yml

In this PR: https://github.com/opensearch-project/ml-commons/pull/3243, CI workflow was modified to fix the jacoco not update it's latest result issue, but after that all the PRs failed with below error, e.g. https://github.com/opensearch-project/ml-commons/actions/runs/13911015452/job/38928296296, after further investigation the jacoco not updated is caused by integTest not passing(no actual issue with CI workflow configuration), so reverting the change now. …

revert CI workflow changes

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineClassLoaderTests.java

Improved the test coverage by adding the edge case of initInstance() method returns null.
Some of the branch coverages which are missing are unreachable code. The Function, ConnectorExecutor and Ingester values are non null.
Resolves #1377

[FEATURE] Improve test coverage for MLEngineClassLoader class

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/BedrockConverseDeepseekR1FunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/BedrockMessage.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/FunctionCalling.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/FunctionCallingFactory.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/LLMMessage.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/OpenaiMessage.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/function_calling/OpenaiV1ChatCompletionsFunctionCalling.java

[Function calling] deepseek interface and refactoring

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java

Improved the test coverage by adding missed use cases.
There is no zero argument constructor, constructor with Input as parameter and constructor with MLAlgoParams.class as parameter in the class class org.opensearch.ml.engine.algorithms.metrics_correlation.MetricsCorrelation. So it is impossible to cover remaining potions, it always throws java.lang.NoSuchMethodException: org.opensearch.ml.engine.algorithms.metrics_correlation.MetricsCorrelation.().
Resolves #1376
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of …

[FEATURE] Improve test coverage for MLEngine Class

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/DLModelExecute.java

Upgrade PyTorch version from 1.13.1 to 2.5.1.
Resolves https://github.com/opensearch-project/ml-commons/issues/3515

Upgrade PyTorch Version

---

build.gradle
ml-algorithms/build.gradle

Version bump to 3.0.0-beta1
https://github.com/opensearch-project/opensearch-build/issues/3747

Version bump to 3.0.0-beta1

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Verified the Rest API of batch ingestion is deprecated. Will send out a separate PR for the tech doc. 
~~~
POST /_plugins/_ml/_batch_ingestion
{
"error": "no handler found for uri [/_plugins/_ml/_batch_ingestion] and method [POST]"
}
~~~

deprecate the restful API of batch ingestion

---

docs/remote_inference_blueprints/bedrock_connector_anthropic_claude3.7_blueprint.md

add blueprint for Cluade 3.7 on Bedrock

add blueprint for Cluade 3.7 on Bedrock

---

plugin/src/main/java/org/opensearch/ml/task/MLTaskDispatcher.java

in `dispatchTaskWithRoundRobin` method, MLTaskDispatcher
modify typo of `_cluster/setting` to `_cluster/settings`
Resolves #3693 

typo: MLTaskDispatcher _cluster/settings api

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java

In the config index the source can be:
```
{
"_tenant_id": {
"S": "058264223758:oasistestm8w8ikom"
},
"_id": {
"S": "master_key_xJWBUnkbw8Gsj7pez-f-g0ccK2-JUSRHcD9uh64Mna0="
},
"_seq_no": {
"N": "0"
},
"_source": {
"M": {
"create_time": {
"N": "1743375153989"
},
"master_key": {
"S": "tOVgn8xhoaYWjpgaAWUkvCUiQYcCEDfXv6aA6NJje8Q="
},
"tenant_id": {
"S": "058264223758:oasistestm8w8ikom"
}
}
}
}
```
When we store an ML encryption key, we save it in a config document with:
A unique _id like:  master_key_xJWBUnkbw8Gsj7pez-f-g0ccK2-JUSRHcD9uh64Mna0=
And the actual key value inside the _source field as: "master_key": "<actual AES key>"
The mistake was that when reading the key back, the code incorrectly tried to look it up using the full document ID (like master_key_xJWBUnkbw8...) as the field …

fix config index masterkey pull up for multi-tenancy

---

ml-algorithms/build.gradle

bouncycastle was removed from the gradle version catalog in https://github.com/opensearch-project/OpenSearch/pull/17507/files#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87df.
This PR will use BCFIPS libraries 
https://github.com/opensearch-project/flow-framework/pull/1087 

Add BCFIPS package for security test

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/QAConstants.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModel.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/question_answering/SentenceHighlightingQATranslator.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/QuestionAnsweringModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/SentenceHighlightingQAModelIT.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/SentenceHighlightingQAModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/question_answering/SentenceHighlightingQATranslatorTest.java

Update highlighting QA model to adapt new highlighter model:
* Add chunk strategy due to model max length limitation to 512 by default
* Introduced `sentence_ids` which is required by new model
https://github.com/opensearch-project/neural-search/issues/1182

Update highlighting model translator to adapt new model

---

plugin/build.gradle

Since the PR https://github.com/opensearch-project/OpenSearch/pull/17900 is now merged we can just apply the gradle plugin, we can test and close the PR https://github.com/opensearch-project/ml-commons/pull/3724.

Use java-agent Gradle plugin to support phasing off SecurityManager usage in favor of Java Agent

---

plugin/src/main/plugin-metadata/plugin-security.policy

With Java agent as a replacement to security manager, we start enforcing access to UnixDomainSockets. On windows since UnixDomainSockets are used for loopback address windows builds are now starting to fail for https://github.com/opensearch-project/skills/pull/551 and https://github.com/opensearch-project/flow-framework/pull/1105.

Allow unix domain socket for loopback calls on windows

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessor.java
plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessorTests.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchResponseProcessorTests.java

fix typo in error message when input map and output map length not match.
also fix when writing to ml_inference search extension, it's only supported when one_to_one is false, so when it's an array to write into ml_inference search extension, don't split up the array and store as a whole in the search extension. 

fix error message when input map and output map length not match

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutorTest.java
plugin/src/main/java/org/opensearch/ml/action/agents/TransportRegisterAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/settings/MLCommonsSettings.java
plugin/src/test/java/org/opensearch/ml/action/agents/RegisterAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportCreateConnectorActionTests.java

The MCP feature enables customer to provide connection details about an MCP server via an MCP connector. This feature is being released as an experimental feature and hence we will expose it behind a feature flag.
To use MCP feature, one has to set the feature flag `plugins.ml_commons.mcp_feature_enabled` to `true`
This feature flag blocks the following when disabled:
- Creation of an MCP connector
- Creation of an Agent with MCP tools
- Executing an Agent created with MCP …

Add Feature Flag for MCP connectors Feature

---

ml-algorithms/src/test/java/org/opensearch/ml/engine/encryptor/EncryptorImplTest.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/test/java/org/opensearch/ml/action/agents/GetAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/model_group/GetModelGroupTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/models/GetModelTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/DeleteTaskTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/action/tasks/GetTaskTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelGroupManagerTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/utils/MockHelper.java

Several unit tests assume that it is possible for `client.get(request, actionListener)` to complete the listener's `onResponse()` method with `null`.  This is impossible.  See [here](https://github.com/opensearch-project/OpenSearch/blob/caf5d71ff02c5250a820f3ec1b346eff37b1d230/server/src/main/java/org/opensearch/action/get/TransportGetAction.java#L146-L165) for the ultimate return value of get requests.
What was done:
- many tests that used `actionListener.onResponse(null)` were replaced with a non-null `GetResponse` object with a `false` value for the document existing.
- for ease of review, these really are largely copy/paste with the only change being the index name
- in the case of `MLModelManagerTests` there were two nearly identical tests, one for not exists (which was fixed as …

Replace null GetResponse with valid response and not exists

---

plugin/src/main/java/org/opensearch/ml/action/agents/DeleteAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/GetAgentTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/TransportRegisterAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/agents/TransportSearchAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/DeleteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/model_group/DeleteModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/GetModelGroupTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/model_group/TransportUpdateModelGroupAction.java
plugin/src/main/java/org/opensearch/ml/action/models/DeleteModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/GetModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/models/UpdateModelTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/DeleteTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelAction.java
plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/main/java/org/opensearch/ml/cluster/MLSyncUpCron.java
plugin/src/main/java/org/opensearch/ml/helper/ConnectorAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/helper/ModelAccessControlHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelGroupManager.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskManager.java

Updates ML Commons SdkClient usage to take advantage of https://github.com/opensearch-project/opensearch-remote-metadata-sdk/pull/141 which will directly pass response objects from NodeClient and avoid serialization and parsing.
In the case of Search, this fixes the aggregation bug reported:
- https://github.com/opensearch-project/ml-commons-dashboards/issues/410
- https://github.com/opensearch-project/ml-commons/issues/3713
- https://github.com/opensearch-project/opensearch-remote-metadata-sdk/issues/132
Resolves the bugs listed above. …

Directly return Response objects from metadata client responses

---

plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLTaskRunner.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java
plugin/src/test/java/org/opensearch/ml/task/TaskRunnerTests.java

[excluding circuit breaker for Agent]

excluding circuit breaker for Agent

---

release-notes/opensearch-ml-common.release-notes-3.0.0.0.md

change release note to add MCP server feature

change release note

---

ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/McpConnectorExecutor.java
plugin/build.gradle

We are using the 0.9 version of MCP to make it compatible with MCP server and also, the MCP have back ported the custom headers change to 0.9 (initially anticipated for 0.10)
Removed the extra content type header since it is being added by MCP client by default.

Downgrade MCP version to 0.9

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorRequest.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLUpdateConnectorRequest.java
common/src/main/java/org/opensearch/ml/common/transport/model/MLUpdateModelRequest.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupRequest.java
common/src/main/java/org/opensearch/ml/common/transport/model_group/MLUpdateModelGroupRequest.java
common/src/main/java/org/opensearch/ml/common/transport/register/MLRegisterModelRequest.java
common/src/main/java/org/opensearch/ml/common/utils/FieldDescriptor.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorRequestTests.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLUpdateConnectorRequestTests.java
common/src/test/java/org/opensearch/ml/common/transport/model/MLUpdateModelRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLRegisterModelGroupRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/model_group/MLUpdateModelGroupRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/register/MLRegisterModelRequestTest.java
common/src/test/java/org/opensearch/ml/common/utils/StringUtilsTest.java

add validation for name and description for model model group and connector resources
resolved https://github.com/opensearch-project/ml-commons/issues/3639
Integ test will fail as code coverages is failing for previously merged PR.

add validation for name and description for model model group and connector resources

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessor.java
plugin/src/test/java/org/opensearch/ml/processor/MLInferenceSearchRequestProcessorTests.java

Ensures that Sparse Vectors can be parsed by ML Inference Request processor during rewrite.
Next steps can be to write a tutorial showing how we can run neural sparse search with ML Inference request processor.
Resolves #3767
spotlessApply && `./gradlew test`

Adds Json Parsing to nested object during update Query step in ML Inference Request processor

---

common/src/test/java/org/opensearch/ml/common/connector/McpConnectorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/AgentUtilsTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/McpConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/McpSseToolTests.java

Adds Unit tests for MCP feature
this tests the files:
- [McpConnector.java](https://github.com/opensearch-project/ml-commons/blob/main/common/src/main/java/org/opensearch/ml/common/connector/McpConnector.java)
- [McpConnectorExecutor.java](https://github.com/opensearch-project/ml-commons/blob/main/ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/McpConnectorExecutor.java)
- [getMcpToolSpecs function in Agent Utils](https://github.com/opensearch-project/ml-commons/blob/6187de8d991a64d9eefeef789fa5ee0d1e3e2390/ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java#L654C24-L654C39)
We use the getConnector function in agent utils. To test the `getMcpToolSpecs`, we need to mock the internals of the get connector function using …

Add Unit Tests for MCP feature

---

common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorRequest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorRequestTests.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/ModelHelperTest.java

[for inline model connector name isn't required
We added validation for connector name during connector creation. But when for inline model where connector is the part of the model object, there we don't need connector name. So we are removing this validation for inline model connector. 
]

for inline model connector name isn't required

---

plugin/src/main/java/org/opensearch/ml/stats/MLStatsInput.java

Refactors MLStatsInput to use `StreamInput::readOptionalEnumSet` and `StreamOutput::writeOptionalEnumSet` from OpenSearch core, added in this recent PR: https://github.com/opensearch-project/OpenSearch/pull/17556
The currently this is implemented in ml-commons using a private helper. I added this functionality to core using ml-commons as a reference so it could be reused in neural search, so the implementation is identical. While I made this change so other plugins could use the same function, I figure it might make sense to use it in ml-commons as well.
Compare
[ml-commons implmentation](https://github.com/opensearch-project/ml-commons/blob/main/plugin/src/main/java/org/opensearch/ml/stats/MLStatsInput.java#L142-L149)
```
private void writeEnumSet(StreamOutput out, EnumSet<?> set) throws …
```

Use stream optional enum set from core in MLStatsInput

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/SearchIndexTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/SearchIndexToolTests.java

We want to align the schema of tools in agent and MCP, but now different tools has different ways to parse arguments from parameters map, we need to figure out how they done this and how to align based on the investigation.
**Example**
The registration request body of SearchIndexTool in ReAct agent could be: 
```
{
"name": "SearchIndexTool",
"type": "SearchIndexTool",
"description": "Use this tool to search an index by providing two parameters: 'index' for the index name, and 'query' for the OpenSearch DSL formatted query. Only use this tool when both index name and DSL query is available.",
"attributes": {
"input_schema": {
"type": "object",
"properties": {
"index": {
"type": "string"
},
"query": {
"type": "string"
}
},
"additionalProperties": false
}
}
}
```
But in MCP tools, the tool's …

change SearchIndexTool arguments parsing logic

---

common/src/main/java/org/opensearch/ml/common/transport/prompt/MLPromptDeleteAction.java
common/src/main/java/org/opensearch/ml/common/transport/prompt/MLPromptDeleteRequest.java
common/src/test/java/org/opensearch/ml/common/transport/prompt/MLPromptDeleteRequestTest.java
plugin/src/main/java/org/opensearch/ml/action/prompt/DeletePromptTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLDeletePromptAction.java
plugin/src/test/java/org/opensearch/ml/action/prompt/DeletePromptTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeletePromptActionTests.java

Implements an API to delete a prompt 
Resolves #3711 

DELETE Prompt API 

---

ml-algorithms/build.gradle

Resolves CVE-2025-48734 for 3.1 release
Following https://github.com/opensearch-project/sql/pull/3782

force beanUtils to 2.0 to address CVE-2025-48734

---

plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/main/java/org/opensearch/ml/action/prompt/TransportCreatePromptAction.java
plugin/src/main/java/org/opensearch/ml/action/prompt/UpdatePromptTransportAction.java
plugin/src/main/java/org/opensearch/ml/prompt/MLPromptManager.java
plugin/src/test/java/org/opensearch/ml/action/prediction/TransportPredictionTaskActionTests.java
plugin/src/test/java/org/opensearch/ml/action/prompt/TransportCreatePromptActionTests.java
plugin/src/test/java/org/opensearch/ml/action/prompt/UpdatePromptTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/prompt/MLPromptManagerTests.java

Enables prompt execution through predict model. This PR also allow unique name across prompts
Resolves #3711

Prompt Execution via Predict

---

plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java

Add mcp system indices to system index descriptor

Add mcp system indices to system index descriptor

---

ml-algorithms/build.gradle

the previous PR (https://github.com/opensearch-project/ml-commons/pull/3915) didnt convert the dependency to a different version. This PR does
I'm borrowing from https://github.com/opensearch-project/query-insights/pull/370/files I tested locally to see before and after this time. 
Solves  https://github.com/opensearch-project/ml-commons/pull/3915 properly
You can see the dependency is now `commons-beanutils:commons-beanutils:1.9.4 -> 1.11.0
`
```
./gradlew :opensearch-ml-algorithms:dependencyInsight \
--dependency commons-beanutils \
--configuration runtimeClasspath
=======================================
OpenSearch Build Hamster says Hello!
Gradle Version        : 8.11.1
OS Info               : Mac OS X 15.5 (aarch64)
JDK Version           : 21 (Amazon Corretto JDK)
JAVA_HOME …
```

properly handles commons-beanutils to 1.11.0 fixes CVE-48734

---

plugin/src/main/java/org/opensearch/ml/action/mcpserver/TransportMcpToolsRemoveOnNodesAction.java

When registering a new tool and remove it immediately, there could be an error like below:
```
Tools: [My_SearchIndexTool] are removed successfully in index but failed to remove from mcp server in memory with error: Tools: [My_SearchIndexTool] not found on node: 84yLg-Q8TvSw7d7MpwwXAw
```
This happens when a tool is not registered first time, the reason is an internal map is maintaining the tools, and during removing, the tool is not been removed from the map then when re-registering the tool, it can't be added into the MCP server memory.
NA …

Fix tool not found in MCP memory issue

---

plugin/src/main/java/org/opensearch/ml/model/MLModelCache.java
plugin/src/main/java/org/opensearch/ml/model/MLModelCacheHelper.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/task/MLPredictTaskRunner.java
plugin/src/test/java/org/opensearch/ml/model/MLModelCacheHelperTests.java
plugin/src/test/java/org/opensearch/ml/model/MLModelManagerTests.java

Currently the remote model auto-deploy only happens when the model is not deployed at all, by checking the running worker nodes == 0. But in some edge cases, we'd like to auto-deploy the model even it's in PARTIALLY_DEPLOYED status.  
The planning worker nodes are synced in the memory so when there is a partially deployed status, the auto deploy will apply.  

run auto deploy remote model in partially deployed status

---

common/src/main/java/org/opensearch/ml/common/connector/Connector.java
common/src/main/java/org/opensearch/ml/common/connector/McpConnector.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportCreateConnectorActionTests.java

This pull request addresses a security concern where user input, in this case specifically the connector URL was being exposed in error messages. Exposing such information can inadvertently leak sensitive data and does not align with security best practices.
Fix:
Updated the error handling logic to avoid printing the connector URL in error messages, thereby preventing potential information disclosure.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING.md#developer-certificate-of-ori …

Fix exposed connector URL in error message

---

common/src/main/java/org/opensearch/ml/common/MLTask.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java

When an agent is executed in async mode and the task is retrieved, we see the is_async parameter in response as false.
```
GET /_plugins/_ml/tasks/<task_id>
{
...
"is_async": false,
"response": {
...
}
}
```

Fix is_async status of agent execution task

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandler.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandlerTest.java

Current if model response is empty, ml-commons returns a 400 error code and error message showing the response is empty. This is problematic because it doesn't show the true status code from the remote service and several customers complained that this error code/message is hard for them to understand the real errors. 
This PR fixes this problem and shows better error code and message based on different type of errors received from the remote model service. …

fix the error status code and message for empty response

---

plugin/src/test/java/org/opensearch/ml/rest/MLCommonsRestTestCase.java
plugin/src/test/java/org/opensearch/ml/tools/ListIndexToolIT.java

1. Don't delete `.plugins-ml-config` index for Integration test, As the master key stores in this index, delete and recreate will cause the value in [Encryptor](https://github.com/opensearch-project/ml-commons/blob/main/ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java#L81) is not consistent for encrypt and decrypt.
A exception flow may looks like 
- cluster initialized -> masterkey KeyA -> value in Encryptor is masterkey KeyA
- IT1 run finish -> remove `.plugins-ml-config` index
- IT2 start to run create a connect will use masterkey KeyA persistent in [Encryptor](https://github.com/opensearch-project/ml-commons/blob/main/ml-algorithms/src/main/java/org/opensearch/ml/engine/encryptor/EncryptorImpl.java#L130-L132) 
- MLSyncUpJob run every 10s -> will create …

Keep .plugins-ml-config index for Integration test

---

ml-algorithms/build.gradle

exclude commons-beanutils and force from 1.9.4 to 1.11.0

exclude commons-beanutils

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/AgentUtilsTest.java

[Backport 3.1] enhance tool input parsing and add agentic rag tutorial (#4023)

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/QueryPlanningTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/QueryPlanningToolTests.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/rest/RestQueryPlanningToolIT.java

This query planner tool is going to take a query text as a nature language question. Based on the question, the agent should intelligently identify relevant indices and construct appropriate queries. This includes:
* generating queries using an LLM (Large Language Model).
* Or Leveraging default search/query templates.
* Or Use user defined search/query templates、
Interface：
```
POST /_plugins/_ml/agents/_register
{
"name": "Test agent for embedding model",
"type": "flow",
"description": "this is a test agent",
"tools": [
{
"type": "QueryPlanningTool",
"description": "A general query generation tool to answer any question",
"type": "llmGenerated",
"model_id": "h5AUWo0BkIylWTeYT4SU",
"prompt": "\n\nHuman:You are a query generation agent for OpenSearch. You will always …
```

Initiate query planning tool

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/QueryPlanningPromptTemplate.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/QueryPlanningTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/QueryPlanningToolTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestQueryPlanningToolIT.java

This change adds a default system prompt to the query planner tool
Create Model:
```
{
"name": "My OpenAI model: gpt-4o",
"connector": {
"name": "My openai connector: gpt-4",
"description": "The connector to openai chat model",
"version": 1,
"protocol": "http",
"model": "gpt-4o"
},
"openAI_key": <YOUR API KEY>
},
"actions": [
{
"action_type": "predict",
"method": "POST",
"url": "https://api.openai.com/v1/chat/completions",
"headers": {
"Authorization": "Bearer ${credential.openAI_key}"
},
"request_body": "{ \"model\": \"${parameters.model}\", \"messages\": [{\"role\":\"system\",\"content\":\"${parameters.system_prompt}\"},{\"role\":\"user\",\"content\":\"${parameters.query_text}\"}] }"
}
]
}
}
```
2. …

Add Default System Prompt for the query Planner tool

---

common/src/main/java/org/opensearch/ml/common/settings/MLCommonsSettings.java
common/src/main/java/org/opensearch/ml/common/settings/MLFeatureEnabledSetting.java
common/src/test/java/org/opensearch/ml/common/settings/MLFeatureEnabledSettingTests.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/QueryPlanningTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/QueryPlanningToolTests.java
plugin/src/main/java/org/opensearch/ml/action/agents/TransportRegisterAgentAction.java
plugin/src/main/java/org/opensearch/ml/action/connector/TransportCreateConnectorAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/agents/RegisterAgentTransportActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestQueryPlanningToolIT.java
plugin/src/test/java/org/opensearch/ml/settings/MLFeatureEnabledSettingTests.java

Add the feature flag `plugins.ml_commons.mcp_connector_enabled` defaulted to false for agentic search feature.
Prevent registering and executing agents with queryPlannerTool.
Resolves  https://github.com/opensearch-project/ml-commons/issues/4005

Add feature flag for agentic search

---

common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java
common/src/main/java/org/opensearch/ml/common/settings/MLFeatureEnabledSetting.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLGetMemoryAction.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLGetMemoryRequest.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLGetMemoryResponse.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLGetMemoryRequestTest.java
common/src/test/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLGetMemoryResponseTest.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/TransportGetMemoryAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLGetMemoryAction.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportGetMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGetMemoryActionTests.java

Get Memory API:
```
GET /_plugins/_ml/memory_containers/{memory_container_id}/memories/{memory_id}
```
Response:
```
{
"session_id": "sess_cd423e34-bc8d-48cc-bf96-4667b043f0df",
"memory": "My name is John and I work at TechCorp as a software engineer",
"memory_type": "RAW_MESSAGE",
"agent_id": "agent_123",
"role": "user",
"created_time": 1754421423498,
"last_updated_time": 1754421423498
}
```
When invalid memory container is presented:
```
{
"error": {
{
"type": "status_exception",
"reason": "Memory container not found"
}
],
"type": "status_exception",
"reason": "Memory container not found"
},
"status": 404
}
```
When invalid memory ID is presented:
```
{
"error": {
{
"type": "status_exception",
"reason": "Memory not found with id: rrrr"
}
],
"type": …
```

GET memory API

---

plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsActionTests.java

There is a edge case in which a undeploy action where the model is not existent in cache results in a misleading call to Get model. 
Currently the code to undeploy models where the edgecase is handled uses client.bulk while this works for local environments, it falls short for those that use remote data sources. This PR refactors the current client.bulk operation to use the sdkClient instead, while keeping the tests verified
Resolves N/A
Ran `./gradlew run --debug-jvm` and forced  `modelNotFoundInNodesCache` to trickle the edge case logic and verified that the write to index happens successfully.
https://github.com/opensearch-project/ml-commons/blob/76220f7d17f64d834754e835e384cc8b4c854109/plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java#L208
By …

Refactor client.bulk to sdkClient.bulkDataObjectAsync when undeploying models with empty model cache edgecase

---

plugin/src/main/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsAction.java
plugin/src/test/java/org/opensearch/ml/action/undeploy/TransportUndeployModelsActionTests.java

Manual 2.19 Backport of #4075
+ Applied spotless
+ Added the warning to undeploy action

[2.19 backport] refactors undeploy models client with sdkClient bulk op

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/MLAgentExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/indices/MLIndicesHandler.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/indices/MLIndicesHandlerTest.java
plugin/src/main/java/org/opensearch/ml/action/connector/ExecuteConnectorTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/handler/MLSearchHandler.java
plugin/src/main/java/org/opensearch/ml/action/tasks/CancelBatchJobTransportAction.java
plugin/src/main/java/org/opensearch/ml/action/tasks/GetTaskTransportAction.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/models/SearchModelTransportActionTests.java

Currently in environments where MultiTenancy is Enabled and indices are pre-populated outside of the local environment **there is a cache invalidation issue**. When this occurs there exists a local cold node that checks that the index exists. 
```
clusterService.state().metadata().hasIndex(indexName)
```
Instead we want to check that multi-tenancy is enabled and return early that we can assert logic that has the above line can continue.
-  ./gradlew spotlessApply
- ./gradlew test …

Refactor checks to ML Indices to return true when MultiTenancy enabled

---

plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/FactSearchResult.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryInfo.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryOperationsService.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemorySearchService.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/TransportAddMemoriesAction.java
plugin/src/main/java/org/opensearch/ml/helper/MemoryEmbeddingHelper.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemoryOperationsServiceAdditionalTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemoryOperationsServiceTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingServiceAdditionalTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingServiceTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemorySearchServiceAdditionalTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemorySearchServiceTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportAddMemoriesActionTests.java

[code refactoring + add unit test [memory module]

code refactoring + add unit test [memory module]

---

plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryOperationsService.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLAddMemoriesAction.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemoryOperationsServiceTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportDeleteMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportSearchMemoriesActionTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/TransportUpdateMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/helper/MemoryEmbeddingHelperTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLAddMemoriesActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLDeleteMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLSearchMemoriesActionTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLUpdateMemoryActionTests.java
plugin/src/test/java/org/opensearch/ml/utils/MemorySearchQueryBuilderTests.java

This PR specifically used to address comments or concerns in Memory API
- Add UT coverage for memories API
- suppres NONE event in add memories response
- Use XContentParserUtils.ensureExpectedToken instead of overriding

[Bug] fix: Suppres NONE event in add memories response and add UT coverage

---

plugin/build.gradle

Add current low ut coverage class to jacocoExclusions to unblock CI

fix: add current low ut coverage class to jacocoExclusions to unblock CI

---

docs/tutorials/agentic_search/agentic_search_llm_generated_type.md

Add tutorial for agentic search

Add tutorial for agentic search

---

common/src/main/java/org/opensearch/ml/common/connector/HttpConnector.java
common/src/main/java/org/opensearch/ml/common/utils/StringUtils.java
common/src/test/java/org/opensearch/ml/common/connector/HttpConnectorTest.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutor.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteConnectorExecutorTest.java

This PR adds support for parameter propagation in the predict API when using `text_embedding` function by ensuring user-supplied parameters are correctly merged into the connector's request_body and included in the outgoing request.
Resolves #4105

Parameter Passing for Predict via Remote Connector

---

build.gradle
client/build.gradle
common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle
spi/src/main/java/org/opensearch/ml/common/spi/MLCommonsExtension.java
spi/src/main/java/org/opensearch/ml/common/spi/memory/Memory.java
spi/src/main/java/org/opensearch/ml/common/spi/tools/Tool.java
spi/src/main/java/org/opensearch/ml/common/spi/tools/WithModelTool.java

Fix jdt formatter error and refactor spotless configuration. Issue is due to the external eclipse umd mirror is down.
Following the same changes made in this PR: https://github.com/opensearch-project/OpenSearch/pull/19199
Example of failing workflows:
- https://github.com/opensearch-project/ml-commons/actions/runs/17335599250/job/49221088170
- https://github.com/opensearch-project/ml-commons/actions/runs/17335599215/job/49221088122
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/ml-commons/blob/main/CONTRIBUTING. …

Fix jdt formatter error

---

common/src/main/java/org/opensearch/ml/common/model/Guardrail.java
common/src/main/java/org/opensearch/ml/common/model/LocalRegexGuardrail.java
common/src/main/java/org/opensearch/ml/common/model/MLGuard.java
common/src/main/java/org/opensearch/ml/common/model/ModelGuardrail.java
common/src/test/java/org/opensearch/ml/common/model/LocalRegexGuardrailTests.java
common/src/test/java/org/opensearch/ml/common/model/MLGuardTests.java
common/src/test/java/org/opensearch/ml/common/model/ModelGuardrailTests.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/test/java/org/opensearch/ml/rest/RestMLGuardrailsIT.java

This PR Introduce add multi-tenancy support to LocalRegexGuardrail by introducing  sdk client to perform search requests.
Resolves #4119 

Support multi-tenancy for LocalRegexGuardrail

---

common/build.gradle
memory/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle

[updating gson version to resolve conflict coming from core]

updating gson version to resolve conflict coming from core

---

plugin/src/main/java/org/opensearch/ml/processor/MLInferenceSearchResponse.java
plugin/src/test/java/org/opensearch/ml/rest/RestGenerativeSearchResponseIT.java
search-processors/src/main/java/org/opensearch/searchpipelines/questionanswering/generative/GenerativeSearchResponse.java

Please refer to #4018 for detailed description of the issue.
When using search templates with generative_qa_parameters, the RAG answer is missing from the response. This happens because:
1. Direct searches call GenerativeSearchResponse.toXContent() → includes ext block with RAG answer 
2. Template searches call GenerativeSearchResponse.innerToXContent() → missing ext block 
The core [SearchTemplateResponse](https://github.com/opensearch-project/OpenSearch/blob/55e98ed2735d898d884295c00f869f5f3278c222/modules/lang-mustache/src/main/java/org/opensearch/script/mustache/SearchTemplateResponse.java#L124) calls response.innerToXContent() instead of response.toXContent() to preserve the status field, but GenerativeSearchResponse only adds the ext block in toXContent().
Override innerToXContent() …

Fix missing RAG response from generative_qa_parameters

---

.gitignore
common/src/main/java/org/opensearch/ml/common/settings/MLCommonsSettings.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/MLEngine.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/Predictable.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/RemoteModel.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/MLEngineTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/RemoteModelTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/text_embedding/TextEmbeddingDenseModelTest.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/action/config/GetConfigTransportAction.java
plugin/src/main/java/org/opensearch/ml/model/MLModelManager.java
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/config/GetConfigTransportActionTests.java

Global resource is resources that can be accessed by any tenant, this PR is to support global resource including connector, model and agent.
- **Multi-tenant encryption**: Added logic to differentiate between global and tenant-specific resources for credential decryption
- **Remote metadata integration**: Migrated config retrieval to use SDK client with DynamoDB support
- **Configuration enhancement**: Added global tenant ID setting for cross-tenant resource management …

Add global resource support

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandler.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/MLSdkAsyncHttpResponseHandlerTest.java

This is a mitigation for https://github.com/opensearch-project/ml-commons/issues/4170
But would need a more thorough code change so that clients can handle properly all situations.
https://github.com/opensearch-project/ml-commons/issues/4170 can be closed but discussion can be done to consider different types of failures
./gradlew spotlessApply
./gradlew test

make MLSdkAsyncHttpResponseHandler return IllegalArgumentException

---

ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/QueryPlanningPromptTemplate.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/QueryPlanningTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/QueryPlanningToolTests.java
plugin/src/test/java/org/opensearch/ml/rest/RestQueryPlanningToolIT.java

- Adds field validation for QueryPlanningTool field `search_templates` to require both `template_id` and `template_description`
- Adds null check for StoredScript response, defaults to default search template if script response is null
- Adds integration tests for Search template field
Additionally includes changes from https://github.com/opensearch-project/ml-commons/pull/4176, will rebase once its merged
- [] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md). …

Adding query planning tool search template validation and integration tests

---

common/src/main/java/org/opensearch/ml/common/memorycontainer/MLMemoryContainer.java
common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/MLCreateMemoryContainerInput.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLUpdateMemoryContainerAction.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLUpdateMemoryContainerInput.java
common/src/main/java/org/opensearch/ml/common/transport/memorycontainer/memory/MLUpdateMemoryContainerRequest.java
common/src/main/resources/index-mappings/ml_memory_container.json
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportCreateMemoryContainerAction.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/TransportUpdateMemoryContrainerAction.java
plugin/src/main/java/org/opensearch/ml/helper/MemoryContainerHelper.java
plugin/src/main/java/org/opensearch/ml/rest/RestMLUpdateMemoryContainerAction.java

Add back_end Roles in the memory container for access control. Add Update Container API to update back_end_roles to allow other users to access memory.

add backendrole in container for access control and update container

---

common/src/main/java/org/opensearch/ml/common/CommonValue.java
common/src/main/java/org/opensearch/ml/common/connector/ConnectorProtocols.java
common/src/main/java/org/opensearch/ml/common/connector/McpConnector.java
common/src/main/java/org/opensearch/ml/common/connector/McpStreamableHttpConnector.java
common/src/main/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInput.java
common/src/test/java/org/opensearch/ml/common/connector/ConnectorProtocolsTest.java
common/src/test/java/org/opensearch/ml/common/connector/HttpConnectorTest.java
common/src/test/java/org/opensearch/ml/common/connector/McpConnectorTest.java
common/src/test/java/org/opensearch/ml/common/connector/McpStreamableHttpConnectorTest.java
common/src/test/java/org/opensearch/ml/common/transport/connector/MLCreateConnectorInputTests.java
ml-algorithms/build.gradle
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/agent/AgentUtils.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/McpConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/algorithms/remote/McpStreamableHttpConnectorExecutor.java
ml-algorithms/src/main/java/org/opensearch/ml/engine/tools/McpStreamableHttpTool.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/agent/AgentUtilsTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/McpConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/algorithms/remote/McpStreamableHttpConnectorExecutorTest.java
ml-algorithms/src/test/java/org/opensearch/ml/engine/tools/McpStreamableHttpToolTests.java
plugin/build.gradle
plugin/src/main/java/org/opensearch/ml/plugin/MachineLearningPlugin.java
plugin/src/test/java/org/opensearch/ml/action/connector/TransportCreateConnectorActionTests.java

Similar to SSE connectors people can now create streamable HTTP connectors and use them in agents
Only change is the connector creation:
```
{
"name": "My MCP Connector",
"description": "The connector to MCP server",
"version": 1,
"protocol": "mcp_streamable_http",
"mcp_server_key": "testmcp"
},
"parameters":{
"endpoint": "/mcp/"
},
"url": "http://localhost:9900",
"headers": {
"Authorization": "Bearer ${credential.mcp_server_key}"
}
}
``` …

[MCP Connector] MCP Connectors for streamable HTTP

---

plugin/build.gradle

1. Align log4j version with OpenSearch core
2. exclude error_prone_annotations 

Fix error_prone_annotations jar hell

---

common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryContainerConstants.java
common/src/main/java/org/opensearch/ml/common/memorycontainer/MemoryStrategy.java
plugin/src/main/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingService.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingServiceAdditionalTests.java
plugin/src/test/java/org/opensearch/ml/action/memorycontainer/memory/MemoryProcessingServiceTests.java

Allow custom prompt in the memory configuration strategy.

allow custom prompt in the agentic memory strategy

---

plugin/src/main/java/org/opensearch/ml/action/prediction/TransportPredictionTaskAction.java
plugin/src/test/java/org/opensearch/ml/action/prediction/TransportPredictionTaskActionTests.java

Skip the input interphase validation for batch_predict for now per discussed in https://github.com/opensearch-project/ml-commons/issues/4080

skip the model interface validation for batch predict

---

common/build.gradle
ml-algorithms/build.gradle
plugin/build.gradle
search-processors/build.gradle

`commons-text` versions 1.10.0 - 1.13.0 have a transitive dependency on `commons-lang3` < 3.18.0 ([ref](https://mvnrepository.com/artifact/org.apache.commons/commons-text)), which causes this [CVE-2025-48924](https://github.com/advisories/GHSA-j288-q9x7-2f5v). Upgrading `commons-text` to 1.14.0 should fix this issue.
Resolves https://github.com/opensearch-project/opensearch-build/issues/5693

Upgrade commons-text to fix CVE-2025-48924
